### ISSUE TITLE
编程思维 Python 基础班三期入学任务

### ISSUE THREAD

**Issue by CrickeySong** [AIHackers/PythonStartUp#1]
欢迎你，开智学堂「[编程思维 Python 基础班](http://t.cn/RIaJboh)」三期学友！

参加这门课程需有一定基础，为顺利参与课程，请你在 12 月 30 日前完成一个入学小任务。

任务详见下文：

## 任务说明

1. 完成[《Learn Python the Hard Way》](http://learnpythonthehardway.org/book) 小练习，**至少**前 17 个，能完成 30 个以上就真是太棒了。以往学员 20 ~ 30mins 就能完成一个小练习，相信你也可以~
2. 将上述练习成果同步到个人 GitHub 公开仓库，仓库名自定。建议你使用 Git 命令同步。

## 提交方式

- 在[本仓库](https://github.com/OpenMindClub/PythonStartUp/issues)新建一个 Issue 
	- Issue title 为 `[你的名号]完成 Py103 入学任务啦` ，例如： 云嫱完成 Py103 入学任务啦
	- 将含有你练习成果的 GitHub 仓库地址附在 Issue 正文中
	- 欢迎同时在 Issue 正文中聊聊进行入学任务时你最意外的收获，或附上你的练习笔记
- 提交截止时间：2016 年 12 月 30 日 11:42

## 其它 

1. 如果你能顺利完成入学任务，将在 12 月 30 日前收到邮件通知正式进入课程学习，否则将收到原支付渠道退还的全额学费。
2. 对任务细节有什么不清楚，欢迎在这个仓库发 Issue 提出；挑战过程中遇到困难，欢迎在本仓库发 Issue ，和其他学友交流探讨。也期待你多多在 Issues 和其他学友互动：D
3. 提交任务后，如果你还有时间，期待你继续完成 [《Learn Python the Hard Way》](http://learnpythonthehardway.org/book) 小练习，完成越多后续学习越畅快。

期待你的挑战成果~

PS. 还没有 GitHub 头像的同学，建议尽快更新头像，方便其他学友记住你。尽量各平台统一哟 ;-)

**Comment by linfeng365** [comment]
报到。

**Comment by derek-cheng** [comment]
我也报道

**Comment by StoneAmber** [comment]
Hello Python!

**Comment by amberdcowork** [comment]
报道～

**Comment by derek-cheng** [comment]
Derek完成入学任务啦Py103
[https://github.com/derek-cheng/python-learning](url)

**Comment by Geometary** [comment]
任务已完成，等待组织指示
issue link: https://github.com/Geometary/First-17-Tests/issues/1

**Comment by CrickeySong** [comment]
欢迎大家来报道！@derek-cheng @Geometary 完成入学任务的速度好快👍，但是任务提交地址不在这里哦😝，是要在本仓库下新建一个 issue 附上你的练习成果仓库地址，记得 issue 标题格式为`[你的名号]完成 Py103 入学任务啦` ，快快迁移来跟大家汇合吧~

**Comment by gzMichael** [comment]
入学任务已完成，来报道啦~
[https://github.com/gzMichael/Python_Learning](https://github.com/gzMichael/Python_Learning)

**Comment by liuxianyun5088** [comment]
报到。

**Comment by vanxv** [comment]
https://github.com/vanxv/pythonkz
入学任务已完成，来报道啦~

**Comment by leilayanhui** [comment]
蕙蕙完成 Py103 入学任务啦
https://github.com/leilayanhui/Python-Basic

**Comment by CrickeySong** [comment]
@gzMichael @vanxv 入学任务是要在本仓库下新建一个 issue 提交哦，记得 issue 标题格式为`[你的名号]完成 Py103 入学任务啦`，赶快迁移跟大家汇合咯~

**Comment by gzMichael** [comment]
刚刚更新了标题了

**Comment by Ricardotang** [comment]
[Ricardotang完成入学任务啦Py103]
(https://github.com/Ricardotang/PythonHomework)

**Comment by Yifan127** [comment]
报道，来提交入学任务啦

**Comment by mxclover** [comment]
来报道啦😊

**Comment by chuanwj** [comment]
**Corey** 完成 Py103 入学任务啦
https://github.com/chuanwj/learn-python-the-hardway

**Comment by hgccd** [comment]
报到

**Comment by VyGiBe** [comment]
报到

**Comment by yanzhiw** [comment]
报到

**Comment by stuian** [comment]
我不会是最晚完成的吧

**Comment by xucongyong** [comment]
报道

2016-12-30 9:41 GMT+08:00 stuian <notifications@github.com>:

**Comment by Tina-Tiian** [comment]
为啥只有10位童鞋没有加入milestone？莫非被漏掉了么……

**Comment by ghost** [comment]
报道

**Comment by shi1234** [comment]
报道

**Comment by scratlzj** [comment]
报道……

**Comment by sunnyhuang42** [comment]
提交任务的 Issue 上有 achievement 标签的，都应该收到入学欢迎邮件及 ch0 任务邮件了吧？

没有收到的话，赶紧微信联系 一休(aiopenmind) ，把你的任务提交地址发给他核查~

调整一下状态，用你完成入学挑战的姿势，迎接未来 12 周的 Python 探索之旅啦：D

**Comment by tcfh2016** [comment]
@ishanshan 我也还没有收到入学邮件 :( 刚发微信给一休哥了.
