### ISSUE TITLE
巨晓松完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by juthy1** [AIHackers/PythonStartUp#100]
仓库地址：https://github.com/juthy1/Python-

不说了，全是泪啊。怎么建文件这么简单的问题卡了，好几天，以前用的都是Windows的系统，现在换Mac，全在适应，传的时候又弄了半天。总之，先完成了17个，别差我一个，不掉队

**Comment by sunoonlee** [comment]
恭喜你，抢到了 100 号 issue！
由 Win 到 Mac 大概比反过来要容易一些。

**Comment by juthy1** [comment]
使用起来很好用，现在已经不用鼠标了，但是有些基本的东西找不到门啊，因为太简单了，查都查不结果，还因为英语不好，看不懂。最惨的是被一个“保存” command+s给卡了好几天，什么都做对了，就是没有得到结果，太简单了，也没人告诉，上论坛求救也不太会，上传了图，给人教训了一顿，但是没解决问题。这个郁闷啊，那几天，无端发怒、路怒，后来一个哥们在论坛了留言，看出来没保存，这才解决了。真心感谢，支付宝打了18元，请他喝咖啡。走过来挺难的，但是已经走了，就会越来越好走了。保持开放

**Comment by NBR-hugh** [comment]
万事开头难，加油！～

**Comment by juthy1** [comment]
恩恩，做第二遍就好多了，英语也大概能看懂了，谢谢鼓励，新年好
