### ISSUE TITLE
VyGiBe完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by VyGiBe** [AIHackers/PythonStartUp#103]
笔记和思考会在之后更新~
https://github.com/VyGiBe/OMPy103Ex01-17

**Comment by VyGiBe** [comment]
刚考完研究生初试，方向是视知觉，希望能过~

**Comment by VyGiBe** [comment]
### 开智元范
- [自我决定论](http://www.yangzhiping.com/psy/implementation-intentions.html)
- [刻意练习](http://www.yangzhiping.com/psy/Deliberate-Practice.html)
- [执行意图](http://www.yangzhiping.com/psy/YangQ&A-SelfDetermination.html)
- 作品说话
- 同侪压力
- 时间源头

### 基本功
1. 打字精确度和速度 Mac端软件： [Typist](https://www.abc.re/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwii3eWtwJvRAhUnqVQKHXBdBbwQFggcMAA&url=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Ftypist%2Fid415166115%3Fmt%3D12&usg=AFQjCNEdV1YXAJh7RufnrwNkWvy7Dcd6ig)
2. Markdown
3. Github操作
4. git操作
5. Blog创建

### 三项最基础编程技能
1. reading and writing, 
2. attention to detail,
3. spotting differences.

### 编程的四个基本步骤
1. 输入代码
2. 运行代码
3. 修正代码
4. 重复



 
### 学习流程闭环
**针对每一个Ex：**
1. 身边放置记事本和笔。
2. 开始练习
3. 在记事本上写下任何尚未理解的内容
4. 完成这一Ex后，通过网络搜索和询问他人回答该Ex的问题
5. 将笔记导入Studies中，每天睡前花5-10分钟过一遍

**Comment by VyGiBe** [comment]
# ex. 01  
#### 1. `print`的使用
*(先运行`print`后内容，再将运行内容的结果输出)*
  
	>>> print "string"
	string
	>>> print 'string'
	string
	>>> print 12345
	12345
	>>> a = 'string'
	>>> print a
	string
	>>> print a + a
	stringstring
	>>> print a * 3
	stringstringstring   

#### 2. 字符串的输出  
	
	>>> print "I am writing this script."
	I am writing this script. 
	>>> a = 'aaa'
	>>> print a, 'a'
	aaa a
#### 3. 在 Terminal 中运行 python 文件；

	python ex01.py
#### 4. 报错的解读；  
	
	>>> print "I am writing this script." "
	File "<stdin>", line 1
    print "I am writing this script." "
                                      ^
	SyntaxError: EOL while scanning string literal
- 1 运行的文件路径和名称(运行文件时)  
- 2 出错的行  
- 3 ^（脱字号）指出行中具体发生错误的位置  
- 4 给出错误的原因  
	
#### 5. ASCII 编码及中文的输出设定；

- 如果要输出中文，需在开头写下：  

```
# -\*- coding: utf-8 -*-
```
#### 6. [`#` 的功能](id:anchor1)  
*`#` 表示注释，之后的代码不会被执行*

- 注释的用处：  
	1. 使该部分代码的功能失用  
	2. 说明这部分代码的用处  

# ex. 02
#### 1. 注释和 “#” 符号  
见[“#”的功能](#anchor1)

#### 2. 检查代码的方法：  
倒序阅读、出声朗读

# ex. 03 
#### 基本的数字运算
##### 加减乘除  
	
	>>> 1 + 1
	2
	>>> 1 - 1
	0
	>>> 1 * 1
	1
	>>> 1 / 1
	1
 *注意浮点数和整数在 “/” 运算中的区别*
 	
	>>> for i in xrange(6):
	...     i += 1
	...     print "7 / %r = %r" % (i,7/i)
	... 
	7 / 1 = 7
	7 / 2 = 3
	7 / 3 = 2
	7 / 4 = 1
	7 / 5 = 1
	7 / 6 = 1
	>>> 1 / 4
	0
	>>> 1.0 / 4
	0.25
	>>> 1 / 4.0
	0.25
	>>> 1.0 / 4.0
	0.25
	
	 
##### 比较大小
	>>> print 4 < 4
	False
	>>> print 4 > 4
	False
	>>> print 4 == 4
	True
	>>> print 4 <> 4
	False
	>>> print 4 <= 4
	True
	>>> print 4 <= 5
	True
	>>> print 4 <= 3
	False
	>>> print 3 >= 3
	True
	>>> print 3 => 3
	  File "<stdin>", line 1
	   print 3 => 3
	          ^
	SyntaxError: invalid syntax
##### 取余 “ % ”

	>>> for i in xrange(9):
	...     i += 1
	...     print "13", "%", i, "=", 13 % i
	... 
	13 % 1 = 0
	13 % 2 = 1
	13 % 3 = 1
	13 % 4 = 1
	13 % 5 = 3
	13 % 6 = 1
	13 % 7 = 6
	13 % 8 = 5
	13 % 9 = 4
##### “print a, b”中“,”的意义
	
	>>> print 1, 1 + 2, 3
	1 3 3

**Comment by VyGiBe** [comment]
## Ex.18 Names, Variables, Code, Functions

## 核查清单(函数)：
***
###### 写一函数时

1. Did you start your function deﬁnition with def? 
2. Does your function name have only characters and _ (underscore) characters? 
3. Did you put an open parenthesis ( right after the function name? 
4. Did you put your arguments after the parenthesis ( separated by commas? 
5. Did you make each argument unique (meaning no duplicated names)? 
6. Did you put a close parenthesis and a colon ): after the arguments? 
7. Did you indent all lines of code you want in the function four spaces? No more, no less. 
8. Did you “end” your function by going back to writing with no indent (dedenting we call it)? 

###### 用一函数时
1. Did you call/use/run this function by typing its name? 
2. Did you put the ( character after the name to run it? 
3. Did you put the values you want into the parenthesis separated by commas? 
4. Did you end the function call with a ) character?



## 函数
***
#### 概念理解
- 黑箱比喻。

#### 函数的三种功能

1. They name pieces of code the way variables name strings and numbers.   
	命名小段代码。  
2. They take arguments the way your scripts take argv.   
	喂入(携带)参数。  
3. Using # 1 and # 2, they let you make your own “mini-scripts” or “tiny commands.”  
	上述功能可使得自己能编写小指令集。

#### 定义过程[^1]

```
def function(argv):
	<statement>
```	

[^1]:括号中可以没有参数  



## Q & A
***
  

Q - `def`的意义？  
A - define的缩写，声明开始定义函数。

  

Q - `argv`这一缩写的意义？  
A - argument vector


  

Q - `*argv`中的`*`的意义？   
A - That tells Python to take all the arguments to the function and then put them in args as a list.


  

Q - 为什么函数会给出None的值   
A - 因为函数中没有return相应值

  

Q - 缩进和代码运行之间的关系？   
A - [Python: Myths about Indentation](http://www.secnetix.de/olli/Python/block_indentation.hawk)

  

Q - 函数名的命名原则   
A - 和变量名命名方式一致


	
## 出错
***
### 错误一  

```
$ python ex18.py
  File "ex18.py", line 15
    def print_none()
                   ^
SyntaxError: invalid syntax
```
处理  

```
def function(): # 注意之后的“:”
```
### 错误二  

```
$ python ex18.py
  File "ex18.py", line 25
    Study Drills
               ^
SyntaxError: invalid syntax
```
处理  

- 应该加上 `#` 符号，

### 出错三



	def add_strings(strings):
		result = ""
		for i in strings:
			result += i
		print result	
		
	strings = ["aaa","bbb","ccc"]
	print add_strings
	
	<function add_strings at 0x100a15c80>

处理  

	print add_strings(strings)

### 出错四

	$ python ex18.py
	  File "ex18.py", line 29
		for i in strings:
	    ^
	IndentationError: unexpected indent

处理  

- 因为在函数内按了两下**Tab**，导致不能运行。
- 减少一个缩进

**Comment by VyGiBe** [comment]
# Ex.19 Functions and Variables



## 本练习内容概要
***
#### 调用函数时  
1. 可直接赋值  
2. 可将值赋给变量，然后将变量带入函数  
3. 可在函数的()内进行数字的运算  
4. 可在函数的()内进行数字和变量的复合运算  


#### 函数中的变量和代码中的变量相隔离
###### 举例

	def function(arg):
		var = arg
		return var

	var = "I am a variable"
	result = function("It is different from 'var'!")
	
	print var, "\n", result, "\n"
	
	result = function("It is different from 'var'!")
	var = "I am a variable"	 
	
	print var,"\n" ,result, "\n"
```
I am a variable 
It is different from 'var'!
	
I am a variable 
It is different from 'var'!
```

## Q & A
***
Q - 如何理解一个函数时如何运作的？  
A - （1. 上方加注释； 2. 出声朗读； 3. 将代码打印出，用图画出，并注释如何运行。 ）
> There’s many different ways, but try putting an English comment above each line describing what the line does. Another trick is to read the code out loud. Yet another is to print the code out and draw on the paper with pictures and comments showing what’s going on.  

Q - 什么是global variables？  
A - 
> In computer programming, a global variable is a variable with global scope, meaning that it is visible (hence accessible) throughout the program, unless shadowed. - From [Wikipedia](https://en.wikipedia.org/wiki/Global_variable)

Q - 定义函数时，参数个数有限制吗？   
A - 有，但该值还是很大的

Q - 能在函数内调用函数吗？   
A - 可以

**Comment by NBR-hugh** [comment]
笔记格式清晰，示例详细，从中get到将错误示例的代码原本与提示再标注出来可读性会更高，感谢～@VyGiBe

**Comment by VyGiBe** [comment]
今天的一个发现：
```
>>> "a" > 3
True
```
> python版本为2.7.10   
[Stackoverflow上的回答](http://stackoverflow.com/questions/7969552/why-does-4-3-return-true-in-python-2)
