### ISSUE TITLE
袁长亮完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by hhxjycl** [AIHackers/PythonStartUp#105]
作业链接：https://github.com/hhxjycl/pyex
python和Git都是纯纯的小白，一步一个坑。过程中考虑过放弃，但还是想过了这关。”一定要坚持下去“
测试代码，找错误的时候很有意思，一点一点找，最后还是很开心的。
看到一些同学对代码分析的很详细，非常佩服！
git主要是看了《GitHub入门与实践》及[Pro Git（中文版）](http://git.oschina.net/progit/1-起步.html)

**Comment by sunoonlee** [comment]
适度困难之下 成长最快~

**Comment by hhxjycl** [comment]
痛苦、刺激、享受，仅仅是开始
