### ISSUE TITLE
elefnt完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by elefnt** [AIHackers/PythonStartUp#107]
作业仓库地址：https://github.com/elefnt/pythonbasic

程序小白入手，举步维艰，lpthw还算细致和友好，github入门学习曲线太高，
特别是系统环境搭建和设置，很多知识点开始不理解，对比多方阐述才稍稍入门，
用命令行把本地仓库commit/push到remote端也是如履薄冰，试错了好几次，不知道如何回复，
只能删除重来。
下面要更有耐心，慢慢来过了。

**Comment by sunoonlee** [comment]
别着急。以往习惯的图形界面跟命令行本来就是两个世界，而 Git 刚上手确实不那么友好。多花点时间适应就好了 😄

**Comment by elefnt** [comment]
是啊，而且我自己时间和精力的分配能力也要升级，可能平常干急活多的缘故，结果导向习惯明显，新知识的学习自有一套规律和节奏，很多细节和知识点需要通过反复观察，练习和阅读，依靠时间沉淀下来，才能理解和掌握，急不来。
