### ISSUE TITLE
chase779完成 Py103 入学任务

### ISSUE THREAD

**Issue by chasejwang** [AIHackers/PythonStartUp#11]
我被朋友介绍这个课程， 无聊的时候已经完成一部分Learn python the hard way: 
Here is the link: 
https://github.com/chasejwang/lpthw

I still keep doing it, hope finish it before the class starts.

**Comment by xpgeng** [comment]
标题没有 `啦` .  差评...!   :stuck_out_tongue_closed_eyes:
