### ISSUE TITLE
六一完成Py103入学任务啦！

### ISSUE THREAD

**Issue by Irene6161** [AIHackers/PythonStartUp#114]
## 入学前感想

我可能是最后一个交作业的人吧？给自己一个翻上天得白眼。后期只要有空，就把笔记整理补上来，今晚先聊一下感想。

###  好奇心驱动报名
之前一直决心报认知写作班，对Python班出于感兴趣但是并不是很强烈的状态，但是由于各种原因，和大概了解了Python之后，发现自己对它十分好奇，嗯，就是好奇（因为不知道自己学了有什么用）。临时决定交费加入，然后发现入学前一周正好是我在外旅行的一周，于是带着书上路了，想着回来最后一天完成。（觉得自己这个行为蠢透了，应该带着笔记本出发的。）

###  零基础从书本入门（看了5天书才碰电脑）
整个路上只要有时间就会翻出来看书，虽然零基础但还是觉得很吸引人。
因为没有电脑，只能脑内演示操作流程和代码，如此反复几遍，自认为应该没有问题。
然而到家的今天，才发现第一步就出了问题，这个就是自己“以为”学会了，和真正理解的最大差距。
这个或许是建立了“必要难度”，当自己以为自己学会的时候，和实际操作时候遇到的问题相比，更深刻的理解了阳老师经常提到的“必要难度”。

###  感优秀同侪动力
因为明天就是截止日期，刚下飞机赶到家就拼命的敲代码，幸好又刘忙和文燕两位小伙伴，被我骚扰无数次还是超级耐心，好感动。优秀同侪的动力和支持，是我这一次赶在最后时刻完成作业的最大助力，感谢你们，爱你们！

**Comment by ouyangzhiping** [comment]
哈哈，加油:D 期待能顺利挺过Py课，未来再来接受我的认知写作学四期摧残，已经感觉到你的整个2017年上半年都是求虐的半年了。。。。

**Comment by Irene6161** [comment]
@ouyangzhiping 充满了期待！！哈哈哈
