### ISSUE TITLE
浚宇完成Py103入学任务

### ISSUE THREAD

**Issue by Wangjunyu** [AIHackers/PythonStartUp#115]
- 练习[地址](https://github.com/Wangjunyu/lpthw_pracitse/tree/master/basic_practise_files_0-17)
- 练习[回顾](http://blog.junyu.pro/posts/python/0705-lpthw-1-17-summary-1.html)
- 学习方法[探讨](http://blog.junyu.pro/posts/python/0704-programing-learning.html)
- 字符串部分[理解](http://blog.junyu.pro/posts/python/0703-learnpythonthehardway-strings.html)

看到了许多Data103的学霸，还未开学同侪压力凸显，一起努力。

**Comment by ouyangzhiping** [comment]
晕，没想到junyu报名Py基础班了.... 这个班面向的是没有Py基础的同学。不过重新锤炼一下也好，大妈的编程思维训练是极好的。但不要耽误未来跟随童牧老师上手人工智能。

**Comment by ouyangzhiping** [comment]
晕，没想到junyu报名Py基础班了.... 这个班面向的是没有Py基础的同学。不过重新锤炼一下也好，大妈的编程思维训练是极好的。但不要耽误未来跟随童牧老师上手人工智能。

**Comment by Wangjunyu** [comment]
@ouyangzhiping  深感自己代码基础薄弱，质量急需提高，现在更新了学习方法以实践为基础，会努力跟上两门课的内容。

另外也是想和源头的 大妈建立连接，向高手学习。
