### ISSUE TITLE
elsaxxx完成Py103入学任务啦！

### ISSUE THREAD

**Issue by elsaxxx** [AIHackers/PythonStartUp#120]
## 感受
真的是零基础学这个啊！刚开始的ex0都搞得我头都大了，一直用shell运算不出来正确的显示方式，搞了好久才解决自己的问题，然后第一节课ex1，也是让我抓狂，在知乎抓到一个大神，才解决了自己的问题，真是体会了万事开头难啊，慢慢就好多了，嗯，勇于面对困难就是胜利啊！

## 作业
https://github.com/elsaxxx/python-studying

**Comment by sunoonlee** [comment]
从 0 到 1 是重要的一步 :+1:
