### ISSUE TITLE
kaikai完成Py103入学任务啦！

### ISSUE THREAD

**Issue by vfrbdxf** [AIHackers/PythonStartUp#121]
[入学任务地址](https://github.com/vfrbdxf/Pythontest)

**Comment by sunoonlee** [comment]
同学，Markdown 的链接是这样写滴
`[你想要链接显示的文字](https://github.com/vfrbdxf/Pythontest)`

**Comment by noylau** [comment]
@ishanshan 您好，请问为什么我的Issue里显示是 No milestone呢？

**Comment by sunnyhuang42** [comment]
@17days 不好意思，可能是忘记设置了。现在配置好啦 ，见 #87
