### ISSUE TITLE
stuian完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by stuian** [AIHackers/PythonStartUp#123]
[作业链接](https://github.com/stuian/exercise)

-收获：
-报名后第二天我就去买了书，全英文阅读对我来说还是太困难了，不过我正在让自己适应英文阅读
-书的每一个练习我都认真看了，还在书上做了笔记以及自己的一些尝试和问题
-不知道是因为看要仔细还是理解问题，我觉得我还是花了很多时间的，总的来说还是觉得效率不够高
-以后要提高效率，遇到问题还要想大家请教。

-问题：
-练习当中，我遇到的问题很挺多的，我觉得大部分是跟我想看“这样行不行，那样行不行”的尝试中出现的
-书写我一般很少出错，因为我写的时候就很小心，但也有出错的时候。比如说，我有一次把print打成了pright，检查的时候并没有发现，弄得我很烦，不知道哪错了。

-大多的错误还是语法，比如说
-SyntaxError:invalid syntax
或者其它错误:
-IndentationError:unexpected indent
-TypeError:function takes exactly 1 argument (6 given)

有些错误我还是看不懂的。
所以还需要多加学习。

**Comment by sunoonlee** [comment]
初学时的尝试和探索很花时间；这不是低效率，而是必经之路。
