### ISSUE TITLE
xbaiyuan完成入学任务啦

### ISSUE THREAD

**Issue by xbaiyuan** [AIHackers/PythonStartUp#124]
* 任务提交[地址](https://github.com/xbaiyuan/lpthw_practice)
* 对学习方法的[反思](https://github.com/xbaiyuan/lpthw_practice/blob/master/review_why_hard_is_easy.md)

**Comment by sunoonlee** [comment]
发现产品部落大牛一只~

> 持续练习编程的初学者会在某一天获得Aha moment，这个Moment意味着，在「读」的阶段，大量的外显知识已经转化为内隐知识，工作记忆的负荷大大减少；在「写」的阶段，肌肉记忆已经形成

写得真好！
