### ISSUE TITLE
学习phthon遇见问题

### ISSUE THREAD

**Issue by Xiongxiongxiongc** [AIHackers/PythonStartUp#136]
## 自学phthon
- crypto_list = ['Yeti','Bigfoot','Loch Ness Monsters']
>>> crypto_string = ', '.join(crypto_list)
>>> print('Found and signing book deals:',crypto_string)
('Found and signing book deals:', 'Yeti, Bigfoot, Loch Ness Monsters')
- 最后一段，应该没有 ‘ ‘ 和 （），不知道是哪里出错了，求大神解答。。

**Comment by JCWDFCS** [comment]
你得贴出来报错的内容。

**Comment by iamzhuoxuan** [comment]
是的呢，提供更充分信息，别人才能为你解答哦〜

**Comment by iamzhuoxuan** [comment]
过期关闭啦〜
