### ISSUE TITLE
王大可完成py104的任务啦！

### ISSUE THREAD

**Issue by xiewuqi** [AIHackers/PythonStartUp#139]
# 《笨办法学Python》 小结 

- 作业地址：https://github.com/xiewuqi/Py101

### 命令行
- 从来没接触过命令行，这里卡了一段时间学习附录里面的内容。自己尝试配置了iterm2终端 ，iterm2 的强大之处还在体会中。其实还是只会 附录里面教的简单内容。

### ex0 ~ ex10

这部分的内容比较简单。主要是介绍
- 如何安装 Python 和 编辑器
-  print 语句的用法
- 如何注释   
- 数学运算
- 变量和文本，转义字符

### ex10 - 17
- 这部分的内容主要讲 输入 、输出，和如何接收参数，写入文档。这部分花的时间比较久，一开始看不懂，自己就把代码打出来，运行，直到结果个书上的一样。多做了几个习题后，回过头来看，发现自己已经看的懂前面的内容了。

### ex18 - 26
- 这部分做起来顺一点，多了新内容 自定义函数，return 返回函数的。还有就是对前面的内容回顾。感觉还比较顺吧。

### ex27 - 40
- 下半部分，多出的新内容 布尔逻辑、for 循环 while 循环。if 、elif 、else 条件语句的用法。列表的基本知识，和字典的基本知识。
- ex37 是个梗，背不下来 ，让后就把它条过去了。

### ex41 - 52 
- 这部分内容也学了一点，不过发现难度比前面的大多了，前面一直是抄作者的代码，主要是作者引导，认知负荷度很小，导致要到后面写代码的时候自己不会写了，这是自己目前遇到的最大的困难，自己写程序的时候就不知如何下手。 

## 主要遇到的问题和解决。
- 《笨办法学Python》一个基本的模式就是，输入代码 > 运行 > 调试 > 直到和书本一样。
- 所以遇到最多的错误是 代码 输入错误。
- 解决错误有如下方案
    1. 把提示错误的行，好好阅读一遍 
    2. 倒着读代码，一个一个的 核对一遍
    3. 如果还没运行成功，放一放，过段时间在来检查。
    4. 实在不行就重新输入，输入少一点内容就调试一下。
    5. 把自己的代码和网上的代码做**对比**（这好像作弊了，不推荐）

**Comment by xiewuqi** [comment]
# 2017-02-15-Git.md
## Git 的前世今生
> 这个要从开源运动说起，1991年Linus创立了开源的Linux 。
很多人参与Linus的开发，但是代码一直不好管理。
开源精神不乏有梁山好汉的气息，有人试图破解正在使用的BitKeeper正在用的版本系统，结果被发现了，要收回Linux的免费使用权。
一周之后， Git诞生了。
2008 年GitHub网址上线，无数开源项目迁移到GitHub。
### Git是什么？
Git 是一款分布式的版本管理软件，适合管理二进制文件，就是适合 代码 文档什么之类。
### 什么是分布式？
- 这就要从svn的集中式仓库说起，集中式好比一个图书馆，你从里面拿一本图书出来修改，在放回去，期间只有你能使用。而且必须要联网，如果服务器死机资料还可能丢失。
- 分布式：任何一台都可以当主机，而且可以吧数据拷贝到任何一台电脑，离线操作。可以分模块开发，完成好之后，提交到 GitHub 远程仓库，和自己搭建服务器开发。
### 为什么要用版本管理仓库？
- 所有人都需要版本管理，一个PPT，老板不满意要你修改，“另存为1”，你加班到半夜，又有新的思路，“另存为2”，第二天说是要增加新内容，好把，再“另存为3"...
这样麻不麻烦？有Git就不一样了。
- Git是世界上最好的分布式版本管理仓库，没有之一。可以让你查看历史版本，版本之间轻松穿梭。
- 这么酷版本管理软件，干嘛不学？

## 安装配置Git
### Mac 安装 Git
- 安装 Xcode 的时候默认安装
- 或者homebrew安装
### Win 安装 Git
地址：https://git-for-windows.github.io
### Liunx
这个大神请绕道，还没用过Liunx 。
- 安装完成后进行配置
```
$ git config --global user.name "Your Name"
$ git config --global user.email "email@example.com"
```
## 常用命令
| 序列 | 命令 | 作用 | 例子 |
| --- | --- | --- | --- | 
| 1   | `git init`| 托管 |
| 2   | `git add` | 添加到暂存区 |
| 3   | `git commit`| 添加到版本库 |
| 4   | `git status`| 察看 |
| 5   | `git diff`  |  对比 |
| 6   | `git log`   | 查看历史版本 |
| 7   | `git reset --hard (版本号) ``HEAD`|回到某版本 |
| 8   | `git reflog`| 查看版本编号 |
| 9   | `git checkout -- file `| 撤销工作区 |
| 10  | `git rest HEAD file`|撤销暂存区 |
| 11  | `git remote add origin git@github.com:youname/lerarngit.git`| 添加远程仓库 |
| 12  | `git push -u origin master ` | 推送所有内容 |
|  13 | `git push oringin master` | 推送 |
| 14  | `git clone` |    克隆 |
| 15  | `git  checkout -b` | 创建并切换分支 |
|  16 | `git branch`<name> |  创建分支 |
|  17 |  `git checkout <name> ` | 切换分支  |
| 18  | `git merge <name> ` | 合并某分支到当前分支 |
| 19  | `git branch -d  <name>` | 删除分支 |
| 20  | `git  tag `            |      打标签           | 
| 21  | `git stash`          |    隐藏工作区      |
| 22  | `git stash pop `  | 回到工作现场     |
| 23  | `git push 本地分支：远程分支`     |  本地分支必须存在 |
| 24  |` git checkout <file name> `           |  从远程库下载文件，（本地文件已删除的情况下）|
| 25 | `git config --global color.ui true`   | 配置git，使其显示颜色 |
| 26 |`git config --global alias.缩写  命令名字 ` | 这样可以为命令配置自己想要的缩写  |


- Git 是什么？
Git 是一款分布式的版本管理软件，适合管理二进制文件，就是适合 代码 文档什么之类。
- 为什么要学Git？
这么酷版本管理软件，干嘛不学？
- 写一个 Git 自动忽略仓库
因为有很多文件会产出垃圾文件，你 `git status` 时看到会很讨厌，git提供了解决方案，创建一个
`.gitignore`文件，在https://github.com/github/gitignore浏览配置文件。

## 版本回退
## 工作区 、暂存区
![](http://www.liaoxuefeng.com/files/attachments/001384907702917346729e9afbf4127b6dfbae9207af016000/0)
## 远程库 GitHub
- 2008年出现了GITHub，这使开源或这社会化编程变得更加容易。
可以在GitHub上面fork自己感兴趣的开源项目，或这大神。
也可以把自己的开源项目托管在GitHub上。

## 分支
` branch ` 分支是git里边的一大特色。
可以通过分支的特性保证原来的版本继续运行，和新想法的继续开发。
`git branch` 查看分支
`git checkout  <name>`切换分支
`git checkout -b <name>`  和合计：创建并切换分支
`git merge <name>` 合并某分支到当前分支
`git branch -d <name>` 和合计： 删除分支

## 解决冲突
通过手动的方式解决冲突。
或者······


 

## 结语
我是先使用GitHub才知道git版本管理的，
发现了这么好用的git管理仓库，
拖拖拉拉学了好久才会。
秉承 “ 教是最好的学 ” 概念，写的学习笔记，
不足之处，大家多多包涵。




## 参考资料
- [廖雪峰 - Git教程](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)
- Git的官方网址： http://git-scm.com
- [《GitHub 入门与实践》- 豆瓣](
https://book.douban.com/subject/26462816/)
## CHANGELOG
170215 创建
170622 添加背景  参考资料
170701 添加缩写设置

**Comment by Merly-61** [comment]
赞！

**Comment by iamzhuoxuan** [comment]
@xiewuqi 速度好快，完成得非常完整，文档写作习惯也非常好 👍 👍    看来是有备而来呀 ^_^

**Comment by simpleowen** [comment]
@xiewuqi 喔，大可好快，不要停，继续探索

**Comment by Lknj** [comment]
学到了，赞

**Comment by scottming** [comment]
很棒，笨办法分成组块的形式很不错，可以思考下，git 的常用命令是否也可以按组块分类呢？或者用一条线串起来？

**Comment by xiewuqi** [comment]
@ssscaptain @iamzhuoxuan @simpleowen @Lknj @scottming 谢谢大家，自己本来想报3期Py班。可是一直拖拖拉拉到现在，现在找个一个销售业务，时间很不固定，不知道有没有时间学习。不过，既然来了，目标只有一个，掌握它。共勉!

**Comment by Hugo1030** [comment]
@xiewuqi 一起加油，完成比完美重要！

**Comment by Wangjunyu** [comment]
@xiewuqi  可以做的更好，推荐尝试个小任务：
* 之前的几个看起来简单的小练习只是在跟着教程写练习，可以尝试自己设定一个场景，自己用代码实现自己的想法。
