### ISSUE TITLE
Ramsey完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by draachen** [AIHackers/PythonStartUp#14]
Title：
**LPTHW exercise address:  https://github.com/draachen/LPTHW.git**

进行入学任务时最意外的收获：
1. 目前学到ex48，课本提供单元测试程序，需要自己编写扫描器，当自己独自完成这一任务的时候，感觉很有成就感；
2. 用的中文版教程有的程序会把字典的大括号写成中括号，刚开始没有意识到，跑程序的时候会报错，然后上网搜索，发现有很多小伙伴其实也遇到过和我一样的问题，就感觉不孤单，此外，stackflow或者zhihu上也有某些问题的解答，感觉这个圈子大家还是蛮互帮互助的；

**Comment by CrickeySong** [comment]
已经练到第 48 个小练习了，好快的速度！

**Comment by liangpeili** [comment]
手动点赞，另外是stackoverflow哦
