### ISSUE TITLE
小康完成py104的任务啦！

### ISSUE THREAD

**Issue by Lknj** [AIHackers/PythonStartUp#141]
# 《笨办法学python》小结
[作业在这里](http://www.github.com/Lknj/py_practice)
## 回顾以前的学习时光
我接触python已经有一年的时间了，《本办法学python》这本书的基础知识现在看的是第三遍，确实有一种茅塞顿开的感觉。
## 回顾练习过程
- 总的来说，在学习if语句，循环和列表，字典等知识点的时候挺顺畅的，到了def函数也还好，学习类和对象的时候遇到了困难
- 以**文字游戏**为例，刚接触感觉太复杂了，一环套一环，一环出现问题就good game，感觉就是一个字，乱，以前都是报错了，根据报错一点一点完善，直到最后运行成功，然后发现这样完全没有自己的思路。
- 然后自己先画了**流程图**，再把骨架拼接起来，然后再完善内容，自己思路就很清晰，类跟def函数的基本功能也可以很好的学习,这些也可以运用到以后的学习中不是吗，永远要有自己的思路！
- 当然，代码 字符输入错误的情况还是很多,解决问题的如下：
>* 倒着读代码
>* 看错误提示，找出问题所在
>* 可以把出问题的一行注释掉（看情况），再运行看看是不是没有其他问题了
>* 当你思路不清晰的时候去听听音乐吧^_<
## 学习经验
>* 我之前也是学python2.x学了一段时间，所以如果有跟我一样不愿卸载放弃python2.x的同学，可以看一下2.x跟3.x两个版本的[共存问题](http://blog.csdn.net/cjl0356/article/details/51035646),其中包括了pip的使用方法。
>* 至于那个SSH连接github仓库，我只是用Git命令配置了SSH key，同步到个人Github公开仓库是用的GitHub Desktop,这是[配置SSH key的方法](http://blog.csdn.net/binyao02123202/article/details/20130891)
>* 说了pip，该说需要用pip安装的模块了，这里说明一下，有个别模块是只适用于2.x的某一版本的，爬虫，写小游戏都是需要安装模块的，认为用pip安装最简捷了。
>* 周围的程序员告诉我，先看一些简单的项目，试试能看懂吗，然后再去深入学习某一点，这种方法不是每个人都适用，会头大的,首先你对的基础很有自信才行
>* 正则表达式很强大，怎么也要了解一下
## 目前遇到2.x跟3.x的区别： 
>* python3.x的print函数，print后有括号print("...")
>* python3.x只有input()函数，没有raw_input()函数，2.x中raw_input()函数接收字符串类型，返回字符串,input()只接收数字类型，返回数字（int，float）

## 参考资料
>* [Git教程-廖雪峰的官方网站](https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/)

**Comment by Wangjunyu** [comment]
恭喜完成入学任务～ 
不要停下探索的脚步，尝试再做点什么吧。

**Comment by Lknj** [comment]
我用Git命令行建库，配置SSH Key，上传文件的笔记[在这里](https://github.com/Lknj/py_practice/blob/master/git.md)
