### ISSUE TITLE
黄老邪完成py104入学挑战啦

### ISSUE THREAD

**Issue by Leon-Huang** [AIHackers/PythonStartUp#142]
地址：https://github.com/Leon-Huang/Learn-Python-the-hard-way

# 总结
由于之前断断续续学过一段时间的Python，但仅限于最基本的内容
到了class阶段就没有再继续深入下去了，这次的练习作业也是
前面的内容，list，string，function等内容基本上没有太大的难度，直接pass过去
但到了class开始产生中断了......

# before
之前自学一段时间的Python，还装模作样下了几本电子书来看，但无一例外，不知道是天注定还是其他的原因，每次到了class的阶段，必定停止，然后过了N个月，又重新捡起书来，但激情已不再了。所以现在的水平也就是简单的能用if/else，函数等的入门水平

# 本次练习

这次抽空刷了前面的题目，把代码放上来，中间由于有一些基础，倒是没有碰到什么问题。Q39 涉及到了dict，里面倒是有一些内容模糊了，有时候都忘了一些基本的方法了，看到一些似曾相识的东西，先猜，再测试，才捡回了一些知识。比如，遍历字典，用 for i,j in dict.items()，如果还是以list的方法就报错...... 这次准备硬着头皮把class的内容啃下来  

# Next

GitHub不会用，只会在网页上傻不拉几的吧代码传到仓库里，相关概念完全不理解，现在Github对我来说充其量就是一个云端的网盘，完全没有发挥它强大的功能。下载了《Github入门与实践》这本书，准备开始系统化学习一下Git的使用方法

# others
之前还接触过一些小case，比如用beautifulSoup来爬豆瓣的页面啥的 应该丢在我自己另一个叫exercise的仓库里了

# 期待
希望经过3个月的学习后，自己能够独立完成一个和微信交互的程序的开发

**Comment by iamzhuoxuan** [comment]
> 每次到了 class 的阶段，必定停止，然后过了 N 个月，又重新捡起书来，但激情已不再了。这次准备硬着头皮把 class 的内容啃下来。

@Leon-Huang  正好趁开学前这段时间多琢磨琢磨 ^^ 有兴趣的话可以继续探索一下 git 

> 希望经过 3 个月的学习后，自己能够独立完成一个和微信交互的程序的开发

加油，期待到时候看到你的作品！

**Comment by Leon-Huang** [comment]
# Git & GitHub

## What's Git & Github
简单说来Git是一种版本控制系统，Github是在Git的基础上构建的一套平台

为什么需要版本控制系统？
大规模开发的时候，会涉及到多人配合，一个优良的版本控制系统能够让每个人各司其职，发挥团队的优势

## 如何使用Git
注册账户 --> 电脑上安装Git客户端 --> 设置SSH key --> 验证登录

## 基本概念
1. 仓库（Repository）：仓库就是用来存储所有代码的地方啦，可以把一个仓库想象成一个文件夹
2. 分支（Branch）：软件开发的过程中，会有不同的分支，最主要的是主分支（Master），剩下的根据需要自由创建，如下一个版本要开发新特性，可以增加一个Feature-xxx分支，如果是以修复bug为主，则可以开辟一个bug-xxx分支。
3. 合并（Merge）：想象一下交通，Master分支就是我们的主干道，其他分支就是支道或者辅路，最后所有的支道或者辅路都需要汇总到主干道来，这个汇集的过程就叫合并。开发中也是一样，bug修复完了或新特性开发完毕，合并入主版本，再统一向外发布。

### 仓库的操作
1. 在本地创建一个文件夹，如 /usr/leon/python，将该文件夹初始化为Git的仓库
```
cd /usr/leon/python
git init
```
初始化完毕后，Git会实时监视仓库里所有文件的变化

2. 我们一般从某个分支开始干活儿，首先需要把存在GitHub上面的代码copy到本地
```
git pull <URL> <BRANCH>
```
URL是远程主机名
Branch是你要获取的分支名称，如bug-xxx，或feature-xxx等

一般仓库初始化后只有一个Master分支
```
git checkout bug-xxx
```
切换到down下来的分支

3. 开始愉（痛）快（苦）地码代码了
下班了，今天的内容先保存一下
```
git add <Your files>
git commit -m "DESCRIPTION"
```
git add <代码文件> 用于把这些文件放在一个缓存区内
git commit -m "blablabla" 用于把这些文件正式提交进入版本

4. 好了，这个bug终于修复完了
测试通过后，需要把手头上这个bug-xxx分支上传到GitHub上面去
```
git push <URL> <Local_Branch> <Remote_Branch>
```

也可以在本地先Merge到Master再上传，视情况而定
不过我这样的菜逼一般都只能push，没有权限merge的
```
git checkout master
git merge --no-ff bug-xxx
```
第一条命令切换回主分支
第二条命令执行快速合并

5. 这个任务完成了，继续去pull下一个branch吧

**Comment by gzMichael** [comment]
很棒的探索！
@Leon-Huang 可以在课程前多尝试一下 git 的使用，课程开始后会经常用到的
