### ISSUE TITLE
陈晨完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by evanchan92** [AIHackers/PythonStartUp#143]
[完全版总结在这](https://github.com/evanchan92/learnpython/blob/master/Python%E8%AF%BE%E5%89%8D%E5%87%86%E5%A4%87%E5%BF%83%E5%BE%97.md)

[LPTHW作业在这](https://github.com/evanchan92/git_terminal)

Markdown和Git部分持续学习中...

学习心得：
如何学好？
模仿 模仿 模仿：学习编程就像学习一门新的语言一样，孩子学习语言的方法只能是模仿嘴巴的动作，不断发声，不断根据外界反映校正，而不是扔给孩子一本语法书，“你照着学吧。”
犯错 犯错 犯错：依然是学习语言的隐喻，小朋友一遍一遍学舌，比如终于说对“爸爸”之后，全家人的兴奋会给到ta一个正面激励，没说对就没有这个激励。所以多犯错，就能了解到知识的边界。

**Comment by scottming** [comment]
学习心得很不错，的确是这样的过程。另外如何模仿的更有效呢？就是要确认你真的搞懂了，所以编程初期，建议多写注释，注释方法见 LearnPythontheHardWay。
