### ISSUE TITLE
入学挑战中你遇到了哪些优秀实践？欢迎在此分享~

### ISSUE THREAD

**Issue by sunnyhuang42** [AIHackers/PythonStartUp#145]
入学挑战中你肯定会遇到不少叫你眼前一亮的优秀实践，欢迎随时在此分享，表达你的赞美肯定，也让更多同学了解学习 😄 

分享时最好给出 GitHub Username 、相应链接及让你眼前一亮的原因哟~

**Comment by sunnyhuang42** [comment]
我先来一个：

@Vwan 在 [Vwan 提交Py104入学挑战任务 · Issue #144 · AIHackers/PythonStartUp](https://github.com/AIHackers/PythonStartUp/issues/144#issuecomment-318287198) 给出了
 [Py104/学习小结.md at master · Vwan/Py104](https://github.com/Vwan/Py104/blob/master/%E5%AD%A6%E4%B9%A0%E5%B0%8F%E7%BB%93.md) 让我觉得眼前一亮，亮点有三：

1. 在小结里分享了根据个人情况给挑战加码、增加学习动力的好方法：

	> 对于基础更好些的同学，做前面的练习可能更觉得没多大挑战性，为避免“不屑”情绪，突然想到一个方法，既可以从头到尾做下来，还可以多带动点脑子，我自己试验了ex33，觉得还挺有趣的。
	
	> 方法就是：看着书中每章的“你应该看到的结果”部分，倒推出代码（需要用到该章的知识点），而不是看着代码一个一个的敲出来。然后再跟作者的源代码作比较。
	
	> 比如 ex33, 我看着运行结果倒推出来的代码是：……

2. 不仅分享了方法，还记录了实践过程，给出了细节正确的示范——这是好教程的关键呐~ BTW， 何为细节正确？见 [如何建立好的学习习惯系统？ - 阳志平的网志](http://www.yangzhiping.com/psy/EstablishLearningSystem.html)

3. 把探索过程和心得这类成果型的内容记录在了 MarkDown 文档里，在 Issue 里给出文档链接，而不只是把全文贴在 Issue 里。这样成果更方便自己未来调用、修订增补，也更符合 GitHub 里 code/wiki 放成果，用 issue 驱动成果完善的使用逻辑。



	BTW，给 @Vwan  一个小建议：如果文档命名是英文就更好啦，这样地址就会清爽些，不会出现 https://github.com/Vwan/Py104/blob/master/%E5%AD%A6%E4%B9%A0%E5%B0%8F%E7%BB%93.md 这样的乱码了~

**Comment by Hugo1030** [comment]
@Bruce-Qiao 
在[绿茶完成py104入学挑战啦 #146](https://github.com/AIHackers/PythonStartUp/issues/146)有两点非常值得我学习：
1. 在做第48个练习时，第一遍用较多的代码行数完成了习题任务，可是并没有满足。在第二遍尝试的时候，深入研究tuple概念，将代码压缩到35行，比作者还要少两行。这种探索和钻研精神值得学习。

2. 第二遍复习时，将《笨办法学Python》代码用Python3重新输入一次，既提高了学习难度，又巩固了语法细节，是非常好的方法，值得学习！

BTW:给 @Bruce-Qiao 一个建议，我觉得你现在基础已经很好了，除了熟悉Python语法之外，1. 能不能利用Python，创作一些有趣的东西? 2. 以前用Ruby实现的某些功能，能不能改为Python来实现？

**Comment by ghost** [comment]
@ishanshan 多谢！文件名已改:-)

**Comment by justin007755** [comment]
做第二遍的时候，建议把书合上，尽量凭记忆写出来。
