### ISSUE TITLE
绿茶完成py104入学挑战啦

### ISSUE THREAD

**Issue by Bruce-Qiao** [AIHackers/PythonStartUp#146]
作业地址：https://github.com/Bruce-Qiao/lpthw

## 背景

早就听说Python语言在数据处理以及人工智能方面应用很广泛，因为自己目前主要从事投资方面的工作，希望通过学习python提高数据收集和分析能力，进而成为一名quant；同时也希望将来能够学习人工智能方面的内容，所以早早就报了名。

最早在大学期间自学过C语言并且独立完成过小型程序项目，后来工作后没有机会用基本上忘光了。在这次学习前学习了ruby on rails，所以算是有点基础。

## 学习过程

在网上报名后，马上按照课程预习要求开始做练习。由于之前有一定基础，加上为了赶进度，很快就完成了第一遍练习。在等待开课的过程中为了加深、巩固学习内容又用python3重新做了一遍练习，第二遍明显感到有较大进步，对于很多概念、方法的理解更加深入了。本来计划在开课前做第三遍，因为下周要出去旅游，估计无法完成了。

## 问题及解决方案

在做lpthw第48个练习（lexicon.py）第一遍时，作者说他的程序只有37行，而我怎么也压缩不到这个数字：

    def scan(s):
    
        list = s.split()
    
        first_word = ('verb', 'go')
        second_word = ('direction', 'north')
        third_word = ('direction', 'south')
        fourth_word = ('direction', 'east')
        fifth_word = ('verb', 'kill')
        sixth_word = ('verb', 'eat')
        seventh_word = ('noun', 'bear')
        eighth_word = ('noun', 'princess')
        ninth_word = ('number', 1234)
        tenth_word = ('number', 3)
        eleventh_word = ('number', 91234)
        twelfth_word = ('error', 'ASDFADFASDF')
        thirteenth_word = ('error', 'IAS')
        fourteenth_word = ('stop', 'the')
        fifteenth_word = ('stop', 'in')
        sixteenth_word = ('stop', 'of')
        sentence = [first_word, second_word, third_word, fourth_word, fifth_word, sixth_word, seventh_word,
                    eighth_word, ninth_word, tenth_word, eleventh_word, twelfth_word, thirteenth_word,
                    fourteenth_word, fifteenth_word, sixteenth_word]
    
        result = []
    
        for item in list:
    
            for word in sentence:
                if convert_number(item) == word[1]:
                    result.append(word)
    
        return result
    
    def convert_number(string):
        try:
            return int(string)
        except ValueError:
            return string

在做第二遍的时候，仔细学习了tuple的概念，做出了只有35行的版本并且顺利实现了相应功能：

    tuples = [('direction', 'north'),
            ('direction', 'south'),
            ('direction', 'east'),
            ('direction', 'west'),
            ('verb', 'go'),
            ('verb', 'kill'),
            ('verb', 'eat'),
            ('stop', 'the'),
            ('stop', 'in'),
            ('stop', 'of'),
            ('noun', 'bear'),
            ('noun', 'princess'),
            ('number', 1234),
            ('number', 3),
            ('number', 91234),
            ('error', 'asdfadfasdf'),
            ('error', 'ias')]
    
    def convert_number(s):
        try:
            return int(s)
        except ValueError:
            return s.lower()
    
    def scan(sentence):
        words = sentence.split()
        result = []
    
        for word in words:
    
            for tuple in tuples:
                if convert_number(word) == tuple[1]:
                    result.append(tuple)
    
        return result

## 学习体会

1. 学习语言需要大量的重复。一是最开始可能有些问题搞不懂，多做几次就懂了；二是重复练习可以提高熟练度，形成常用套路，这可能也是熟练程序员和初学者的主要区别：虽然都能得到结果，但前者的速度比后者快很多。
2. 要有明确目的的学习。Lpthw我虽然练了两遍，但一、两周不练就感觉生疏了。如果学的东西平时的工作中不常用，只是做练习，很快就会忘记。希望参加这个课程能够使我把所学用到日常的工作、学习中。
3. 要勇于并善于查阅文档。虽然自己的英语水平还算说的过去，但是面对长篇的技术文档还是很难硬着头皮看下去，所以我说首先要勇于查阅文档。要想成为合格的程序员，这关必须得过。

**Comment by Hugo1030** [comment]
第二遍时用python3重新做一遍，这个做法非常好，不仅提高了难度，同时熟悉了Python3的语法细节。向你学习，我也想这样做一遍。 @Bruce-Qiao

**Comment by Bruce-Qiao** [comment]
@Hugo1030 在学习上个语言时，有的同学入学前练习做了七八遍，事实证明这些同学后来学的都非常好。
一起加油吧！
