### ISSUE TITLE
刘纪元完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by elevenera** [AIHackers/PythonStartUp#148]
## Py104入学挑战
- [代码仓库](https://github.com/elevenera/python.learn)
- [练习过程回顾及复盘完整版](https://github.com/elevenera/python.learn/issues/1)
- [Py学习笔记](https://github.com/elevenera/python.learn/issues/2)
- [Git基本操作](https://github.com/elevenera/python.learn/issues/3)

## Py练习小结
- 说明：这是练习和复盘过程的summary，完整版的练习过程回顾和复盘解题过程，请戳上面的：[练习过程回顾及复盘完整版](https://github.com/elevenera/python.learn/issues/1)。

### 背景
- 我前段时间辞职，作为一个小白开始自学《Learn Python the Hard Way》，每天投入3～4h，完成了书中的练习及练习思考。
- 后续不打算马上工作，给自己半年时间，继续深度学习。然后职业转型，希望成为一个创造者、成为“黑客”。

### 整体回顾
- 整体练习比较顺畅，难度属于循序渐进型。个人觉得推荐这本《Learn Python the Hard Way》给编程新手是非常好的入门书籍。
1. 本书的结构设计非常符合“必要难度”理论，不是一上来就讲复杂的理论知识吓倒一片，而是先从简单的模仿输出开始，完成每一个习题，遵循“刻意练习”理论。
2. 随着难度逐渐增加，让学习者像游戏过关一样，“必要难度”满足了人们对挑战性的需求。感受到学习python的乐趣和成就感。

#### 遇到的困难?
- 感觉一个人编程的时候，有时效率不高。可能是因为一个人学习python，没有“同侪压力”。
- 遇到困难时，没有同伴可以讨论和互助，比较孤独。

#### 想到的解决办法?
   - 改用“执行意图”，来为自己做学习计划。按着愿望、障碍、目标、计划“woop思维模式”执行。
   - 之前会用网络大搜索、查看官方文档、请教工程师朋友等方法解决。后续会参加开智py104编程课程，以输出为导向，与优秀的人一起学习。

### 回顾我的心流体验
- 次数回忆不清楚了，大多数情况是“必要难度”，匹配自身阶段，同时有一定挑战性。且在环境安全、放松的情况下，我会更容易进入心流。
- 为了容易进入心流，我会提前关好门、打开我喜欢的音乐，戴上耳机免打扰，更容易全身心投入到编程里，尽量保持大时间段的刻意练习。

**Comment by Hugo1030** [comment]
@elevenera 很棒！「专注」和「必要难度」是进入心流的好方法。
