### ISSUE TITLE
SSH Key生成后与Github不能建立连接

### ISSUE THREAD

**Issue by Jessica8729** [AIHackers/PythonStartUp#149]
我的系统、版本等环境配置是：macOS Sierra 10.12.
问题描述：
步骤一：SSH Key生成：
_**The following SSH key was added to the Jessica8729/ssh repository by Jessica8729:
Key
64:6a:bb:b5:06:d6:dc:39:52:6d:63:2d:e2:c7:82:1b**_
步骤二：与github建立连接却不允许，如下：
**JessicadeMacBook:temp jessicaliu$ cd ~/.ssh
JessicadeMacBook:.ssh jessicaliu$ ssh -T git@github.com
Permission denied (publickey).**
问题：是key的公有私有设置错了吗？
解决方案：查Github help，提示，如果是macOS Sierra 10.12.2 or later, 需要modify  ~/.ssh/config file to automatically load keys into the ssh-agent.
但是，这一步卡住，不知如何改了？
输入Host *，结果如下：
**JessicadeMacBook:.ssh jessicaliu$ Host *
known_hosts.DHCP has address 202.98.24.125
known_hosts.DHCP has address 202.98.24.125
Host known_hosts.DHCP not found: 3(NXDOMAIN)
Host known_hosts.DHCP not found: 3(NXDOMAIN)**
也不是手册的提示结果。
请教了。
谢谢！

**Comment by wangluzhou** [comment]
我之前用mac搭建gitpage的静态博客的时候也遇到过这个情况，我记得是要将这个ssh的名称添加一下，类似于一个安全名单一样。命令如下：
```
ssh-add <你的ssh名称>
```
试试？

**Comment by Jessica8729** [comment]
谢谢 @wangluzhou ，按您的提示，终于搞定。
错误原因：自作聪明自建了个SSH文件夹，所以生成的KEY配对都存在这，而不是安装后默认的文件夹。
做法：
1. 查看.ssh存放路径并打开
_$ open ~/.ssh_
2. 将KEY对移制于此(copy and paste)；
3.复制SSH key到GitHub account
_$ pbcopy < ~/.ssh/id_rsa.pub_
4....
5. 建立连接
_$ ssh -T git@github.com_
6. 成功
_Hi Jessica8729! You've successfully authenticated_

**Comment by Jessica8729** [comment]
谢谢 @wangluzhou ，按您的提示，终于搞定。
错误原因：自作聪明建了个SSH文件夹，所以生成的KEY对都存在这，而不是默认文件夹。
做法：

1. 查看.ssh存放路径并打开
$ open ~/.ssh
2. 将KEY对移制于此(copy and paste)；
3. 添加SSH private key to the ssh-agent
$ ssh-add -K ~/.ssh/iamkey
Identity added: /Users/jessicaliu/.ssh/iamkey (/Users/jessicaliu/.ssh/iamkey)
4. 复制SSH key到GitHub account
$ pbcopy < ~/.ssh/id_rsa.pub
5. ....
6. 建立连接
$ ssh -T git@github.com
7. 成功
Hi Jessica8729! You've successfully authenticated
