### ISSUE TITLE
[王玮楠]完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by MountainDoor** [AIHackers/PythonStartUp#15]
[Python作业](https://github.com/MountainDoor/LearnPythontheHardWayex)

**Comment by CrickeySong** [comment]
能更新一下头像就更好啦，尽量各平台统一哟 ;-)

**Comment by MountainDoor** [comment]
请问除了GitHub我们还会使用哪些平台呢？

**Comment by sunnyhuang42** [comment]
@MountainDoor  课程用到的还有开智学堂 App 哦。正式开课前会邮件告知大家：）

**Comment by liangpeili** [comment]
ex17.py 第15行应该是“continue”  ：）
