### ISSUE TITLE
入学任务常见问题指南

### ISSUE THREAD

**Issue by iamzhuoxuan** [AIHackers/PythonStartUp#150]
Hi, Py104 小伙伴

入学任务已持续几天，你是否已顺利安装相关软件、上手练习 [《笨办法学 Python》](https://book.douban.com/subject/26264642/) ？

此 Issue 将持续汇总入学任务的常见问题，方便学友们查阅／参考。

## 目录

1. 担心完不成 40 个小练习怎么办？我可以不做附加练习吗？
2. 遇到问题卡了很久怎么办？完成一个小练习要做 1 天怎么办？
3. Python 到现在还没有安装成功怎么办？
4. 我在 GitHub 上卡了很久？我不会用 Git 命令上传文档怎么办？
5. 如何及时获取课程仓库变动，了解学友完成情况，与学友互相交流？
6. [如何提交任务成果到 GitHub 仓库？](https://github.com/AIHackers/PythonStartUp/issues/150#issuecomment-319345610)

详细请查看此 Issue 后续 Comment. 

## PS

1. 还未提交入学任务的学友，请花 1-10 分钟填写一下《入学任务反馈表》，告知当前完成情况、所遇困难，方便课程组知悉并提供相应帮助：http://openmind.mikecrm.com/goGYIIw
2. 无论如何，请一定在截止日期 8 月 4 日 11:42 前提交任务成果；越早提交，越早收到后续通知。
3. **完成 21 个小练习及其附加练习后，即可在课程仓库发布 Issue「 ? 完成 py104 入学挑战啦」。**

附时间线：

7-29 7-30 7-31 8-1 8-2 8-3 8-4
--↑------------ ↑ ----------↑
.今天........最后 3 天....截止提交！

今天是周末，大家抓紧时间，加快练习步伐哦〜期待和你相遇 ；）

**Comment by iamzhuoxuan** [comment]
## 1. 担心完不成 40 个小练习怎么办？我可以不做附加练习吗？

完成复杂任务的最佳打开方式：降低问题复杂度，一步一步来。

小提示：未完成附加练习（study drills）不影响你完成下一个小练习。

因此，入学任务可以拆解为：

Step 1. 完成前 21 个小练习
Step 2. 完成前 21 个小练习及附加练习
Step 3. 完成前 40 个小练习
Step 4. 完成前 40 个小练习及附加练习

建议你按照这样的次序进行练习。先完成 1 轮，再回头做附加练习，更有助于加深自己对知识的理解。

注意优先保证有质量地完成前 21 个小练习，无需过份在意练习数量。在完成 21 个小练习及其附加练习的基础上，仍有时间，再继续往前练习。

当你完成 21 个小练习及其附加练习后，即可在课程仓库发布 Issue「** 完成 py104 入学挑战啦」。

## 2. 遇到问题卡了很久怎么办？完成一个小练习要做 1 天怎么办？

Keep calm and take a breath.

保持冷静，深呼吸一口气。

[编程思维 Python 基础班四期入学挑战 · Issue #138 · AIHackers/PythonStartUp](https://github.com/AIHackers/PythonStartUp/issues/138) 中描述的 15-30 mins ，是针对有一定编程基础的同学／功底较好的同学。

若你需要理解小练习中相应的知识点，对完全的编程小白来说，单个小练习花费时间超过 30 mins 也比较正常，尤其是第 17 个小练习之后。

但如果某个问题，你折腾超过 2 个小时（甚至 1 整天）仍不能解决，**建议你立即发 Issue 提问**，热情的学友、教练将会为你解答。

发 Issue 提问时请提供相应截图、其它相关信息，方便他人快速定位问题，更好为你解答。

## 3. Python 到现在还没有安装成功怎么办？

请直接联系一休。

## 4. 我在 GitHub 上卡了很久？我不会用 Git 命令上传文档怎么办？

GitHub 并非入学任务考察的核心，只要你能使用网页版提交任务成果即可。

建议你目前专注完成 [《笨办法学 Python》](https://book.douban.com/subject/26264642/) 中的小练习，无需在 使用 GitHub、使用 Git 命令上耗费过多精力。学有余力，再探索 GitHub 与 Git 命令的使用。

## 5. 如何及时获取课程仓库变动，了解学友完成情况，与学友互相交流？

你可以使用邮箱接收课程仓库最新变动，及时了解其他学友动态，与其他学友相互交流。

**设置方法：**

Step 1. 在 GitHub 个人设置中，增加关联的邮箱账号。

![image](https://user-images.githubusercontent.com/24438878/28744385-5d0e6b52-7492-11e7-9254-4bdcf45c147c.png)

Step 2. 设置默认接收提醒邮箱

如图中数字 2 所示位置，在方框内选择你希望接收提醒的邮箱。

![image](https://user-images.githubusercontent.com/24438878/28744391-67e7a2f0-7492-11e7-8d21-4380fdbca538.png)

Step 3. 关注 (watching) 课程 GitHub 仓库。

![image](https://user-images.githubusercontent.com/24438878/28744394-707a2dd4-7492-11e7-9a0f-24591ffec64e.png)

Step 4. 在手机端接收相应提醒。

每天大家最常使用的是手机，如何在手机端收取邮件提醒呢？

方法一：在微信中设置 QQ 邮件提醒（需将步骤二的邮箱设置为 QQ 邮箱）。

方法二：使用邮箱提供商相应的移动端，如网易的邮箱大师

方法三：使用不同手机系统内置的邮箱功能，并开启相应提醒功能。

---

大家还有其它问题，欢迎在此仓库中发布 Issue 提问／填写[《入学任务反馈表》](http://openmind.mikecrm.com/goGYIIw)／联系一休。

**Comment by iamzhuoxuan** [comment]
## 6. 如何提交任务成果到 GitHub 仓库？

GitHub 是一个优雅的版本管理工具，开智学堂常用 GitHub 作为课程主题讨论、提交&互评作业平台。你可以通过网页端、客户端、Git 命令行将文件提交到 GitHub 仓库。

具体使用方式可参考：[如何使用 GitHub 提交 任务成果 & 笔记](https://github.com/OpenMindClub/Share/wiki/HbAssignmentHandUpAndReview#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4-%E4%BB%BB%E5%8A%A1%E6%88%90%E6%9E%9C%E7%AC%94%E8%AE%B0)

**Comment by zhiyu1999** [comment]
Kamino closed and cloned this issue to [zhiyu1999/PythonStartUp](https://github.com/zhiyu1999/PythonStartUp/issues/2)
