### ISSUE TITLE
李广鹤liguanghe(lgh) 完成入学任务啦.

### ISSUE THREAD

**Issue by liguanghe** [AIHackers/PythonStartUp#152]
- [x] LPTHW:
 
[test2/try at master · liguanghe/test2](https://github.com/liguanghe/test2/tree/master/try)

- [x] Experience:

 [test2/Practical experience.mdown at master · liguanghe/test2](https://github.com/liguanghe/test2/blob/master/doc/Practical%20experience.mdown)

- [x] Tutorial: 
[First Step to Git | Li Guanghe's blog](https://liguanghe.github.io/2017/07/30/HowtoGit/)
## timelog
- write tutorial 80 min
- Write Experience 10 min
- push LPTHW to remote repository 10 min

**Comment by scottming** [comment]
@liguanghe 写英文的方式很棒，特别是写英文注释。另外对于你作业里提到的几个问题：

> why a ()?

试着去思考一下函数的本质是什么？

关于类变的难了，这点很正常，因为抽象层级更高了。对于这类元知识，如果一个例子理解不了，试着换换参考下别的经典材料，如官方文档，Think Python，廖学峰教程等等，对比着去理解它，甚至可以深入思考一些问题，如：

* 类的好处到底有哪些？除了打包封装外？
* 什么时候该用类？什么时候用函数就可以了？
* ......

如这里就提到，类的好处不只是你说的打包，https://www.youtube.com/watch?v=o9pEzgHorH0&t=1281s

**Comment by liguanghe** [comment]
@scottming 谢谢,我去看下~
