### ISSUE TITLE
f-string的双引号问题

### ISSUE THREAD

**Issue by yyliuqu** [AIHackers/PythonStartUp#153]
1. 问题描述：
`  File "ex6.py", line 4  
    x = f"There are {types_of_people} types of people."     
                                                      ^
SyntaxError: invalid syntax`

2. 运行环境： OS， python3.6.1 terminal  
3. 操作：中英文双引号都试过，尝试 a) 先敲f-string里两个双引号，再填text，b) 左双引号+text+右双引号，c) 增加/减少空格，也但还是报错

**Comment by Hugo1030** [comment]
我直接复制这行代码，运行并没有语法错误。

要不你把整个代码发上来看看吧？

**Comment by polestar698** [comment]
@pulala8787 

我完全复制你的代码，赋值后运行，并没有报错
可能你的代码错误不在这一行，要不然截图展示一下所有代码？

![image](https://user-images.githubusercontent.com/30563775/28751919-32b9298c-7546-11e7-9afb-5311bdabf624.png)

![image](https://user-images.githubusercontent.com/30563775/28751924-3da43bca-7546-11e7-9cd3-80b3a4c1f8de.png)

**Comment by scottming** [comment]
排错记得多个角度去排。

**Comment by yyliuqu** [comment]
谢谢大家的回复。 @polestar698 
![code](https://user-images.githubusercontent.com/16816892/28752629-0469adfc-7557-11e7-8eb6-94a8c370cb14.png)

得到的结果是：
![error](https://user-images.githubusercontent.com/16816892/28752675-ac254f2e-7557-11e7-8c66-861cbfb9627c.png)


在后面几个练习里面只要出现f-string 的地方也报同样的错误。
我看了Shaw的练习视频，还没有找到错在哪里。。。

**Comment by polestar698** [comment]
@pulala8787 你前几个小练习的时候 print 没有出错？是不是因为 terminal 中默认运行的 python 是 python 2.x ， 你试试在命令行中输入： python3 ex5.py

**Comment by yyliuqu** [comment]
@polestar698 厉害了老铁 it works 👍  把默认路径改为python 3.6 没有报错了。

**Comment by polestar698** [comment]
@pulala8787 不客气，一起加油！

**Comment by scottming** [comment]
其实这个问题，是很显然的。
f 型打印，是 3.6 之后的 python 才支持，并且提示有语法错误，所以第一步就应该检查 python 版本，那么检查版本的命令是啥呢？除了检查版本还应该检查啥？有没有可能多版本共存？有合适的工具么？试着进一步探索下。
