### ISSUE TITLE
蓝兴建完成Py104入学挑战啦

### ISSUE THREAD

**Issue by lanxingjian** [AIHackers/PythonStartUp#157]
很高兴能参加这一期的学习~下面是我的作业地址

- [作业](https://github.com/lanxingjian/Learn-Python-the-Hard-Way)

- [练习小结](https://github.com/lanxingjian/Learn-Python-the-Hard-Way/blob/master/2017-07-30-summary-about-learning-python.md)

# 背景
从小是乖乖生，没有多少自己想法，一直跟着老师或者家长的路线过来，长大之后发现对自己却不是很了解，习惯性有人引导，却没有勇气去探索未知和不确定，迷茫和不知所措，很羡慕对自己了解并且从事自己喜欢项目的人。于是决定趁着现在，做一个探索者，去发现和探索那些有趣的事情和人，而Python就是当下的一个尝试。恰好有朋友推荐了“开智学堂”的微信公众号，就撞见了第四期的学习课程，欣喜加入学习

# 学习体验

- 作者Zew A.Shaw是个有趣的人

- 我喜欢这种一边学习一边练习的方式。

- 打字速度变快了

- 我是个比较随意的人，对待代码也是，所以在过程中出现好些细节错误：拼写错误，print的双引号漏掉一个，括号漏掉一边，def忘记冒号……等等，简直了，不得不说，这个锻炼了我的细心和耐心。（不然程序运行不出来。。）

- 课程的安排很好，难度逐渐递进，还不断鼓励我们前行，写作业的过程蛮享受的
# 学习建议
无它，坚持

**Comment by Hanxiaorong** [comment]
well done
