### ISSUE TITLE
王锦完成py104入学任务

### ISSUE THREAD

**Issue by woaipuppyball** [AIHackers/PythonStartUp#158]

**Comment by woaipuppyball** [comment]
作业https://github.com/woaipuppyball/Jane-learn-python-104.git

**Comment by woaipuppyball** [comment]
[woaipuppyball/Jane-learn-python-104: 作业  https://github.com/woaipuppyball/Jane-learn-python-104](url)

**Comment by woaipuppyball** [comment]
### 作业[https://github.com/woaipuppyball/Jane-learn-python-104.git](url)

**Comment by woaipuppyball** [comment]
https://github.com/woaipuppyball/Jane-learn-python-104.git

**Comment by iamzhuoxuan** [comment]
@woaipuppyball  是不是不小心 close 了 Issue ？可以 右下角 「Reopen and comment 」 就可以重新打开 Issue ：

![image](https://user-images.githubusercontent.com/24438878/28754489-a5213a78-7578-11e7-89d9-a76f9a7cd8d0.png)

这样，这个 Issue 就会重新出现在这个界面中：

![image](https://user-images.githubusercontent.com/24438878/28754481-821867fe-7578-11e7-8560-927ad1dbf482.png)

**Comment by woaipuppyball** [comment]
谢谢您的帮助，我都不太懂怎么弄，而且，我刚才只做到了21题，为什么有时候会显示打不开这个作业仓库的链接呢。另外，别人是怎么把链接的网址变成“”作业“的超级链接的呢

**Comment by iamzhuoxuan** [comment]
@woaipuppyball 不客气，一起加油；离任务截止时间还有几天，继续完善一下你的任务成果喔
print 的 「小猫喵喵」 很好玩 😄   是不是发现编程挺有意思的  ^^ 加油啦

**Comment by iamzhuoxuan** [comment]
@woaipuppyball 

> 为什么有时候会显示打不开这个作业仓库的链接呢。

可能只是网络问题，这个仓库是公开库，没有限制用户访问；或者你检查一下自己输入的网址是否正确；

> 别人是怎么把链接的网址变成 “” 作业 “的超级链接的呢

这个是使用 Markdown 语法来写的；
使用的语法格式是这样的：
`[要显示的字](链接)`

举个例子：

[入学任务仓库](https://github.com/AIHackers/PythonStartUp/issues)

![image](https://user-images.githubusercontent.com/24438878/28783230-44da4ad6-7642-11e7-8d53-6cafff0cd818.png)

你点击这个 comment 框右上角可以看到原始的 Markdown 格式文本，试试看？😄
