### ISSUE TITLE
雷云鹤完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by leiyunhe** [AIHackers/PythonStartUp#16]
[雷云鹤的Python预习作业](https://github.com/leiyunhe/Pre-test4OpenMindCLub)

**Comment by sunnyhuang42** [comment]
哇，做到了 40+，还阅读了推荐书目，并做了笔记， @leiyunhe   awesome!

**Comment by leiyunhe** [comment]
@ishanshan 预习笔记比较粗糙。不过想着还是放上来，权且作为自己的学习前测吧。

**Comment by xpgeng** [comment]
少年, 要不要更新个头像呐?

**Comment by liangpeili** [comment]
太厉害了，作业做到46+， 书也看完了。要不要再看看《编码》？

**Comment by leiyunhe** [comment]
@liangpeili 我看的有水分，因为有一些书以前看过。我也发现code的推荐指数非常高。上个月已经买了，还没开始看。希望能在课程结束时候看完吧。
