### ISSUE TITLE
西西莉亚完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by ceciliacheng** [AIHackers/PythonStartUp#162]
更新了作业了@gzMichael  [https://github.com/ceciliacheng/entrance-task](https://github.com/ceciliacheng/entrance-task)
更新作业@7:00am 8.1，只有习题9和11里面有ruby，我把ruby都删了，换成python的语法了。

从上次结业之后一直都有练习的，但是只可以完成教材里的练习，没法无中生有地创造出解决日常生活和工作中遇到的问题的程序。所以这次又报名参加课程。
目标：

1. 跟住全程，毕竟可以退回学费，不好意思，我这么肤浅；
2. 学会API、类、爬虫；
3. 写出一个帮助自己减轻工作量的小程序

**Comment by gzMichael** [comment]
确实把另一本书的放进去了
等你检查完，再打完成标记

**Comment by LexieLee** [comment]
@ceciliacheng 还没有更新你的学习小结呢，尽快喔～😝 看好你！
