### ISSUE TITLE
习题13 如何改变sys.argv（代码文件本身的路径）？

### ISSUE THREAD

**Issue by Gungh** [AIHackers/PythonStartUp#164]
我的环境是MacOS 10.12.6， 使用的IDE是jupyter。（我的工作是数据分析，有时会在Python里用pandas做些由于数据量太大Excel完成不了的工作，比如数据透视表等）
在做习题13和习题14的时候，遇到一个问题，argv传入的代码文件路径不是想要的结果，是一个叫：
'/Users/haogong/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py'

的文件，我打开看了，它里面的内容不是我当前编写的代码。
运行情况如下：

> In [12]:
> argv
> Out[12]:
> ['/Users/haogong/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py',
>  '-f',
>  '/Users/haogong/Library/Jupyter/runtime/kernel-bc319618-debc-49d2-9432-cc6463b7c93a.json']
> In [13]:
> from sys import argv
> script,first, second,third = argv
> print("The script is called:", script)
> print("Your first variable is:", first)
> print("Your second variable is:", second)
> print("Your third variable is:", third)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-13-5987774c3fa8> in <module>()
>       1 from sys import argv
> ----> 2 script,first, second,third = argv
>       3 print("The script is called:", script)
>       4 print("Your first variable is:", first)
>       5 print("Your second variable is:", second)
> 
> ValueError: not enough values to unpack (expected 4, got 3)

当然，我知道如果将第三个变量删掉的话，这段脚本能正常运行。然而这个问题并没有真正解决，而且在习题14页还会再遇到。
网上查了下，尝试使用os.chdir（“”）改变工作目录，但并不能解决问题。
麻烦大家帮我看看该如何解决，才能将argv的参数改为我当前这段代码的.py文件，感谢！

**Comment by thxiami** [comment]
@Gungh 
按照我的理解，这里的 argv 是在终端中（Windows下是cmd或Powershell都可以），使用 python 运行脚本文件时所带的参数，其位置是 python 之后输入的参数，以空格隔开。
例如下面的 argv 就是 ex13.py， 1st_argv， 2nd_argv， 3rd_argv：
```
PS C:\py\hard> python ex13.py 1st_argv 2nd_argv 3rd_argv
```
如果要完成本练习，有1个地方需要注意：

- 在终端中使用 python 运行脚本文件

你遇到的问题，关键就在于这点，Jupyter 是如何执行 python 代码的，和终端一样吗。 Jupyter 如何调用 Python 执行代的内部原理我不懂，不过根据以下部分

> In [12]:
> argv
> Out[12]:
> ['/Users/haogong/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py',
> '-f',
> '/Users/haogong/Library/Jupyter/runtime/kernel-bc319618-debc-49d2-9432-cc6463b7c93a.json']

我猜测的是在我们执行脚本文件的代码时, argv 已经由 Jupyter 提供。此时 argv 已经存在了，无法完成本练习。        

我完成本练习的方式如下：
使用 Powershell，进入 python 脚本文件 ex13.py 所在目录下后输入以下命令后运行脚本，结果如下

```
PS C:\py\hard> python ex13.py 1st_argv 2nd_argv 3rd_argv

The script is called: ex13.py
Your first variable is: 1st_argv
Your second variable is: 2nd_argv
Your third variable is: 3rd_argv
```
表述难免有不清楚的地方，不知是否解决了你的问题

**Comment by Gungh** [comment]
@thxiami   谢谢，你的理解是正确的，这个问题主要是由于我在编辑器里执行代码造成，目前已经按照和你一样的方法，在终端执行脚本文件，完成练习。再次谢谢~
