### ISSUE TITLE
【summerpenguin】完成Py103入学任务了

### ISSUE THREAD

**Issue by summerpenguin** [AIHackers/PythonStartUp#17]
[作业仓库链接](https://github.com/summerpenguin/learning-CS)

跟踪课程信息很久了，终于报到了，虽然自己工作生活都很忙，还是希望能有所收获~

题目是之前陆陆续续做的，虽然由于时间限制只完成了基本要求，但是作为基本零基础，能够慢慢摸索进入编程的世界，自我感觉很有成就感。在Issues里看到大家都提前预习了很多东西，觉得好羡慕啊，自己也会努力赶上课程进度。

**Comment by liangpeili** [comment]
能完成任务就很不错啦~加油
