### ISSUE TITLE
Nicole完成Py104入学挑战啦！

### ISSUE THREAD

**Issue by NicoleChen6** [AIHackers/PythonStartUp#177]
- LPTHW
[https://github.com/NicoleChen6/Nicole-Chen](https://github.com/NicoleChen6/Nicole-Chen)

- 练习感想

_背景_：文科+商科，使用的最高端的计量软件是EViews(┬＿┬)；毫无编程背景；刚来土澳开学，缺乏大块时间

_回顾这几天练习的最大的困难_：安装Python，使用终端命令，以及文本编辑器。

别笑，虽说LPTHW是本初阶入门书，但是我作为一名计算机office和ps，lr以外的内容完全不明白，书中对于ex0的描述，讲的太过简略。以至于我在最初的两天完成没有办法开始练习——没有办法在powershell里打开Python，（更早的问题是，为什么不直接用Python自己来编程？）无法理解工作目录的含义。

当然现在，我的确可以回答自己的问题。文本编辑器用来写脚本，terminal用来运行脚本，Python是脚本的语言。

_21个练习_：
我完全follow作者的思路，“不懂没有关系，先照着书中的代码来写，慢慢地就明白了”，因此联系完成的较为顺利，虽然许多语法的用法还无法灵活掌握，但是凭借着“变量替换”的思路，读懂代码是可以的。

_观学友有感_：
我来仓库一看，这么多小伙伴兢兢业业地完成了练习，还详尽撰写各种心得，说明大家的反思真的很到位。我看得非常激动，敬佩，在别的社区很难看到这么多（hen nan dong）的干货吧。“师友夹持，立志不远矣”。LPTHW看完后还是要再看一遍的！

**Comment by NicoleChen6** [comment]
[https://github.com/NicoleChen6/Nicole-Chen/find/master](https://github.com/NicoleChen6/Nicole-Chen/find/master)

之前的链接似乎找不到code？

**Comment by iamzhuoxuan** [comment]
@NicoleChen6 

![image](https://user-images.githubusercontent.com/24438878/28862661-6156bc9c-7798-11e7-83d5-8bc656f51f48.png)

你的 markdown 语法没写对哈哈，()里应该放你想要跳转的链接呢

比如这么写：

```
[Nicole-Chen 作业链接](https://github.com/NicoleChen6/Nicole-Chen)
```
