### ISSUE TITLE
 sunwenbo完成 Py104 入学挑战啦 

### ISSUE THREAD

**Issue by ghost** [AIHackers/PythonStartUp#178]
###  LPTHW练习代码地址
https://github.com/sunwenbo/learnpython/tree/master/开智学堂课程/课前练习

### 课前练习总结
- 我是在2017年3月开始学习Learn Python the Hard Way的。其中练习1-25我按逐字敲出了所有代码，后面的练习我并没有逐字敲代码，而是部分采用了复制粘贴的方式。

- 作者Zed Shaw强烈反对复制粘贴的方式，在做练习1-25时我对作者还怀有神圣的崇敬之情，完全按照他所说的去做。但做到后面的练习时，我觉得Zed的观点也并非全都不容置疑的，所以经过重新考虑后不再逐字敲代码。有几个练习中，Zed要求我们用comments的形式在每句代码前注明这句代码是做什么的，但实际上这些代码都是在做同样的事情，如果按照Shaw的要求，我们就得把同一句comments写很多遍，我看不出这样有什么收获。Zed很推崇“死记硬背”的学习方法，他要求我们把命令写在卡片上，然后将命令的含义写在卡片的另一面，然后让我们每天花一些时间来背诵卡片的含义。而我认为在使用中记忆是最好的方法，死记硬背耗时太久，效率太低。Zed要求我们逐字敲代码，也许是为了让我们体会到自己写代码可能遇到的问题，我认为最重要的问题自己在敲前25个练习的代码时已经遇到了。那就是你写每个练习程序时几乎都免不了要犯拼写错误或其他小错误，而因为这些小错误进行代码调试的过程也是一门必修课。如果一定要我逐字敲出所有练习的代码，我觉得自己可以比较容易做到，但我希望以最快的速度掌握这本书的全貌，因此后面的练习不再逐字敲代码了。也许我的这种做法是值得商榷的，不过我暂时认为自己的做法没有错。

- 刚开始学这本书的时候，看的是Learn Python the Hard Way，里面使用的是Python2，并且Zed在书里强烈建议大家不要用Python3。可是我学了十多个练习后，却听说这本书的Python3版本已经出来了。于是赶紧找来了Learn Python3 the Hard Way,重学了前面十多个练习。这样，我在机缘巧合之下对Python2和Python3都有所接触，倒是挺有意思的经历。

- Learn Python the Hard Way作为经典书籍，我认为最重要的是教给我们一种“程序员范”，比如告诉我们至少得懂得使用command line，才能让你多少像程序员一些；比如严厉地要求我们一定要逐字敲出代码，不要复制粘贴；比如告诉我们用Atom已经够了，不要总想着去用其他什么高级工具。这些都让人感觉到Zed有一种“程序员范”，而其他编程书籍往往只是在教语言本身，很少让人有这种被一个老程序员训斥的感觉。

- 全书的练习部分并不难，但附录中教Command line的部分比较难。Command line部分我一共学了两遍才掌握了大部分内容，第一遍的时候，跟着Zed实现了所有过程，但仍然似懂非懂，第二遍的时候才弄懂了大部分内容。例如附录教的命令都是当文件在当前文件夹里时才能实现，我在第二遍的时候才学会了处理非当前文件夹的文件，这才真正能够用命令行来操控自己的电脑了。但Zed没有专门讲解，要求我们自己查资料学习的几个命令我至今未能掌握，可能这几个命令的难度偏大，我需要第三遍去学才能掌握吧。

- 零基础的人学Learn Python the Hard Way其实稍嫌不够，需要找其他书或工具配合。我在Apple Store里面找到一个"Learn Python" APP，知识点全面，学习和练习界面非常友好，还能在上面运行或修改示例的程序，甚至还能做编程PK的游戏。非常推荐这个APP，但不知道是否有安卓版。

- github网站通过试用已经能够掌握其流程原理，但git命令还未能掌握，还需进一步学习。

- Automate the Boring Stuff with Python目前只学了部分，充分感受到了Python各种库的威力，不过也比在学Learn Python the Hard Way时感受到了更大的难度，要成为一个初步能实战的程序员还有很长的路要走！

**Comment by Hanxiaorong** [comment]
Command line 处理非当前文件夹的文件怎么操作？

**Comment by ghost** [comment]
@Hanxiaorong 
我尝试了一下，Command line使用两种路径：绝对路径和相对路径。绝对路径是以根目录作为最上级目录的，例如F:\LearnPyhton\Tom\tom.txt。相对路径则是相对于当前文件夹的路径，例如当我在F:\时，使用LearnPython\Tom\tom.txt就能达到和F:\LearnPyhton\Tom\tom.txt相同的效果。Command line里面用”.."（两点）表示进入上一级目录，也可将“..”用于相对路径中，例如当我在F:\时，使用LearnPython\Tom\ .. \ .. \LearnPython就到了LearnPython文件夹。

LPTHW的附录中都是对当前文件夹进行操作，例如当前文件夹是F:\时，使用ls命令可以看到F:\中所有内容的列表，这实质上是一种相对引用。如果我们想要对非当前文件夹使用ls命令，只需在ls命令后加上目标文件夹的绝对路径或相对路径即可，例如用ls F:\LearnPyhton和ls LearnPython都可以得到LearnPython文件夹中的内容列表。

所以处理非当前文件夹中的内容挺简单的，可能我在课前练习总结中说得有点神秘了~~

**Comment by Hanxiaorong** [comment]
学会了，谢谢！

**Comment by ghost** [comment]
@Hanxiaorong 哈哈，不客气，多多交流
