### ISSUE TITLE
吴晓莉完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by wxlsally1980** [AIHackers/PythonStartUp#181]
习题1
附加练习
1. 略
2. 略
3.#的作用是注释，#号后面的内容python会自动忽略，不会执行。

习题2
附加练习：
1.	略
2.	略
3.	略
4.	略

习题3
附加练习：
1.	每一行的上面用#写一个注释。
#打印文字“I will now count my chickens：”
#打印文字 “Hens”, 显示25加上30除以6得到的结果
#打印文字“Roosters”, 显示25乘以3并除4后得到的余数，被100减去的结果
#打印文字“How I will count the eggs:”
#显示3加2加1减5加4除以2后的余数再减1除以4的得数再加6的运算结果
#打印文字 “Is it true that 3 + 2 < 5 – 7?”
#判断3 + 2 < 5 – 7的值是true还是false， 并打印出结果
#打印文字 “What is 3 + 2?”,计算3加2的结果并显示在同一行
#打印文字 “What is 5 - 7?”,计算5减7的结果并显示在同一行
#打印文字 “Oh, that’s why it’s False.”
#打印文字 “How about some more.”
#打印文字 “Is it greater?”, 判断5 > -2的值是true还是false， 并打印出结果
#打印文字 “Is it greater or equal?”, 判断5 >= -2的值是true还是false， 并打印出结果
#打印文字 “Is it less or equal?”, 判断5 <= -2的值是true还是false， 并打印出结果
2.	略
3. print "We are going to count how much money we spent on Tuesday"
    print 25 + 169 +138
4. 计算的结果只有整数没有小数，是因为脚本里的数字都是整数。浮点数就是带有小数的数。
5.略

习题4
附加练习
这个错误的意思是在脚本的第8行，程序找不到变量‘car_pool_capacity’，也就找不到这个变量的值，所以无法计算。
1.	没有必要，因为这个值是表示人数，整数才有意义。如果用4也没有问题的。
2.	 在每一个变量赋值上加一个注释
3.	给赋值加上一行注释
#给变量cars赋值100
#给变量space_in_a_car赋值4.0
#给变量drivers赋值30
#给变量passengers赋值90
#给变量cars_not_driven赋值“变量cars的值减去变量drivers的值”
#给变量cars_driven赋值“变量driver的值”
#给变量carpool_capacity赋值“cars_driven乘以space_in_a_car的值”
#给变量average_passengers_per_car赋值“passengers除以cars_driven的值”
4.	略
5.	略
6.	在终端运行以下计算
>>> x=3
>>> y=3
>>> print x + y
6

习题5
附加练习
1.	略
2.	略
3.	所有python格式化字符
整型数：%d/无符号整型数：%u/八进制：%o/十六进制：%x   %X/浮点数：%f/科学记数法: %e   %E/根据数值的不同自动选择%e或%f: %g/根据数值的不同自动选择%E或%f: %G
这些都比较简单，需要强调的是"%s"和"%r"的差别。str()得到的字符串是面向用户的，具有较好的可读性， repr()得到的字符串是面向机器的。比如：
string = "Hello\tWill\n"
print "%s" %string
print "%r" %string
输出的结果就是
Hello    Will
‘Hello\tWill\n’
4.不会做。

习题6
附加练习
1.	给每行加注释
#设定一个变量叫x, 它的值是一个字符串，这字符串里还有一个格式化字符%d，这个字符会把数字10代入字符串中
#设定一个变量叫binary，它的值是一个字符串“binary”
#设定一个变量叫do_not, 它的值是一个字符串“don’t”
#设定一个变量叫y，它的值是一个字符串，这个字符串里有两个格式化字符，分别将变量binary和do_not的值代入字符串。
#打印变量X
#打印变量y
#打印字符串,这个字符串里有个格式化字符要将变量X的值放进这个字符串
#打印字符串,这个字符串里有个格式化字符要将变量y的值放进这个字符串
#变量hilarious赋值为False
#变量joke_evaluation赋值为一个字符串，字符串里有一个格式化字符
#打印变量joke_evaluation并将hilarious的值放进前面的字符串
#变量w赋值一个字符串
#变量e赋值一个字符串
#打印变量w和e的内容
2.	不止4处
3.	共有6处，分别在第1，4，9，10，15行
4.	Python可以使用+把两个字符串连接成一个字符串这是python种字符串的功能，当使用加号运算符的时候会调用这个类的_add_()这个函数。

习题7
附加练习
略

习题8
附加练习：
1.	略
2.	不明白为什么最后一行的输出既有单引号又有双引号。

习题9
附加练习：
略

习题10
附加练习：
1.	略
2.	当字符串里用了双引号的时候，就可以使用三个单引号取代三个双引号了。
3.	x = "Good"
   tabby_cat = "\tI'm tabbed in. %s"
   print tabby_cat % x
4.	已经注意到%r 和%s 的区别了。%r打印出来的是作为程序员写在脚本里的东西， 而%s打印的是作为用户应该看到的东西。

习题11
附加练习：
1.	python的raw_input()实现的是将用户输入的内容赋值给一个变量。
2.	找不到。
3.	用类似的格式再写一段代码，把问题改成我的问题。
print "What do yo udo in the morning?",
    morning = raw_input()
    print "What do you do in the afternoon?",
    afternoon = raw_input()
    print "What do you do at night?",
night = raw_input()
print "So, you %r in the morning, %r in the afternoon and %r at night." % (
        morning, afternoon, night)
4.	已经注意到最后一行‘6\’2”’里边有个\’序列。单引号需要被转义，从而防止它被识别为字符串的结尾。

习题12
附加练习：
1.	终端跳出一个框，里面有以下文字：
raw_input(...)
    raw_input([prompt]) -> string
    
    Read a string from standard input.  The trailing newline is stripped.
    If the user hits EOF (Unix: Ctl-D, Windows: Ctl-Z+Return), raise EOFError.
    On Unix, GNU readline is used if enabled.  The prompt string, if given,
    is printed without a trailing newline before reading.
2.	略
3.	pydoc命令是pyhton的文档生成工具。
4.	使用pydoc再看一下open、file、os和sys的含义
open(...)
    open(name[, mode[, buffering]]) -> file object 
    Open a file using the file() type, returns a file object.  This is the
    preferred way to open a file.  See file.__doc__ for further information.
File本身里含有许多的命令，例如readline（…），seek(…), tell（…）, write(…), truncate(…)
os
This exports:
      - all functions from posix, nt, os2, or ce, e.g. unlink, stat, etc.
      - os.path is one of the modules posixpath, or ntpath
      - os.name is 'posix', 'nt', 'os2', 'ce' or 'riscos'
      - os.curdir is a string representing the current directory ('.' or ':')
      - os.pardir is a string representing the parent directory ('..' or '::')
      - os.sep is the (or a most common) pathname separator ('/' or ':' or '\\')
      - os.extsep is the extension separator ('.' or '/')
      - os.altsep is the alternate pathname separator (None or '/')
      - os.pathsep is the component separator used in $PATH etc
      - os.linesep is the line separator in text files ('\r' or '\n' or '\r\n')
      - os.defpath is the default search path for executables
      - os.devnull is the file path of the null device ('/dev/null', etc.)
sys
This module provides access to some objects used or maintained by the
    interpreter and to functions that interact strongly with the interpreter.
    
    Dynamic objects:
    argv -- command line arguments; argv[0] is the script pathname if known
    path -- module search path; path[0] is the script directory, else ''
    modules -- dictionary of loaded modules
    
习题13
附加练习：
1.	系统会报错。因为脚本是需要三个参数才能运行，少于或者多于3个都不行。
2.	再写两个脚本，其中一个接收更少的参数，另一个接收更多的参数。
from sys import argv
script, luggage, bicycle = argv
print "The script is called:", script
print "The woman is holding a:", luggage
print "There is a:", bicycle
3.	 from sys import argv
         script, luggage, bicycle = argv
         print "The script is called:", script
         print "The woman is holding a:", luggage
         print "There is a:", bicycle
         luggage = raw_input("How much do you weigh?")
         bicycle = raw_input("How tall are you?")
其实我真的不懂，raw_input()和argv分明是两种不同的获得参数的方法，为什么这个练习要我们放在一起使用呢？况且我是真不知道怎么把两种方式获得的参数搅和在一起使用。
4.	略

习题14
附加练习：
1.	略
2.	改成完全不同的部分，也没有影响。
3.	略
4.	如果不用三个引号”””来定义多行字符串，用两个””来定义的话，那么这个字符串里就会有很多的反斜杠\，那这个字符串就太烦了。
5.	这个脚本里的两种方式接收的参数并没有交集，太好了，和我想的一样啊。前6行可以自己运行，没有问题。

习题15
附加练习：
1.	给脚本加注释
#从sys调用参数模块argv
#接收参数script和filename
#打开filename文件返回一个file object给变量txt
#打印一个字符串，这个字符串里有一个格式化字符，将filename代入到字符串里。
#对变量X进行read的操作，然后将结果打印出来
#打印字符串
#变量名file_again定义为用户输入的值
#打开filename文件返回一个file object给变量txt_again 
#对变量txt_again进行read的操作，然后将结果打印出来
2.	python open 通过open（）函数获取一个file object，然后调用read（），write（）等方法对文件进行读写操作
3.	略
4.	运行之后
5.	用脚本中的方法获取文件名称更好，因为这样脚本不会那么长，而且别人和自己取用都方便。
6.	略
7.	在提示符下使用open打开一个文件就报错了。
>>> open(ex15.py)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ex15' is not defined
8.	略

习题16
附加练习：
1.	在每一行上增加注释
#从模块sys调用argv
#argv接收两个参数，script和filename
#打印字符串，这个字符串里有一个格式化字符将filename代入字符串
#打印字符串，内容是给出一个选择
#打印字符串，内容是给出另一个选择
#这个地方用户给出选择
#打印字符串“Opening the file…”
#用写入的方式打开文件filename，然后赋值给变量target
#打印字符串，内容是清空filename这个文件
#对target这个文件，执行truncate这个命令
#打印字符串，内容是我将会要求你输入三行文字
#用户输入一行文字，赋值给变量line1
#用户输入一行文字，赋值给变量line2
#用户输入一行文字，赋值给变量line3
#打印字符串，内容是我将会把这几行文字写入到那个文件中
#在target文件中输入line1的文字
#在target文件中输入一个换行符
#在target文件中输入line2的文字
#在target文件中输入一个换行符
#在target文件中输入line3的文字
#在target文件中输入一个换行符
#打印字符串，内容是现在我们要关闭这个文件
#对target这个文件执行关闭命令
2.	试着写一段与上一个习题类似的脚本，用read 和argv读取它
from sys import argv
script, filename = argv
print "Now I am going to read and print this file-%r" % filename
book = open(filename)
print book.read()
3.	target.write(line1\n\line2\nline3)
报错SyntaxError: unexpected character after line continuation character
4.	w是write的缩写，是要告诉python，要用写入的方式打开文件。
5.	不需要了，w在写入之前已经把内容都清空了。

习题17
附加练习：
1.	import就是导入模块，无他。
2.	这个脚本的确是非常啰嗦。其实就是要把一个文件的内容复制到另一个文件里。删掉了一些特性，脚本是像以下这样，可以运行的。
from sys import argv
script, from_file, to_file = argv
in_file = open(from_file)
indata = in_file.read()
out_file = open(to_file, 'w')
out_file.write(indata)
out_file.close()
in_file.close()
out_file.write（open（from_file）. Read()）
3.	作者说他可以把脚本改到只有一行，不可能吧，至少需要三行，因为需要argv来接收参数，解包参数呀。我修改的如下，已可以运行：
from sys import argv
script, from_file, to_file = argv
open(to_file, 'w').write(open(from_file).read())
4.	我一直没有看到作者说的“cat”命令，到底在哪一行？
5.	略
6.	因为每个文件打开后都要关闭，所以要在脚本中用到close().（不明白为什么练习中说代码里有output.close(),分明没有啊！）

习题18
附加练习：无

习题19
附加练习：
1.	略
2.	略
3.	自己编写一个函数，然后用至少10种方式运行这个函数

习题20
附加练习：
1.	在每一行之前加上注释。
#从sys调用argv
#接收两个参数，script和input_file
#定义一个函数，名为print_all,接收一个文件名为参数
#函数的功能是将读取文件内容并且打印出来
#定义一个函数，名为rewind，接收一个文件名为参数
#函数的功能是回到文件最开始的位置
#定义一个函数，名称为print_a_line, 接收两个参数，一个叫line_count, 一个叫f
#函数的功能是打印接受到的参数line_count, 读取文件f的一行内容并打印出来
#定义一个变量current_file，变量的值是打开input_file这个文件的返回的值
#打印字符串，内容是让我们先来打印文件的全部内容，并换行
#执行print_all函数，接收的参数是current_file
#打印字符串，内容是让我们来回退，有点像胶带那样
#执行函数rewind，接收的参数是current_file
#打印字符串，内容是让我们打印三行文字
#给变量current_line赋值1
#执行函数print_a_line，接收参数为current_line和current_file
#给变量current_line赋值为current_line+1
#执行函数print_a_line，接收参数为current_line和current_file
#给变量current_line赋值为current_line+1
#执行函数print_a_line，接收参数为current_line和current_file
2.	通过给current_line赋值1，每次都给这个函数加1，这样就变成了current_count了。
3.	检查了脚本每一处用到函数的地方，确认参数没有错
4.	file中的seek函数作用是回到文件最开始的地方
5.	+=操作符的意思是加法赋值运算符，即c += a 等效于 c = c + a

习题21
附加练习：
1.	我自己写了一个函数，让它返回一个值并打印出数值90了。
def aimeite(a, b, c):
    print "Let's count %d + %d + %d" % (a, b, c)
    return a + b + c

age = aimeite(20, 30, 40)
    print age
2.	可以用正常的方法实现和这个表达式一样的功能，如下：
a1 = divide (iq, 2)
a2 = multiply(weight, a1)
a3 = subtract(height, a2)
what = add(age, a3)
3.	修改“return a + b”变成 ”return a + b + a + b, 这样就输出另外一个值了。
4.	写一个简单的等式，使用一样的函数来计算它
what = age + divide + multiply + subtract

习题
https://github.com/wxlsally1980/For-PY104

小结：

  2017年初的时候，因为未来想让孩子学习编程，我自己也想来先学习编程。到网络上搜索了一下，python是最流行的。于是我先后买了两本关于python的书，自己试着学习。5月份时，我留意到微博上开智课堂在开python的课程，于是我又买了《笨办法学python》自己试着学习。因为前期已经学习了一些python的语句，在做这本书的练习的时候相对轻松一些。
  因为我是英语专业的，所以在输入这些习题的时候，并没有遇到特别的困难。但是在附加练习，就遇到了许多的困难。特别是那些要求使用到习题中的知识的练习，完全就没有办法做。
  遇到困难的时候，我会先跳过，试着往后走，在后面的习题中通常能得到启发。例如习题17的附加练习的第3题，我根本就不知道怎么把整个文件进行“缩写”。我还是往后做了，一直做到第40个练习。然后，我又返回进行第二遍，第三遍对脚本的阅读和理解。每多读一次脚本，就多理解一点，我认为就是多灌输一些“编程思维”。要习得和之前不一样的思维，就必须每天都要看一些脚本。我渐渐明白本书的作者为什么会花专门的章节要我们去阅读脚本。编程是要剥茧抽丝，想要一个结果，必须从最小的单位开始考虑，就像虽然只能看到河流，但却要找到河流发源的地方。在第三遍阅读脚本，并且给脚本注释以后，我终于明白作者的脚本讲的是什么内容，要达到一个什么样的效果。其实那么多语句，只是为了做一件事情而已，而且还有那么多没有什么实际用处的语句。可是我虽然明白作者的意图了，要把脚本改短却也还是不无从下手。直到我读到了习题21的脚本第31行，我看到一个变量用到了那么多个函数，我就突然明白了，就是这样各种嵌套，就可以将脚本改短了！再回头观察那脚本中的语句，就像搭桥一样用了一些变量来实现一步一步的转换，就验证了我的想法。拿掉这些变量，直接嵌套，就可以实现了！我认为写注释是对我最大的帮助了。我喜欢写注释。
  在学习这本书的过程中，我有多次的心流体验，完全沉浸其中，非常舒服。时间不知不觉地流淌，不断尝试，即使有出错，竟然也觉得开心。

**Comment by Hanxiaorong** [comment]
你没有建个库上传练习吗？直接打开你的习题还要下载，不方便。先传到库，再粘贴链接过来，其他人看代码就很方便了

**Comment by wxlsally1980** [comment]
已经建库了，可以看见了吗？

**Comment by sunnyhuang42** [comment]
>https://github.com/wxlsally1980/For-PY104

@wxlsally1980  这里没看到代码哦，你再同步一下？
