### ISSUE TITLE
大西瓜完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by twoyue** [AIHackers/PythonStartUp#188]
[作业代码库](https://github.com/twoyue/forpy104)
[学习笔记](https://github.com/twoyue/forpy104/issues/1)

# **个人背景**
研究生在读，在之前的学习中几乎无代码背景，只有一点点上课时需要用的MATLAB的语言基础，几乎属于纯小白。
毕业后想从事互联网相关工作，如果能偏数据和产品会更好，所以想通过python来入门代码世界，完成小白到技术宅的转变。

# **练习复盘**
练习主要分为以下几个阶段

- 安装python：

小白安装软件的过程真是辛酸……一开始还以为只需要安装一个python就可以运行了，但是没想到代码编辑器、终端、python居然是三个东西……在折腾了一整天之后打出“Hello，world”简直热泪盈眶。

- ex1到ex11的任务及附加任务：

刚接触编程，ex1就运行不了，加上那段时间自我情绪低潮期，一度认为是自己智商有问题，在挣扎了两个小时后果断选择了搁置python……自我怀疑了一天后发现只是自己的单词拼写出现了问题（&*%￥#@！……&）这样的问题在前十个python中出现过数次，空格缺失、单词拼写错误、大小写问题……刚开始一遇到就抓狂，一度认为是软件出了问题，书上及时的出现了一句话“电脑不会出现问题，一定是你错了”。之后慢慢可以静下心来自己去找bug……前十个练习做完后最大的收获就是把bug当成了常态，有bug慢慢调试就好，并不是自己能力或智力的问题= =

- ex12到ex21的任务及附加任务：

argv的部分有时候会忘记输入参数，自己查看了代码很多遍也没有发现问题，百度一下后发现有人遇到过相同的问题，于是在提示下很快找到了问题所在。
后面的习题虽然难度不断提升，但是由于自己心态发生了变化，反而逐渐快了起来，后面十个任务只用一天就完成了……而且基本对代码都已经有所理解~~逐渐上道的感觉很棒！

- 观摩其他同学任务

报名开智课程之后就注册了GitHub，很多同学提前就交了作业，看了看同学们的总结回顾，却一直没有着手写自己的……因为觉得大家总结回顾的逻辑都差别好大，不知道该参照哪位同学的逻辑进行自己的总结……后来忽然反映过来：自己的总结为啥非要参照别人的逻辑模式？（上学期间答题总是有答题给分点……后遗症……）然后就只好用自己的逻辑碎碎念了…………

- GitHub的任务上传

上传任务搞了一天……又有一开始安装python时候那种无助的感觉了……认真的参照开智给的攻略一步步上传，中间出现一些问题被迫卡住……出去转了一圈又向一休哥求助了一下，回来反而迎刃而解……
想感慨下，居然有GitHub这么神奇的东西……程序员的世界丰富多彩啊……探索其中还需要一些时间。

# **总结感悟**
总的来说有几方面感悟吧，一方面是**有bug应该看成常态**，应适应这种不断调整的过程，而不是用消极情绪去对待。
另一方面是多看看别人的作业是有所帮助的，**有问题也应该及时百度和请教其他人**，可以节约很多时间和精力，毕竟写代码又不是考试…………但是也要有自己的一套体系进行消化吸收，而不是跟着别人的思路走。
三是想说技术上，**python前20个进行入门远远不够**，只是到了函数，还没有到达循环和条件语句，所以争取在开课前尽快完成前40个ex吧。
四是觉得自己说话很墨迹……应该学习程序员的性冷淡范，**逐条简洁的描述清楚**……日后改进……

# **心流状态记录**
本次入学挑战后期（ex12-ex21）进行心流的记录，几乎在没有遇到困难和阻碍的时候可以一直保持心流状态一个小时左右。在日常其他学习和阅读中我也是比较容易进入心流状态的一类，总结一下觉得在任务刚刚好思考一下就可以得到答案的中档任务中是较容易进入心流状态的，但是若任务过难，一个问题思考时间过长，会打破这种心流状态，甚至会将问题搁置。
为了更容易进入心流状态：
1.调整任务难度，每次一个台阶，不要跨度过大。
2.找寻解决过难问题的方法，比如及时和组内成员进行讨论，切忌将问题搁置。

**Comment by iamzhuoxuan** [comment]
@twoyue 加油，尽快提交你的任务成果哦 ^_^

**Comment by twoyue** [comment]
@iamzhuoxuan 已提交~~辛苦啦~~(*^__^*)
