### ISSUE TITLE
for 循环问题

### ISSUE THREAD

**Issue by Beckyme** [AIHackers/PythonStartUp#189]
1.我想实现：    
i = 10  
i = i + i // 2  
循环10次。  

2.运行环境：Windows， Python3.6

3.操作：    
> for i in range(0, 10):  
	i = 10  
	i = i + i // 2  
	print(i)  

> i = 10  
i = i + i // 2  
for i in range(0,10):  
	print(i)  
都不对。。。  

如果不对循环次数要求而用数字限制：   
>for i in range(10, 300, i + i // 2):   
	print(i)   

结果也不对。  
还尝试了其他方式得到的结果就差得更多了。   
应该如何更正，非常感谢。

4.解决方案：
感谢 @0x0o 和 @wangluzhou 提供的方法。
0x0o 提供的代码如下：
```Python
num = 10
for _ in range(0,num):
	print(num)
	n = num / 2
	num += n
```

@wangluzhou 提供的代码如下：
```Python
i = 10
for k in range(0,10):
    i = i + i/2.0
    print "the {k}time: {result}".format(k=k+1, result=i)
```

由此我改好了我的代码如下：
```Python
    i = 10
    for k in range(0,10):
        i = i + i // 2
        r = k + 1
        if r < 6:
            l = r
        else:
            l = 6
        print("等级{level}-设置任务数：{mission}。等级{level}-{level_up}需要经验值{result},生命值+1。"
          .format(level = r -1, mission = l, level_up = r, result = i))
```

**Comment by 0x0o** [comment]
```python
for i in range(0,10):
	print(i)
```
这个就是循环十次，没明白为什么要 i = 10 i = i + i // 2。你要的循环十次是什么

**Comment by Beckyme** [comment]
@0x0o 
我需要的是从10开始每次循环递增自身的一半，循环10次。

**Comment by iamzhuoxuan** [comment]
@Beckyme 所以最开始提问的时候，尽可能描述清楚自己的需求，别人才能有效帮到你 😄   提问的智慧 ；）

我的疑问：

> 我需要的是从 10 开始每次循环递增自身的一半，循环 10 次。

从 10 开始，是指从第 10 次开始，还是指 当数字达到 10 ，后续开始每次循环递增自身的一半，循环 10 次。

**Comment by Beckyme** [comment]
@iamzhuoxuan 嗯嗯，好的，谢谢。

是从数字10开始，后续开始每次循环递增自身的一半，循环 10 次。

@0x0o 抱歉，表述有误。

**Comment by 0x0o** [comment]
@Beckyme 根据这么描述可以这么写：(更新过)

```python
num = 10
for _ in range(0,num):
	print(num)
	n = num / 2
	num += n
```

**Comment by Beckyme** [comment]
@0x0o 非常感谢~~~就是这样

**Comment by wangluzhou** [comment]
```Python
i = 10
for k in range(0,10):
    i = i + i/2.0
    print "the {k}time: {result}".format(k=k+1, result=i)
```

**Comment by Beckyme** [comment]
@wangluzhou 谢谢~

也就是说我应该把i的计算方式和i的初始赋值分开。。。

**Comment by Beckyme** [comment]
@wangluzhou 按照您的代码最终改好如下：
```Python
    i = 10
    for k in range(0,10):
        i = i + i // 2
        r = k + 1
        if r < 6:
            l = r
        else:
            l = 6
        print("等级{level}-设置任务数：{mission}。等级{level}-{level_up}需要经验值{result},生命值+1。"
          .format(level = r -1, mission = l, level_up = r, result = i))
```
谢谢~

**Comment by iamzhuoxuan** [comment]
@Beckyme 很赞，成功用 issue 帮助自己解决了问题 👍   不要忘了，解决问题后在第一个 comment 里更新最终解决方案，方便后来人查询。轻轻的小举动，可以方便学友之间更好地交流、互助

**Comment by Beckyme** [comment]
@iamzhuoxuan 嗯嗯 好的~
