### ISSUE TITLE
原子完成Py104入学挑战啦

### ISSUE THREAD

**Issue by yuanzizi** [AIHackers/PythonStartUp#190]
# Github 仓库
-------
yuanzizi<https://github.com/yuanzizi/py104>

#心得体会
-----
自己作为一个计算机专业的本科生，多年的荒废居然都不会coding了，甚是汗颜~！
这次是冲着 开智 认知科学的学习方法报的名。
课前作业差点让自己奔溃：
* python2 python3的切换，让自己有了放弃的念头，后来自己硬着头皮，查找两个版本的差异，一点一点啃下来；
* github 网络搞得很暴躁，后来买了个vpn搞定；
* github 和 markdown 的使用，也耗尽半生修为；

但无论如何，自己坚持完成了，满满的成就感~！
当然，征途才刚刚开始，我会一步一步走下去~！

**Comment by iamzhuoxuan** [comment]
> github 和 markdown 的使用，也耗尽半生修为；

哈哈，但是最后你会发现，哇，它们好好用 ^^
