### ISSUE TITLE
刘荣完成py104挑战了～

### ISSUE THREAD

**Issue by Jessica8729** [AIHackers/PythonStartUp#193]
1. 仓库地址：https://github.com/Jessica8729/python-learning
2. 学习小结：https://github.com/Jessica8729/python-learning/issues/2

关注开智有1-2年，决心学习编程也有半年，但很难下决心咬硬骨头，因而也几乎没有进展。
蹉跎复蹉跎，不堪接受平庸的人生，希望再搏一把，恢复斗志，最好的方式，是挑战一门新的技能。学习编程，志在必得。
不过，上阳老师组织的课，认真程度超出预期，入学即设门槛，心理很是花了点时间才适应。

准备阶段，经历三重天：
1. Git安装遭遇下马威；陆续折腾了4+小时，未果，乖乖求教；求教完，锁定问题点，继续折腾半小时，哑然失笑，显摆mkdir，多么愚蠢的错误！
2. 之后，一路高歌猛进到ex15，开始操作文件，进展变缓，需仔细看示例，仔细琢磨，仔细理解，很花时间；又担心时间不够，心流不稳，只好不求甚解，运行成功后直奔下一练习。
3. 完成练习21后，因出差停了一天，今天想抓紧时间继续深化并补充学习小结，但进展不如预期，原以为2小时能从ex0开始到ex15复习完成一遍，并完成学习小结，但心流极度不稳，到ex15时，又开撕进展缓慢...

总结经验教训：
1. 说到必须做到，每日固定保持7:00-9:00两小时稳定时间学习编程，否则，安排一乱，心思即乱，非常不利于高效学习。
2. 学习编程需要记忆，不断练习，才能熟练。编程的最高境界，应是以最简洁的代码和语法，完成最复杂的表达，编程水平的高下，在于对于语言的熟练掌握并高度抽象和简化。
3. 任何事，应尽量提前完成，不要拖到最后。越往后，越急躁，心流越不稳，效果越差。本次学习，最高效是上周末，因感觉时间还长，老师助学随时在线相帮，心很安，感觉不到时间的流逝，只感觉到心智的增长和能力的增强，本周上班后，由于琐事繁多且出差，学习效率不高。而且，学习到后来，任务越来越难.....
希望老师给一次再逼自己的机会（重新启用高强记忆，重新关注细枝末节），愿以每日2小时全力以赴做承诺。

**Comment by iamzhuoxuan** [comment]
@Jessica8729 尽快补充一下学习小结啦 ^^

**Comment by Jessica8729** [comment]
@iamzhuoxuan 谢谢提醒。已补充学习小结。

**Comment by iamzhuoxuan** [comment]
@Jessica8729 还是没有看到你补充的学习小结哦 ；）

**Comment by iamzhuoxuan** [comment]
@Jessica8729 原来你放仓库 issue 里了，看到啦

**Comment by adi0229** [comment]
@iamzhuoxuan 核查同学们的作业，挺 tedious 的，辛苦了。
