### ISSUE TITLE
Ollie完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by hunshiouren** [AIHackers/PythonStartUp#2]
[仓库地址](https://github.com/hunshiouren/Learn-Python-the-Hard-Way)

**Comment by sunnyhuang42** [comment]
哇 @hunshiouren 好迅速！

不知在进行入学任务时你有没有什么意外的收获：P
有练习笔记也欢迎分享：D

**Comment by hunshiouren** [comment]
> 不知在进行入学任务时你有没有什么意外的收获：P
有练习笔记也欢迎分享：D

是八月份为了参加数据基础班做得。现在则投机取巧拿来一用~ 这两天也在重温~
意外收获是之前买过一本《教孩子学编程 python版》，但一直没看。做任务的时候因为概念理解上有些困难，顺手把这本已经落灰的书的核心章节给扫了。围绕任务学习很高效，并且又少了一本买来后就搁置的书，开心~
练习笔记有点惭愧...自己偶尔的一些小想法写在了程序里，不过确实相当稀少，算不上什么笔记.......

**Comment by liangpeili** [comment]
注释很详细，好评。不过如果代码语句意思很明显的话，也不用那么多注释……
