### ISSUE TITLE
大猫完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by simpleowen** [AIHackers/PythonStartUp#21]
[笨办法学python 笔记](http:www.huangdamao.com)

**Comment by liangpeili** [comment]
都有自己的博客啦~自己开发的？

**Comment by simpleowen** [comment]
@liangpeili 用[Hexo](https://hexo.io/zh-cn/)搭建的：D

**Comment by ZoomQuiet** [comment]
@simpleowen 最好能追加 DISQUS 插件以便同学们针对性回复讨论

**Comment by simpleowen** [comment]
看到@ZoomQuiet  大妈的消息，好激动...[流口水]

已设置好disqus

![disqus](https://cloud.githubusercontent.com/assets/17614465/21520492/9ab880b0-cd2f-11e6-821d-b18829db4323.png)

**Comment by zoejane** [comment]
超帅喔~  
不仅笔记做得用心，有自己的分析和思考，
还用Hexo搭建了自己的Blog系统，而且还绑定了自己的独立域名，同时火速设立好了DISQUS 插件。
不得不说大猫你太牛啦，刚学Python就做得这么棒...犹记得当时我在这几步就掉了好多坑呢...
内心点了一万个赞后，越发觉得要向你学习呢 :)  
我已经开始期待你毕业的时候会是怎么样的啦，哈哈。

**Comment by simpleowen** [comment]
谢谢 @zoejane 
记得从8月份的时候就在咨询3期啥时候开班，也是准备的时间比较长啦，哈哈。

**Comment by leiyunhe** [comment]
太牛了！我要向你学习。。。。

**Comment by simpleowen** [comment]
@leiyunhe 互相学习[握手]

**Comment by VyGiBe** [comment]
@simpleowen 好赞~

**Comment by NBR-hugh** [comment]
@simpleowen 天啊，好帅，不行，要试着倒腾个博客出来！学习之～
