### ISSUE TITLE
[GlamourBunny]完成 Py104 入学挑战啦！

### ISSUE THREAD

**Issue by Glamourbunny** [AIHackers/PythonStartUp#215]
# 基础任务
- [21个练习及附加](https://github.com/Glamourbunny/ForPy104/blob/master/learn_python_the_hard_way_ex1-21.rar)
- [小结](https://github.com/Glamourbunny/ForPy104/issues/1)

- [22-40练习及附加] 待完成

**Comment by LexieLee** [comment]
@Glamourbunny 有计划的小步迭代，很赞 👍 不过建议未来可尝试更优雅便捷的客户端、Git 命令行上传方式，省时又省力的好方式喔。继续加油啦！😄
