### ISSUE TITLE
Xinwei完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by xinweixu1** [AIHackers/PythonStartUp#217]
作业地址：[https://github.com/xinweixu1/python_exercises](https://github.com/xinweixu1/python_exercises)

**Comment by xinweixu1** [comment]
＃练习回顾
自知七月和八月份有集中的暑期课程，所以前34个练习是按计划六月末完成的，时间稍久远。总体来说，鉴于有谷歌的大力帮助，练习过程还算比较顺利，也很容易进入心流，尤其是遇到稍有挑战的练习。练习过程中，最大的挑战应该是适应使用terminal完成和pc对话的过程，以及适应python的语法。

**Comment by xinweixu1** [comment]
## 练习回顾
自知七月和八月有集中的暑期课程，所以前34个练习是按计划六月末完成的， 时间稍久远。练习时使用的是 python 2.7（在 *Learn Python The Hard Way* 还是免费的时候。。。），每个小练习大约需要15～20分钟，每次的练习都安排在写论文的间隙，所以进入心流也很快，尤其是遇到稍有挑战性的练习内容。目前已经购买了python 3 版本的书，正在努力复习中。
总体来讲，鉴于有谷歌的大力帮助，练习过程比较顺利，大多数小困难和小路障都可以很快解决。最大的挑战是适应使用terminal和pc完成对话的过程，以及适应python的语法结构。目前觉得python最令人惊艳的一点是处理字符串的灵活性，之前有用R处理字符串的经历，相比python磕绊很多。不过自己之前的编程经历属于现学现用型（尤其发现自己的学习路径和 *Learn Python The Hard Way* 的实践型风格十分契合），所以缺乏系统的知识结构，期待利用开智的课程补上知识结构这一课。

**Comment by adi0229** [comment]
写论文间隙，还能进入心流做练习。精力很强，大赞。
