### ISSUE TITLE
张倩完成Py104课前最少挑战

### ISSUE THREAD

**Issue by zqlog** [AIHackers/PythonStartUp#225]
学习心得正在整理，先把做好的21个练习上传占位。继续努力，小白的蜗牛历程，加油！
https://github.com/zqlog/ForPy104/upload/master

**Comment by iamzhuoxuan** [comment]
@zqlog 你分享的链接有误，应该是这个吧：https://github.com/zqlog/ForPy104  😄  
加油，尽快提交一下小小心得、笔记 ^_^
