### ISSUE TITLE
Julia0527完成Py104入学挑战啦

### ISSUE THREAD

**Issue by Julia0527** [AIHackers/PythonStartUp#226]
https://github.com/Julia0527/forPy104

我是编程小白，从上周日起，每天利用下班后晚上在家的时间研究Python入门，终于完成了前21个测试小练习，练习的部分基本都看懂了，附加题还是有一定的难度，需要时间理清思路。有的练习题，在最初开始做的时候，很茫然，但是做到后面的某个练习题时，有时会一下子就明白了前面某个练习题里某个指令的意思。
还是要多做练习，多思考，孰能生巧。

心得体会：
1） 对python和编程有了大致的了解；
2）掌握了python中经常使用的英语词汇，能够在没有中文译文的情况下看懂一些简单的相关文本；
3）掌握了在python中实现简单的输出、输入、计算、注释、提示、定义变量、操作文件、定义函数等；
4）能够理解命令行里一些常见提示错误的原因，并回到编辑器里修改；
5）有了一些基本的常识后，可以在此基础上自己进行思考，查阅资料时更有针对性。

**Comment by Julia0527** [comment]
您好！收到此封邮件，请问需要我做什么？



xingshaoxuan0527
 
发件人： 李晴
发送时间： 2017-08-03 17:16
收件人： AIHackers/PythonStartUp
抄送： Julia0527; Mention
主题： Re: [AIHackers/PythonStartUp] Julia0527完成Py104入学挑战啦 (#226)
Assigned #226 to @Julia0527.

**Comment by LexieLee** [comment]
@Julia0527 你收到这封邮件只是系统提示啦。

另外提醒下，你的仓库里还没有上传你的练习成果，请尽快上传喔～😁 加油

**Comment by Julia0527** [comment]
https://github.com/Julia0527/forPy104

您好！我修改了网址，麻烦您再试一下？谢谢

**Comment by Wangjunyu** [comment]
@Julia0527  作为纯小白，能完成21个小练习已经很棒了。不过在开智的课程里，还可以更好，比如说：
1. 参考其他同学的作业，总结，参与提问和讨论。
2. 总结21个小练习的学习心得，写写看教程。
3. 继续做21-42的练习。
4. 完成提高的作业。 
5. 基于已有的知识，自己模拟场景，开发小功能。
