### ISSUE TITLE
何炜完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by ivanhw** [AIHackers/PythonStartUp#235]
下午基本把前21个做了，因为完全没基础，好多看不明白。附加题都没做，遇到的问题上网查了一下。
这个地址给的对吗？
https://github.com/ivanhw/python-.git

**Comment by ivanhw** [comment]
我的作业提交了吗？我怎么看不见？

**Comment by LexieLee** [comment]
> 遇到的问题上网查了一下

遇到问题能够主动 google 检索，这个习惯很棒喔～另外，既然完成了 21 个小练习，就尽快上传上来吧，加油💪 上传作业的方法可参考 issue [HbAssignmentHandUpAndReview · OpenMindClub/Share Wiki](https://github.com/OpenMindClub/Share/wiki/HbAssignmentHandUpAndReview)

**Comment by ivanhw** [comment]
Markdown怎么用？在哪儿下载？

**Comment by LexieLee** [comment]
关于 markdown 的使用方法可以查看 wiki 中的协作基础技能部分 [IdxCooperateBasicSkill · OpenMindClub/Share Wiki](https://github.com/OpenMindClub/Share/wiki/IdxCooperateBasicSkill#%E5%8D%8F%E4%BD%9C%E5%9F%BA%E7%A1%80%E6%8A%80%E8%83%BD)，不过还是建议你先探索如何上传入学任务😝 ，距离截止时间不多啦

**Comment by ivanhw** [comment]
正在弄，上传不了。



 
发件人： 李晴
发送时间： 2017-08-03 23:14
收件人： AIHackers/PythonStartUp
抄送： 何炜; Assign
主题： Re: [AIHackers/PythonStartUp] 何炜完成 Py104 入学挑战啦 (#235)
关于 markdown 的使用方法可以查看 wiki 中的协作基础技能部分 IdxCooperateBasicSkill · OpenMindClub/Share Wiki，不过还是建议你先探索如何上传入学任务???? ，距离截止时间不多啦

**Comment by ivanhw** [comment]
以前没用过，很多现研究。是浏览器的问题。先开始用的猎豹，后来换了IE还是不行。刚下了Chrome，这才上传成功。不过没留神把文件注释好像全改了 ；）
