### ISSUE TITLE
Ramsey 完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by draachen** [AIHackers/PythonStartUp#237]
代码地址：**https://github.com/draachen/LPTHW**
（其实是8个月前完成的，可不要让我重新敲一遍。。我保证这周末重新看一遍LPTHW）

上完Py103，又报Py104。希望遇见更多大牛，同侪压力来得更猛烈些吧~~

**Comment by draachen** [comment]
@LexieLee 我是不是必须写点什么心得？才能achievement?

**Comment by draachen** [comment]
LPTHW的心得，在Py103提交任务时候已经提到过了。这次复习的心得呢（其实还没来得及复习呢），稍后补充吧。
我发觉没了同侪的压力，自己一个人很难把Python坚持下去。所以Py104开课的时候，我就又来了。

**Comment by sunnyhuang42** [comment]
@draachen 哈哈又见面啦~ 这期的入学挑战和 Py103 的不完全一样，有劳移步 #138 仔细核对检查确认至少完成了基础挑战，才有 achievement 标记哦。
