### ISSUE TITLE
张太阳完成 Py104 入学挑战啦！

### ISSUE THREAD

**Issue by ZhangCici** [AIHackers/PythonStartUp#245]
- [ 练习笔记](https://github.com/ZhangCici/python/issues/7)
- [代码](https://github.com/ZhangCici/python)

## 完成入学挑战
7月29日开始二刷，6天完成前40个习题。从最开始翻开这本书，小白到#后面是注释都不知道，到现在饶有趣味地欣赏自己写的代码。下班回家之前，在上班堵车路上，早晨起床后，甚至开会间隙也能写上两行。我想自己的状态准备好可以入学了。

## 缘起
想学编程的冲动，比想象中更简单。工作上开始不停的跟技术打交道，被逼着接触数据处理，置身在一片语言陌生的荒野之地。而当我发现团队的程序员面对新的东西也是去找wiki，一步一步去做，瞬间觉得他们没有那么神秘莫测。我自己也可以按照wiki解决问题，终于明白去年学长说不给自己设限的意思。工程师们会相信一切都可以找到解决方案，这也许是他们最棒的地方。
 
## 心流时刻
就像这本书里说的，笨方法更简单。打破了心里天花板之后，编程这件事本身竟然也是一种享受了。我按照书中的笨方法，一步一步听话的做下去。安心之余，还有很多成就感。有趣的事，每天在加班之后尝试做一些习题，代码运行成功的那一刻感到无比的解压。想进入心流时刻，WOOP大法好。If 工作做完了，then 开始写代码。if 早上到公司坐在工位上， then 开始写一段代码。生活的惊喜在于，这个七月末不仅开始正式报名python，同时还开始自学小提琴。我好奇如果把两件很难的事一起做，会是什么样呢？负负得正也是很有趣的事。周日的时候连续7个小时，写代码写累了就站起来练习小提琴，拉空弦拉的累了就再坐下来一行一行的写。现在我可以激动的说，完成了前40个练习还可以拉出一首完整的曲子了！

## 遇到问题
较高强度的集中练习，吸收很多，问题也很多，总体还算顺利。逻辑和循坏部分的练习比较好理解，解包和函数部分反复看了很久。练习中的小问题会随手问下程序员大哥，例如怎么让脚本只打印一行。在习题13 参数、解包和变量，对解包概念非常的不理解。硬着头皮按照书上的代码写下去，反复看琢磨是怎么被实现的。做到习题17之后，再回头看习题13 的说明，终于真的明白" from sys import argv \ script, first, second, third = argv "。

## 太酷了
开始学习python，也得到了团队程序员小哥哥们的支持。思维也会有变化。编程还会带来什么呢？更多的难题和更多的不懂，当然也会有更多的成就感。总之，就强迫自己输出吧。同时，我也要时刻警醒，不要认为每天输入完那些代码就完成任务了。要保持高价值的输出，留下思考才是最宝贵的。希望可以早点说出那句：你会编程，他们不会。太酷了。

**Comment by ziwuniao** [comment]
哈哈，期待你的Python之歌：）
