### ISSUE TITLE
小楼一夜（GitHub：Gungh）完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by Gungh** [AIHackers/PythonStartUp#246]
[入学挑战：练习1-21](https://github.com/Gungh/exercise_for_py104)

我是文科生，毕业后机缘巧合在某大厂成了数据分析师。日常主要是SQL跑跑数，Excel制作输出一些报表，结合业务写分析报告。中间尝试过R、Python，学习数据挖掘，但由于各种原因（主要是懒和没毅力。。。）都是浅尝则止，目前对Python的熟悉了解仅限于使用过pandas，替代在Excel由于数据太大不方便操作的数据透视表功能。
所以本次完成入学挑战使用的是电脑早前安装的anaconda包的Python3，也正是因此，在入学挑战卡了在习题13上：
我习惯直接在jupyter里执行代码，而不是照书上的方式写进.py文件，在终端里运行，由于argv返回的参数需要外部读入，导致总是返回not enough values to unpack 的错误，而我在查看直接执行argv的结果后，又将其错误的理解为是自己的编程环境与作者不同导致文件路径不同，尝试去修改代码文件路径，在此处周折了两天时间，其间给开智提交了入学挑战障碍，在仓库了发布了求助的issue，最后才在某位朋友指导下找到问题所在。
另外接受朋友建议，编辑器里写代码，终端里执行，尽量保证脚本执行环境和书上一样。不要把时间花在环境和Python版本造成的问题上。
此外总体顺畅，由于之前多少有点点了解，实际花费的时间并不长（但拖延癌发作导致现在才提交任务）。没有太多针对编程本身的感悟和认知刷新，主要还是加深了初学SQL时的一个体会：写代码是个细致活儿，没有大概差不多，必须完全正确，一个细节错了都不行，细节就是魔鬼啊同志们。

**Comment by thxiami** [comment]
@Gungh 
共同学习，一起加油。文科生机缘巧合入了大厂做数据分析师，很好奇这么大的跳转是怎么做到的~~

**Comment by adi0229** [comment]
@Gungh 同好奇，我也是文科生。
目前，想提高自身的数据分析水平，只学了一点皮毛的pandas和Tableau，感觉姿势水平还差多了。

**Comment by Gungh** [comment]
@thxiami @adi0229 谢谢关注，说是机缘巧合，其实波折不少。
通过校招进入该厂在一个区域部门，在部门做的工作是后台系统策划，主要对接研发，相当于业务方产品经理的角色。项目比较小，瞎折腾了一年。
这时候哥们对接过的北京部门的A总监因为有个数据系统的项目需要招人，就把我推荐过去了。然后就是一段不怎么愉快的经历，A总监两个月后股票到手跑路，规划的项目没了，接手的B总监自己有几个经验丰富的数据分析下属，不怎么管我，在新部门成了边缘人，给业务写SQL跑跑数，偶尔帮忙发点报表。
待了大半年实在待不下去，又换了个业务部门，新换的C总监虽然也不是数据出身，但是部门需求数据场景特别多，写SQL做报表写报告对接项目帮业务做分析和优化流程，也没人带，一个人埋头练级打怪，然后就到了今天。

**Comment by thxiami** [comment]
真是一波三折，那这次学python主要是想以后往数据分析和挖掘上转码

**Comment by Gungh** [comment]
@thxiami 目前已拿到一家小公司的策略产品offer，打算转回产品轨道。学Python编程和数据挖掘对于我来说，不一定是必备技能点，可以算是附加技能和业余爱好吧，目前更倾向于出于喜欢而不是工作需要拿Python来做些有趣的东西。经历了不同的岗位，现在感觉自己还是更喜欢产品的工作生态。

**Comment by thxiami** [comment]
@Gungh 兴趣驱动学习，这应该是很舒服的一种状态。希望在这期培训班中一起加油学习，互勉互助。

**Comment by adi0229** [comment]
@Gungh 这就是内在驱动了，加油。
