### ISSUE TITLE
夏至完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by haokong0703** [AIHackers/PythonStartUp#249]
[练习作业](https://github.com/AIHackers/PythonStartUp/issues/new)

# 体验
* 因为记错了时间，导致最后才开始了课前任务。幸好，还没完全错过。
* 小白用户，做这个习题的时候，感觉十分有趣，有时候半懂不懂，但坚持做下去。会发现后面的练习会解决前面的问题。有时觉得豁然开朗。
* 出现结果的那一刻，感觉到心流

# 经验
*  跟着书本要求，一步一步踏实执行
* 很多时候是拼写错误
* 没写完几行，就先运行一次
* 记下问题，不要再犯错误
* 练习，反复练习

**Comment by iamzhuoxuan** [comment]
@haokong0703 似乎你提供的链接有误哦 ；）

找到你的链接啦：[haokong0703/PythonStartUp: Python 课程入学任务提交处](https://github.com/haokong0703/PythonStartUp)
