### ISSUE TITLE
ChowHak 完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by chowhak** [AIHackers/PythonStartUp#250]
### [学习小结](https://github.com/chowhak/Learn-Python-The-Hard-Way#learn-python-the-hard-way-学习小结)

正如卓璇在`入学挑战`里提醒过的：
> 入学挑战并非闭卷考试，你可以动用各种方法，促进自己完成挑战。

遇困时，大可放胆行动。不要仅局限于书本。

**Comment by iamzhuoxuan** [comment]
@chowhak 啊哈，被 mention 了，好开心，Python 课一起加油  😄

**Comment by chowhak** [comment]
@iamzhuoxuan 嗯！全力以赴😜
