### ISSUE TITLE
乙淅君完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by lctfwyt** [AIHackers/PythonStartUp#257]
[练习成果](https://github.com/LazyCatTF/LPTHW)
[学习笔记和小结](https://github.com/LazyCatTF/LPTHW/blob/master/studynotes.md)

嗯...感觉自己啃得很踏实很慢，目前完成了 21 个习题及附加题，是个小白哦 > <
经验就是不急躁也不消沉，不去盘算这个速度学下去还得多少天能完成，每天把当天能学到的学好就成
很多感想总结都在小结里写到啦，总之要学习的还有很多，今后和小伙伴们一起加油～

**Comment by wchengvincent** [comment]
4点多了还在学习！ 敬佩啊。。！

**Comment by lctfwyt** [comment]
@wchengvincent 哈哈，怕 deadline  前提交来不及修改，晚上赶着写学习笔记和小结，不知不觉通宵了。。:P 谢谢支持～

**Comment by dudechuan** [comment]
```
while True:
  for i in ["/","-","|","\","|"]:
    print "%s\r" % i,
```
这是个无休止的循环，中断程序或者退出terminal/powershell才能终止。

**Comment by lctfwyt** [comment]
@chuanski 哇看得好仔细呀！谢谢～的确我是找不到别的办法直接点红叉叉呢。
