### ISSUE TITLE
nanshanpai完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by nanshanpai** [AIHackers/PythonStartUp#258]
[作业仓库](https://github.com/nanshanpai/Py104)

# Python学习小结

1. 整体顺畅，开始容易后面就越来越难，大部分问题出在拼写，也就是基础的语言用法不够熟练。

2. 文件输入部分比如input() 和 from sys import argv,理解实际的物理文件和赋值的参数有点混淆。输出部分因为是python 3.6所以 print经常忘带括号，而且提示的行数提示是出错问题的下一行，

3. 函数部分理解的也不是很透彻，比如何时该自己定义函数，我初步认为如果重复提取某一个执行动作时可以定义，函数名称后面（）里的参数，与函数内部的参数变量，的区别不是很清楚。

4. 经常出错地方一是拼写，缩进，还有函数后的冒号。

5. 一旦函数出错，我的做法是先看错误提示，有些错误提示很明确，比如缩进问题，然后看代码，找相应位置的拼写，和用法是否有误，实在看不出来就搜索 python 加错误提示，有时可以得到启发。
或许把解决问题流程改为，看提示定义问题类型，看代码，后看官方文档，网络求助。由内而外的解决问题会好些。

6. 两个发现当给代码写注释时，感觉写出来后，对程序的理解好像更深入了，也就是说，对于问题或者是代码把它用语言描述出来，对于加深理解有帮助，  发现二是强行自己写程序问题才会真正的知道自己是否真的懂了，越来以为理解的可能是有偏差的。

**Comment by Wangjunyu** [comment]
刚开始有不理解的地方是很正常的，随着不断的探索，理解了过去的内容，又会有新的不理解。这是一个典型的探索过程。
自己模拟场景用代码实现是非常好的学习方法，而且你已经有了自己的解决问题的套路，很棒哦~继续加油。
