### ISSUE TITLE
韩旻完成Py104入学挑战啦

### ISSUE THREAD

**Issue by kkkk-lll** [AIHackers/PythonStartUp#259]
https://github.com/MIniHahn/ForPy104

从powershell开始学起，每一个习题都要做至少一个小时，经常上网查和问懂的人。虽然现在还是不太熟悉，但比起开始有了明显进步。有些仍然存在疑问，希望以后可以通过讨论解决。::::x3

回顾练习过程：
对电脑完全的小白，从powershell开始学起。每个习题都会花费很多时间，很多东西还太生疏。几乎每个都不怎么顺畅，特别是ex20和ex21。
我觉得每个习题对我来说都比较困难，时间花的多一点，但每当完成一个习题，总会特别开心。

复盘解题过程：
很多时候搞不懂编码的意思，通过python打开不了也是常有的事。遇到不懂的一般是上网查或者问懂的人，当然即使这样，有时候还是会存在疑问。
从这几天的学习学到最多的，就是遇见问题要沉着，问了别人或上网查还是不懂的话，那就先放一下，有时候跳过做后面的会突然明白之前不懂的地方。
以及，不要太过钻牛角尖， 我在做习题的时候，一点点理解不了的都会卡住，有时候甚至会一天都解决不了，到后来才慢慢好起来。
比如说在学到习题15的时候，提到执行一下close()，我完全不知道是什么，上网查了也没懂，输入了很多种形式，都没成功，最后是通过问懂的人解决的。

我认为学习这个，对文字的理解力特别重要，还有待提升。
对于我，ex20和ex21目前其实还没有弄明白，提交了后还要再想一想，希望可以更好。
完成习题后，很开心，几天前我还对编程、python完全不懂，现在至少可以操作一点了。

**Comment by Wangjunyu** [comment]
@MIniHahn  可以把小结放到Issue里来，和大家一起分享。

**Comment by kkkk-lll** [comment]
好的\(^o^)/~
