### ISSUE TITLE
范冬冬完成py103学习任务啦

### ISSUE THREAD

**Issue by fandongdong89** [AIHackers/PythonStartUp#26]
仓库地址：https://github.com/fandongdong89/-Py103.git

**Comment by sunnyhuang42** [comment]
@fandongdong89  需要在 Issue 正文附上你的作业仓库地址哦，详见 #1

**Comment by sunoonlee** [comment]
@fandongdong89 代码仓库还是空的，记得来填坑哦

**Comment by fandongdong89** [comment]
你好，已填上作业坑。笔记我还来不及导入，后续补上。谢谢！

在 2016-12-27 21:36:01，"sunoonlee" <notifications@github.com> 写道：


@fandongdong89 代码仓库还是空的，记得来填坑哦
