### ISSUE TITLE
GraceJiangye完成Py104入学挑战啦~

### ISSUE THREAD

**Issue by GraceJiangye** [AIHackers/PythonStartUp#260]
- [练习任务](https://github.com/GraceJiangye/LHP-E)
- [个人总结](https://github.com/GraceJiangye/LPH/issues/1)

**Comment by Wangjunyu** [comment]
总结很到位，编程的初阶学习是一个不断挖坑和填坑的过程~填的多了就习惯了。
提一个小建议：既然已经学了这么多了，可以模拟一个场景，跟着自己的思路实现小功能，会有意想不到的坑和更意想不到的收货哦。

**Comment by GraceJiangye** [comment]
@Wangjunyu  谢谢你的建议，期待接下来的遇坑填坑收获~
