### ISSUE TITLE
陈瑶霖完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by SailingChen10** [AIHackers/PythonStartUp#261]
我的 GitHub 仓库的挑战成果地址：
https://github.com/SailingChen10/Py104Startup/

1. 入学挑战体验：
- python没有想象中那么难，不要着急，静下心来进入心流很重要
- 学到第四题，瞬间觉得Python很有意思，开始自己设计计算题，举一反三的感觉挺好
-原本一边备考GRE一边上班，好怕自己坚持不下来，但是在小伙伴的鼓励下活过来了
-努力进入心流状态真好

挑战完成建议：
- 加分题经常看不懂中文在写什么，建议查看英文版，另外极客学院有一个指导可以参考：
http://wiki.jikexueyuan.com/project/learn-python-hard-way/
- 照着题目打一遍代码，但一定要校对，不然就是浪费时间
- 打一遍代码之后一定要思考清楚原理，不然也是浪费时间，附加题就是起到强迫思考的作用，另外也可以举一反三，加深印象。举一反三这个对我来说特别好使。
- 原理、易错点建议写成方便查阅的纸条，或者印象笔记剪藏，可以随时打开来看
多问“愚蠢“的问题，抓住身边一切比你更懂的人问问题
- 充分利用网络资源，每一步遇到的问题，其实基本都能找到，github、知乎或者国外的编程论坛
-把遇到的问题及解决方法详细记录， 题做多了之后，遇到问题可以先不着急搜索答案，而是自己想想
-给自己设定每天的完成时间，如果遇到问题导致超时未完成，可以放到第二天再查看，也许第二天就迎刃而解，或者第二天问懂编程的同事。

**Comment by iamzhuoxuan** [comment]
@SailingChen10 好像你的仓库里还没有上传你的笨方法小练习作业哦 ^ ^

**Comment by SailingChen10** [comment]
@iamzhuoxuan 好像是之前拖拽上传没成功……已经补交，请查看～https://github.com/SailingChen10/Py104Startup/

**Comment by iamzhuoxuan** [comment]
@SailingChen10 好的 收到 ；）
