### ISSUE TITLE
vickie完成 Py104 入学挑战啦

### ISSUE THREAD

**Issue by appletrue** [AIHackers/PythonStartUp#264]
学py过程中的一些[随手记录或者总结](https://github.com/appletrue/hardWayPython)

----------学习总结--------------
基本上遇到几个比较卡壳的问题
1，关于终端那部分，有些命令，我搜索了网上的基础命令，然后建立了目录，但我想在mac 上找到我所建立的目录，因为对mac 的使用也不太熟悉，怎么都找不到，后来还是在安装的pyCharm 编辑器里边调出来的这个目录。我还需要继续熟悉，怎样熟练的操作这个OS。
办公室安装的是win7系统，调出来powershell 运行一些文件的操作就就很直观能看到，包括后面的一些对文件的改写练习，操作起来没有遇到卡壳的地方，代码有错就另当别论了。：（
对照着这个gitbook 地址来进行学习的：有兴趣的可以看下，感觉比下载电子书方便，练习过的目录上会打一个对勾，下次可以轻松找到进度页面，[分享一下](
https://flyouting.gitbooks.io/learn-python-the-hard-way-cn/content/)

2，py2 和py3 的语法切换
刚开始的时候，基本就只有两个函数不一样，一个是input，在py2 里面是raw_input；一个就是print，基本上就一个print 在py3 里面作为一个函数来对待，是有圆括号的区别，我卡在输出字符串 需要格式化，但输出结果在中间有变量调用的时候，一直报错，说语法错误，后来终于找到错误，输出时，中间是不要写逗号的。
个挑战吧。👊

---------------------赤裸裸的分割线-------------------
之前学过一些R，脑袋里边总有拿那个语法跟这个对比的成分存在，还好没干扰

**Comment by iamzhuoxuan** [comment]
@appletrue  可以提交一下能提交的练习呐；本子上的笔记可以拍照上传 ; )
