### ISSUE TITLE
HenryLGL完成Py103入学任务啦

### ISSUE THREAD

**Issue by HenryLGL** [AIHackers/PythonStartUp#27]
练习仓库，请查看：

https://github.com/HenryLGL/Openmind-Python

之前其实学习过这套教程，但后来准备考试之类的，久而久之就自己找借口，没继续学了；这几天重新看回复习，感到一种半途而废的痛苦，实在很不好受。所以很希望能借助这次开智的课程培养自学的好习惯。

**Comment by sunoonlee** [comment]
欢迎上船！这里有很棒的学习理念和氛围，有一群优秀而努力的伙伴，最不缺的就是动力啦。
