### ISSUE TITLE
ziyouma1010完成py104入学挑战

### ISSUE THREAD

**Issue by ziyouma1010** [AIHackers/PythonStartUp#271]
差不多还有半个小时，就截止提交入学任务了，说实在的，心里还是很紧张。
赶紧提交了，不知道这样提交的方式是否正确？[完整内容](https://github.com/ziyouma1010/python01/issues/1)

**Comment by iamzhuoxuan** [comment]
@ziyouma1010 提交姿势很正确😄   可以进一步探索使用客户端、命令行提交
