### ISSUE TITLE
刘帆提交了 Py104 入学挑战啦

### ISSUE THREAD

**Issue by skynever2009** [AIHackers/PythonStartUp#277]
https://github.com/skynever2009/ForPy104

       作业完成情况：之前没有基础，命令行都不会，从零开始。习题做到第21题，过程中没有遇到太多问题，一点一点按照作者的指导写代码、运行代码、寻找错误、解决错误。
       遇到的问题：从装软件就开始遇到了问题，在Powershell 中Python的路径配置的命令中，不知道有无空格，试了老半天才弄好。其他的主要是写概念、定义不清楚，例如“”“与'''的区别，基本可以上网找到答案。另外，就是附加联系中的一些应用练习，例如习题13后的"将 raw_input与argv一起使用"，由于不太熟悉，所以这样的题当时不会，到后面也慢慢理解了。
       从这周开始学习，每天大概2~3个小时，今天上午还特意请假学习了一上午，这种一点一点提高的感觉非常好。无奈时间太紧张，没有能够完成作业，到这周末应该可以作为前21道题。希望，可以继续跟班学习。

**Comment by gzMichael** [comment]
加油哦，期待你的作业

如果前面的已经完成的，不妨先提交到仓库，完成后再在这里更新一下就可以了

**Comment by skynever2009** [comment]
https://github.com/skynever2009/ForPy104
