### ISSUE TITLE
powershell中调用python出现问题

### ISSUE THREAD

**Issue by yuanchunrong** [AIHackers/PythonStartUp#28]
#Title：powershell中调用python出现问题

## 背景

- 我期待实现的效果/欲达成的目的是：在powershell中成功调用python
- 我的系统、版本等环境配置是：Windows8.1系统版本，64位操作系统，python2程序包存放在C:>Users>Administrator中

## 现象

我想实现上述效果/目的时，遇到了这样的情况：

- 输入：在powershell中输入“python”，显示无法识别。按照教程输入[Environment]::SetEnvironmentVariable("Path","$env:Path;C:\Python27", "User")运行，依然出现问题
- 触发：
![default](https://cloud.githubusercontent.com/assets/20310214/21447690/4b0c63bc-c913-11e6-9e01-d8239893d1b1.PNG)
- 问题：是否是哪里出现问题？导致无法调用呢？

## 分析

我已经做了以下尝试：

- 尝试 0：
    - 参考：在python的官方网站中，寻找相关问题
    - 判断：
    - 实验：
    - 结论：没有找到相关问题
- 尝试1：通过百度搜索“如何在powershell中调用python”
- 判断：逐个点击答案，发现和教程里面是一样的，没有找到答案

## 方案

我推测可以有以下几种解决方案，请问大家哪种思路正确，或有其它思路建议？

- 解决思路 0：
    - 参考：
    - 设想：是否是路径出现错误？
## 这个问题困扰了我很久，感谢各位同学的帮助

# 最终解决方案：
[重新设置环境变量](https://github.com/OpenMindClub/PythonStartUp/issues/28#issuecomment-269075903)

**Comment by derek-cheng** [comment]
试试这个办法：
1.找到：我的电脑-属性-高级系统设置-环境变量-系统变量-PATH
2.新建地址。就是把你的PYTHON所在路径添加在后面，如下图：
![image](https://cloud.githubusercontent.com/assets/24478433/21448200/c441ca72-c91a-11e6-81c0-a378dbc9ae8a.png)
试试……

**Comment by simpleowen** [comment]
检查下python的安装路径是不是c:\python27

**Comment by sunoonlee** [comment]
楼上说了我想说的。我来补充点小建议吧：

- Windows 下的命令行程序可以试试 [git bash](https://git-for-windows.github.io/)，体验更好
- 搜索尽量用 Google，可试试英文关键词，比如 "run python in powershell" 之类
  - 为了使用 Google，你可能需要科学上网。相关工具，简单点的可试试 [lantern](https://github.com/getlantern/lantern)，想更流畅可试试 shadowsocks + 合适的VPS
- 有条件的话，能用 Mac 最好，可以避免不少无谓的坑
  - 我的血泪史：二期全程用的 Win，前不久刚换了 Mac，悔不当初

**Comment by StoneAmber** [comment]
昨天遇到相似问题，重启电脑后powershell可以调用python。
由LPTHW EX0知，若无效，试试ACTIVEPYTHON ( http://www.activestate.com/activepython/downloads )。

**Comment by yuanchunrong** [comment]
## 感谢各位同侪们的热心帮助，powershell首次调用python的问题已经解决
## 解决方法：重新设置python的路径后，就成功调用python啦
## 具体步骤如下：
1. 电脑版本：Windows8.1专业版。点击桌面的“这台电脑”，在左上方点击“计算机”，然后点击菜单栏的“系统属性”，如下图：
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%AD%A5%E9%AA%A41.png)

2.双击“高级系统设置”，在出现的“系统属性”对话框中，选择“高级”子选项，点击右下方的“环境变量”，如下图：
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%AD%A5%E9%AA%A42.png)
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%AD%A5%E9%AA%A43.png)

3.在“环境变量对话框”中，双击“path”，然后在对话框中把python的存储路径复制上去，点击保存。最后，重新在powershell中输入“python”，调用成功。
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%AD%A5%E9%AA%A44.png)
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%AD%A5%E9%AA%A45.png)
![](http://ogzvyw5z8.bkt.clouddn.com/%E6%88%90%E5%8A%9F%E8%B0%83%E7%94%A8.PNG)

**Comment by sunoonlee** [comment]
哈，第一个顺利解决的 issue ~

@YCR007 使用 issue 的姿势已经相当娴熟。进一步地，如果能把解决方案更新在一楼，就更方便其他同学参考了。（可以只给出回复的链接，比如 https://github.com/OpenMindClub/PythonStartUp/issues/28#issuecomment-269075903 ）

**Comment by StoneAmber** [comment]
今天翻看官方参考文档发现
![wh](https://cloud.githubusercontent.com/assets/24679912/21471797/5ec5c2ee-caf9-11e6-8faa-9f1b14e20932.PNG)
