### ISSUE TITLE
熊猫完成 Py104 入学挑战啦 achievement

### ISSUE THREAD

**Issue by Farahcoco** [AIHackers/PythonStartUp#280]
[入学任务](https://github.com/Pandacoco/Learning-Python-from-the-Openmind)

· 学习心得
虽然是复训学员，可初次学习的时候好像就是成了捐学费的选手，中间卡到了一个GUI的任务里，无法自拔
于是中途就被打败放弃了。可是人总会有不服输的时候，而我也是在广鹤同学的鼓励下，又一次觉得再给自己多一次机会尝试一下，总不能被一次的失败就给自己定论，于是有了这次的内容

**Comment by LexieLee** [comment]
@Pandacoco 四期入学任务与三期稍有不同，详见 issue  [编程思维 Python 基础班四期入学挑战 · Issue #138 · AIHackers/PythonStartUp](https://github.com/AIHackers/PythonStartUp/issues/138) 需至少完成前 21 个小练习 + 不少于 300 字的小结

**Comment by Pandacoco** [comment]
那我一会更新一下

**Comment by Farahcoco** [comment]
已经更新~
