### ISSUE TITLE
有谁在设置环境变量的时候遇到和我一样的问题？

### ISSUE THREAD

**Issue by alice7706** [AIHackers/PythonStartUp#31]
Title：
ex0中，有一个路径的设置，命令是：[ENVIRONMENT]::SETENVIRONMENTVARIABLE("PATH", "$ENV:PATH;C:\PYTHON27", "USER")

我用拷贝的办法，在命令提示符下输入，结果总是提示”文件名、目录名或卷标语法不正确。“
## 背景
电脑的操作系统是win10,也在网页上搜索这个命令，安装python为默认位置c:\python27。
在c:\也尝试过输入，在c:\python27目录下也尝试使用。
网上搜索可以在控制面板-系统-高级设置中设置环境变量。但是找不到这个设置。

python小白。求助！

> 注意：问题解决后
> 	
> 1. 你需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
> 2. 顺手点击 Issue 下方右下角 close issue ，归档

**Comment by Leohb** [comment]
我的电脑（右键属性）->左边的高级系统设置 -> 选高级，最下面就是系统变量阿。
具体的可以bing搜一下教程。还有，可以用Pycharm，这个比较好看。

**Comment by maokaiqi** [comment]
你可以在桌面图标右击我的电脑 或者 如下图打开文件夹
![0](https://cloud.githubusercontent.com/assets/11867264/21459691/826f37d6-c97b-11e6-86d1-200ea38ef133.jpg)
打开文件夹的话进入下面的界面
![1](https://cloud.githubusercontent.com/assets/11867264/21459646/15ae382c-c97b-11e6-9997-5936938e46cc.jpg)
右键点开后，点属性会进入下面的界面
![2](https://cloud.githubusercontent.com/assets/11867264/21459652/2c94508a-c97b-11e6-8422-dc5b5aded47b.jpg)
点高级系统设置进入下面的界面
![3](https://cloud.githubusercontent.com/assets/11867264/21459664/4d0a706a-c97b-11e6-9bde-fc6a5a22b7d7.jpg)
看到环境变量了吧？点开她
![4](https://cloud.githubusercontent.com/assets/11867264/21459707/9aeb6208-c97b-11e6-834d-f377301d0579.jpg)
接下双击path这一栏，进入下一个界面
![5](https://cloud.githubusercontent.com/assets/11867264/21459714/af3619ce-c97b-11e6-9c67-bd00547a7d74.jpg)
好像不需要之前系统要注意写上分号的细节了。
这是我比较笨的方法，其它的方法我也不太会，希望能帮到你。

**Comment by ouyangzhiping** [comment]
给 @maokaiqi 同学手动点赞:D

**Comment by sunoonlee** [comment]
@maokaiqi 的回答图文并茂、清晰明白~
我来补充下在 Win10 中找到环境变量设置对话框的另一种方式：

1.  Win + Q 启动搜索
2. 输入“环境” 即可找到环境变量设置的入口
---
另外，win8.1 下类似问题，参考： https://github.com/OpenMindClub/PythonStartUp/issues/28#issuecomment-269075903

**Comment by sunoonlee** [comment]
win8.1 下类似问题，参考： https://github.com/OpenMindClub/PythonStartUp/issues/28#issuecomment-269075903

**Comment by alice7706** [comment]
已经按照教程设置了路径。谢谢maokaqi同学。

**Comment by StoneAmber** [comment]
今天翻看官方参考文档发现
![wh](https://cloud.githubusercontent.com/assets/24679912/21471797/5ec5c2ee-caf9-11e6-8faa-9f1b14e20932.PNG)
