### ISSUE TITLE
chousawa完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by chousawa** [AIHackers/PythonStartUp#39]
https://github.com/chousawa/Python

**Comment by liangpeili** [comment]
都完成的话，可以优化下代码的排版，就不用一行不空的写下来了， 参考[Google Python 风格指南](http://zh-google-styleguide.readthedocs.io/en/latest/google-python-styleguide/contents/)

**Comment by chousawa** [comment]
@liangpeili 好的，感谢建议
