### ISSUE TITLE
[Hugh]完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by NBR-hugh** [AIHackers/PythonStartUp#4]
[NBR-hugh/python](https://github.com/NBR-hugh/python)

**Comment by NBR-hugh** [comment]
# 命令行快速入门

## 使用方法：

1. 遇到不懂或者无法理解的东西，就把它记录在笔记本上

2. 完成一个习题后过一遍记录的问题，试着解决问题：网络搜索，问人，学邮件

3. 每个习题的过程都重复这一过程



## 如何记忆东西

* 告诉自己一定会去做，不找技巧或者窍门，安心去做

* 要记的东西写在索引卡上，要学的写一面，答案写另外一面

* 每天花15˜30分钟，专心学习索引卡，试着把每一张都记住，没记住的单独放一摞，🚽自己提高多少

* 晚上睡觉前花5分钟学习自己答错的卡片



## 问题

### 习题3

mkdir

* mkdir -p temp/stuff/things/frank/joe/alex/john 中的-p是什么意思？

创建路径／文件夹时只能逐层递进，想创建多级路径就要添加-p

* 注意／的全角与半角



### 习题5

cd

* ˜的输入方法是什么？

 键盘问题……~ ～
* cd到达一个路径，为什么到things之前的层级不用/,到达frank需要frank/?

  A：这样的



* 注意“”的中英文""





### 习题6

ls



### 习题7

rmdir

* rmdir 我确定为空目录但拒绝删除时，实际上这个目录有一个.DS_Store 的文件，为什么同样的创建指令，有的文件夹有这个文件，而有的文件夹没有呢？ 键入rm -rf <dir>即可删除，这里的-rf 是什么意思？



### 习题8 在多路径切换

> pushd  ＋ 路径 1  ：指保存当前路径0，并跳到路径1；

计算机返回2个~，第一个~为路径1，第二个为保存的路径0；

> pushd ＋ 路径2，

计算机返回~路径2 ~路径1 ~路径0

> pushd ＋空白  调换路径0与路径1的位置，有3个路径时不行





### 习题9 创建空文件夹

touch



### 习题10 复制文件 cp



* Q:如何将一个文件复制到home目录或者桌面？

练习中的指令只能将文件或文件夹复制到同一级活着或者下一级，如何复制到上一级？甚至移动到不同的路径？ 移动指令mv也有同样的问题。

A:先到达包含目标与来源文件（夹）的根目录，从当前层级到目标文件的路径表示出来即可，记住：文件夹后加／，文件不用

如示例：cp Desktop/test.txt  temp/



### 习题14 删除 rm



循环移除文件时要小心操作





### 更多任务

*  xargs   
https://blog.gtwang.org/linux/xargs-command-examples-in-linux-unix/  
一列输出参数，-n控制每列个数 



* sudo 管理员身份运行 


* chmod -- change file modes or Access Control Lists 改变文件模式或者获得控制列表
http://www.chinaunix.net/old_jh/7/240097.html  
* linux 文件查看／编辑介绍
https://www.centos.bz/2011/10/linux-file-view-edit/

**Comment by NBR-hugh** [comment]
# 问题集
## 习题0:
Q：第12步，如何使用键盘切换回到Terminal窗口？
A：command ＋tab

## 习题1:
Q：如何让脚本只打印一行？
A：在其他行前面加＃失效？

## 习题3:
- 来自@OMlalala 同学的笔记
> Q：对于Common Student Questions的最后一个问题：Why does / (divide) round down?
> 作者的回复是
> /只是将小数点后的部分去掉了，可以尝试 7.0 / 4.0 和 7 / 4。
> 我觉得回复不严谨。
> 负数取模怎么算中提到三种整除法取整方式
> 
> 向上取整
> 向下取整
> 向零取整
> 作者的回答属于Truncate取整，即向零取整，即舍去小数部分；
> 而python的处理方式为Floor取整，即向下取整，取比实际结果稍小的最大整数。可以尝试-9 / 4 ，结果是 -3， 而不是 -2。
> 当分子分母均为正数时，结果一样；但有一个为负数时，结果就不一样了。


## 习题4：
- 来自@OMlalala 同学的笔记
> Q：Common Student Questions的第三个问题：How can I print without spaces between words in print? 没有理解。
> A：作者答复的代码是：print "Hey %s there." % "you"，打印出的结果是：Hey you there。
> 和代码 print “Hey you there.”的结果一样，单词之间还是有空格呀？


## 习题8:
Q1：最后一行的输出既有单引号又有双引号，你觉得他是如何工作的呢？


Q2: 为什么％r有时打印出来的是单引号，而我实际用的是双引号？
A：Python 会用最有效的方式打印出字符串，而不是完全按照你写的方式来打印。这样做对于％r来说是可以接受的，因为他是用于调试与排错的，没必要打印出好看的格式。
  q:这里的最有效是什么意思呢？ 要是最省纸墨就应该都是单引号，所以背后的工作原理是什么呢？

## 习题9:
Q：怎样将每个月份显示在新的一行？
A：字符串以\n开始就好了

## 习题10:
Q1:用三个单引号取代3个双引号，什么场合下应该用单引号而不是双引号？

Q2：那段小程序到底什么意思？
zhuanYiXuLie.py

## 习题11:
Q1：raw_input实现的是什么功能？
  A：输入的功能，而且无论输入什么都是str类型

Q2:如何读取用户输入的数进行计算？
  A:试试x＝int（raw_input（）），它会把用户输入的字符串用int（）转成整数。

## 习题13:
Q:argv 和 raw_input有什么不同？
 A：用户输入时机不同，前者在执行命令时输入，后者在脚本运行过程中输入

## 习题17:
Q:找出为什么要需要在代码中写output.close
A： 因为open会占据进程，并且close的意思是编辑已经完成，保存并关闭，除非后面接.read(),这个命令运行文件会自动被关闭

## 习题18:
Q：函数命名有什么规则？
和变量名相同，只要以字母／数字以及下划线组成，而且不是数字开始，就可以。

## 习题19：自己编写至少一个函数出来，用10种方式运行这个函数？
  A：理论上有无穷多种方式运行一个函数，这是什么意思？练习中有三种，直接给出数字，用来自脚本的变量，二者结合，还有什么其他方式呢？想不到诶...

## 习题20:
Q：seek（）函数是做什么用的？
A：
1.pydoc file:
 |  seek(...)
 |      seek(offset[, whence]) -> None.  Move to new file position.
 |      
 |      Argument offset is a byte count.  Optional argument whence defaults to
 |      0 (offset from start of file, offset should be >= 0); other values are 1
 |      (move relative to current position, positive or negative), and 2 (move
 |      relative to end of file, usually negative, although many platforms allow
 |      seeking beyond the end of a file).  If the file is opened in text mode,
 |      only offsets returned by tell() are legal.  Use of other offsets causes
 |      undefined behavior.
 |      Note that not all file objects are seeable.
> 参数偏移是一个字节计数。原始参数来源默认为0（偏移从文件开头开始，偏移应该大于等于0）；其他值>是1（相对于当前位置移动，正或负），和2（相对文件末端移动，经常是负的，虽然许多平台允许查找超出文件末端） 如果文件在测试模式下打开，只有通过tell（）返回偏移才是合法的，使用其他偏移会引发未定义的行为。
要注意不是所有文件都是可见的。

2. [示例](http://www.runoob.com/python/file-seek.html)
```
line = fo.readline()
print "读取的数据为: %s" % (line)

# 重新设置文件读取指针到开头
fo.seek(0, 0)
line = fo.readline()
print "读取的数据为: %s" % (line)
```
```
读取的数据为: 1:www.runoob.com

读取的数据为: 1:www.runoob.com
```
重置文件读取箭头


## 习题23阅读代码
### 说明
高亮为陌生命令，函数，亮红字为问题：
### 问题   
 - 1.print 后面为什么要加（）？
 - 2.`r’/ws'`是什么意思？
[阅读代码的来源](https://bitbucket.org/bitscope/websocket-demo/src/0e2061fe4e5a8a8929d22e4e566e817c246e4797/main.py?at=default&fileviewer=file-view-default)

```
import tornado.httpserver
import tornado.websocket
import tornado.ioloop
import tornado.web

import threading
import serial
import time
import base64

debug = False

ser = serial.Serial('/dev/ttyUSB0', 115200, timeout=0.01)

serviceId = 0

receivedBuffer = bytearray()
internalCommand = bytearray() # Used to send commands to the BS from within the server
serverObject = None
serverOpen = False

print("Running")

class WSHandler(tornado.websocket.WebSocketHandler):
    def check_origin(self, origin):
        # Allows loopback client
        return True
    def open(self):
        global serviceId, serverObject, serverOpen
        serverObject = self
        serverOpen = True
        print('New connection:', serviceId)
        serviceId += 1
      
    def on_message(self, message):
        global receivedBuffer
        if debug:
            print('message received %s' % message)
        # ser.write(message.encode())
        # print(ser.read(len(message)))
        receivedBuffer += message.encode()
 
    def on_close(self):
        print('connection closed')
 
# Create application instance with the above class as the handler
application = tornado.web.Application([(r'/ws', WSHandler),])
                                         ^ 为什么加／以及’
# Create an HTTP server with the above application instance
http_server = tornado.httpserver.HTTPServer(application)
# Listen on port x
http_server.listen(16385)

# Function that runs the service forever
toThread = tornado.ioloop.IOLoop.instance().start
# Embed that in a thread and run it
serverThread = threading.Thread(group=None, target=toThread, name=None, args=(), kwargs={}, daemon=None)
serverThread.start()

time.sleep(1)

def safeWrite(message):
    halts = ["A", "D", "T", "Z", "X", "Y", ">", "<", "U"]
    # Hopefully nothing ever comes after D in the same command
    echo = bytearray()
    haltEndBuffer = ""
    for char in message.decode():
        if char not in halts:
               haltEndBuffer += char
        else:
            haltEndBuffer += char
            ser.write(haltEndBuffer.encode())
            while ser.inWaiting() < len(haltEndBuffer):
                time.sleep(0.001) # Sleep until there's enough data echoed
            echo += ser.read(len(haltEndBuffer)) # Read and append expected echo bytes
            haltEndBuffer = ""
    if debug:        
        print("Echo: ", str(echo.decode()))
        
    return echo
    
while serverThread.isAlive():
    out = bytearray()
    if receivedBuffer:
        temp = receivedBuffer
        receivedBuffer = bytearray()
        out = safeWrite(temp) # out becomes whatever is echoed
    if (ser.inWaiting() or out) and serverOpen:
        try:
            out += ser.read(ser.inWaiting())
            serverObject.write_message(bytes(out), binary=True)
        except (tornado.websocket.WebSocketError):
            serverOpen = False
    time.sleep(0.010)

serverThread.join()
serverObject.close()
```

## 习题24:
Q：\t的作用真的是缩进4格么？ 那为什么第12行\n\t的缩进这么多呢？而且还和单纯的\n缩进的格数不一样？

```
poem = """
\tThe lovely world
with logic so firmly planted
cannot discern \n the needs of love
nor comprehend passion from intuition
and requires an explanation
\n\t\twhere there is none.
"""

--------------

	The lovely world
with logic so firmly planted
cannot discern 
 the needs of love
nor comprehend passion from intuition
and requires an explanation

		where there is none.
```

#### 观察所得：
\t前有字符，空1小格，没有字符2小格，在行首，4小格

**Comment by NBR-hugh** [comment]
# TIPS

## 函数注意事项
 1.函数定义是以def开始的吗？
2.函数名是以函数名与下划线_组成的吗？
3.函数名是否紧跟(？
4.括号内是否包含参数？多个参数是否可以以逗号隔开？
5.参数名称是否有重复？（不能使用重复的参数名）
6.紧跟着参数的是不是括号与冒号（）：？
7.紧跟函数定义的代码是否使用4格缩进？
8.函数结束的位置是否取消缩进？

## 运行（使用，调用）一个函数时的检查要点：

1.调用函数时是否使用函数名
2.函数名是否紧跟（？
3.括号后又无参数？多个参数是否以逗号隔开？
4.函数是否以）结尾？
**!!!  run /use/ call  function  is the same.**

## 检查
    1.倒着阅读这段代码，在每一行的上面加一行注释
    2.倒着朗读出来，找出自己的错误
    3.从现在开始，把你的错误记录下来，写在一张纸上。
    4.在开始下一个习题时，阅读一遍你记录下来的错误，并且尽量避免在下一个习题中再犯同样的错误。
    5.记住，每个人都会犯错误。程序员和魔术师一样，他们希望大家认为他们从不出错，不过着只是表象而已，他们每时每刻都在放错。

## 其他tip
- 习题2:##倒着读代码## 可以精确处理每个片段，更容易发现错误。
- 习题3:当添加中文注释时，在文件首行添加 # -*- coding: utf-8 -*-
- 习题7:从代码风格而言，每行字符最好不超过80
- 习题12:另一种用法，在raw_put()的（）内可以用双引号添加提示信息
- 习题14:三个引号可以定义多行字符串，而％是字符串的格式化工具

```
print"""
Alright,so you said %r about liking me.
You live in %r. Not sure where that is.
And you have a %r computor. Nice.
""" % (likes,lives,computor)
```

- 习题19:一个细节：函数里的变量和脚本里的变量之间是没有联系的。
- 习题25:
  -帮助文档即是定义函数时放在“””之间的东西；
  -from ex25 import * 倒入所有模块

- 习题33:注意全局变量与局部变量

**Comment by yuanchunrong** [comment]
哇！作业后注意点记录的如此详细，我也要多多向你学习！

**Comment by NBR-hugh** [comment]
@YCR007   哈，共勉共勉，加油！

**Comment by NBR-hugh** [comment]
大致浏览了一下留言数目较多的学友们的学习笔记，几点收获：
1. 文燕菇凉的必要难度理论在编程上应用的想法有点小启发
2. 印象笔记记笔记太不爽了，笔记转记在wiki上吧，看看有没时间试着搭自己的博客，向大猫同学学习；目测大猫同学是根粗壮的大腿，哈哈。
3. OMlalala 同学对于细节的测试于把握，还有笔记的可读性方面可以借鉴改善
4.雷云鹤同学做到了 40+，还阅读了推荐书目，并做了笔记，嗯，看起来也是一条相当粗壮的大腿，哈哈。
- 代码为上，多多交流，多多讨教，学习提问，学会剥削机器，真是充满期待啊，各位请多指教～
