### ISSUE TITLE
文燕完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by wenyan666** [AIHackers/PythonStartUp#47]
[文燕的python入学任务](https://github.com/wenyan666/wenyan-python)

**Comment by wenyan666** [comment]
在拿到书开始练习到12个练习的时候，没有遇到什么大问题，到后面会出现一些小问题，不过也都是单词拼错，把反括号写成了中文的，双引号另外一半忘记加上了这类的错误，根据报错信息提示很快就能改正。

 但是练习结束之后，留在脑袋里面的python模型并不完整，能提取出来的东西依旧很有限，于是开始思考：

> 为啥不试一下用六小时定理来练习？

- 就是看完书，然后不马上开始动手，在脑子里面预演，等合上书建个一定时间后再按照记忆或者自己的理解来敲代码练习？

很有趣。

你会发现，刚开始由速度带来的优越感都会消失，转而有越来越多的盲点。这是的hard way learn python才展示出它的hard。

这种方式也会迫使你放弃掉 **我很聪明** ，而转向 **我很努力** 。

聪明是自欺欺人，努力才是当下应该关注的不是么？

**Comment by CrickeySong** [comment]
不仅完成了任务，还分享了自己的思考和收获，棒棒哒👍

**Comment by mxclover** [comment]
边学习边思考，而不是仅仅完成任务，向你学习👍

**Comment by chousawa** [comment]
六小时定理这个很棒！打算也这样操作看看。

**Comment by wenyan666** [comment]
@CrickeySong @mxclover 
哈哈，谢谢认同。其实任务做的质量不高才有的反思，希望以后继续加油~

**Comment by wenyan666** [comment]
@chousawa 试试看，有新发现一起再交流啊

**Comment by Irene6161** [comment]
不仅自己完成的棒棒的，教我的时候也是思路清晰！

**Comment by NBR-hugh** [comment]
@wenyan666 也就是说从代码提取需求（或是输出结果），再6个小时后根据需求（或结果）不看书自己打出代码，我就说感觉练习过程缺少了什么，文燕姑娘好想法！学习之～
不过有个小疑虑：假如是完全的新手这样增大难度会不会损害正反馈印象心流呢？因此建议或许可以完全招打过一次，有正反馈建立信心，再用提升难度的方法练习第二次，深化体会，补充细节或许会更好？哈哈，有时间再试试

**Comment by wenyan666** [comment]
@Irene6161  么么哒~

**Comment by wenyan666** [comment]
@NBR-hugh 嗯嗯，补充得很赞！之前是因为自己已经照着书本敲了一遍觉得少了些什么才想到增加必要难度的学习思路。
先熟悉内容→寻找正反馈建立信心→提升难度做第二次练习这个方法很赞！学习了~

也可以通过阅读先熟读代码，然后用笔和纸写出关键步骤和关键词，核对关键词后再根据关键词来敲代码也不错~这样有利于自己思路更清晰，而不至于是死记硬背那几行代码，代码要记，里面的逻辑思维更应该学。

欢迎继续讨论哟~
