### ISSUE TITLE
ken079完成Py03 任务啦

### ISSUE THREAD

**Issue by ken0709** [AIHackers/PythonStartUp#49]
完成啦
https://github.com/ken0709/learn-pyton-the-hard-way

**Comment by CrickeySong** [comment]
好的，等你哈，要在 12 月 30 日 11：42 之前哦~

**Comment by sunoonlee** [comment]
完成啦！好棒。首层的状态怎么还木有更新。

**Comment by ken0709** [comment]
怎么更新？直接close issue？

**Comment by sunnyhuang42** [comment]
@ken0709  ， @sunoonlee 指的是你在第一个 comment 里，写的还是 「先完成了1-9章节，正在继续ing」 。可以把这句话删了或更改为已经完成 17 个小练习了哦。

点击每个 comment 右上角铅笔按钮即可编辑该  comment。

**Comment by ken0709** [comment]
@sunoonlee @ishanshan 谢谢噢，已经修改完成。
