### ISSUE TITLE
OMlalala完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by OMlalala** [AIHackers/PythonStartUp#51]
[练习成果](https://github.com/OMlalala/Python)
12月26日，完成ex01-ex05
12月27日，完成ex06-ex17，复习ex01-ex05
12月28日，复习ex06-ex11
1月1日，复习ex12
1月3日，复习ex13-ex14
1月4日，复习ex15-ex16
1月6日，复习ex17(未写教程)，用py3写ex01,ex03-06.
1月7日，复习ex17，完成ex18

**Comment by liangpeili** [comment]
加油！后面的练习(ex1~ex17)也要完成

**Comment by OMlalala** [comment]
@liangpeili 已经完成，谢谢鼓励。

**Comment by OMlalala** [comment]
### Exercise 0

1. 我使用的是Windows系统，所以
- Terminal or shell 对应 Powershell
- text editor 对应 Atom

2. Powershell里退出python的方式有两种 `quit()`、`exit()`

3. 第18条指导建议中，提到 list the directory 。
可通过代码 `dir` 和 `ls` 实现，二者功能一样：通过 `alias dir` 和 `alias ls` 查询作用，发现都是 get-childitem.

**Comment by OMlalala** [comment]
### Exercise 1
#### Py2
1. 写字符串时，可以用 ''（单引号）或 ""（双引号），二者均可。

2. 对于本身包含 ‘（单引号）或 “（双引号）的字符串，在字符串首尾需使用另外那种符号。
比如：
要打印出：I'd much rather you 'not'.
代码中的首尾符号，需使用 “”（双引号），即：`"I'd much rather you 'not'."`

3. 如果非要使用 ’（单引号），可以借助后面学的 `\`，即：`'I\'d much rather you \'not\'.'`

#### Py3
1. 语法变化：使用 `print `时，需要加括号： `print()`

2. 对于多行连续打印，可以在 `“”“  “”“ `之间输入代码。 
注意：代码与 `“”“` 之间是否换行，会在结果中体现为是否空行。
示例1：
代码及结果
`print ("""Hello World!""")`
![1](https://cloud.githubusercontent.com/assets/10447824/21719282/d97feeda-d457-11e6-8b71-abf1bc85b74c.png)  
示例2：
代码及结果
```
   print ("""
   Hello World!
   """)
 ```
　![2](https://cloud.githubusercontent.com/assets/10447824/21719565/67812cf2-d459-11e6-8d42-3d17cdf72be2.png)

**Comment by OMlalala** [comment]
### Exercise 2
1. 在Atom里批量注释连续的代码，可以使用快捷键：`Ctrl+?` （也可以批量恢复为正常代码）

2. 小技巧：倒着读代码：从最后一行最后一个单词往前读

**Comment by OMlalala** [comment]
### Exercise 3
#### py2
1. 若想打印出"True"，有两种代码实现方式
- 打印 Ture `print “Ture”`
- 打印结果为正确的逻辑表达式 `print 2 > 1`
- 光在编辑器里输入` 3 + 2 > 5 - 7`，是不会打印出 ` True` 的。

2. 若想数字的计算结果出现小数，有3种形式
- 22.0 / 7
- 22 / 7.0
- 22.0 / 7.0

3. 对于Common Student Questions的最后一个问题：Why does / (divide) round down? 
作者的回复是
> `/`只是将小数点后的部分去掉了，可以尝试 `7.0 / 4.0 和 7 / 4`。   

我觉得回复不严谨。
[负数取模怎么算](http://www.jianshu.com/p/452c1a5acd31)中提到三种整除法取整方式
- 向上取整
- 向下取整
- 向零取整
作者的回答属于Truncate取整，即向零取整，即舍去小数部分；
而python的处理方式为Floor取整，即向下取整，取比实际结果稍小的最大整数。可以尝试` -9 / 4` ，结果是 -3， 而不是 -2。
当分子分母均为正数时，结果一样；但有一个为负数时，结果就不一样了。

#### py3
使用 `/ ` 时，结果不会向下取整，会显示小数部分，不是非要分子或分母使用小数。
代码：
```
print (22 / 7)
print (22.0 / 7)
print (22 / 7.0)
print (8 / 5)
print (-9 / 4)
```
结果：
![1](https://cloud.githubusercontent.com/assets/10447824/21720641/4327425a-d45f-11e6-84da-b46259c879b2.png)

**Comment by OMlalala** [comment]
### Exercise 4
#### py2
1. 区分“=”和“==”，前者是给变量赋值，后者是逻辑判断。

2. 问题：Common Student Questions的第三个问题：How can I print without spaces between words in print? 没有理解。
作者答复的代码是：`print "Hey %s there." % "you"`，打印出的结果是：`Hey you there`。
和代码 `print “Hey you there.” `的结果一样，单词之间还是有空格呀？

#### py3
复习时，使用了 `%d`, 注意：代码中 的 `% variable`, 需要在 `print` 的括号内。
正确：
`print ("There are %d cars available." % cars)`
结果：
![2](https://cloud.githubusercontent.com/assets/10447824/21722265/ca3f0424-d466-11e6-9cad-f46a1f01e305.png)

错误：
`print ("There are %d cars available.") % cars`
结果：
![3](https://cloud.githubusercontent.com/assets/10447824/21722271/cfad2ddc-d466-11e6-9232-1ebb8e5bf9ab.png)

**Comment by OMlalala** [comment]
### Exercise 5
1. 比较练习4与练习5的思路。
如果要实现练习5的打印部分。借鉴练习4的思路，关键部分代码如下：
```
print "Let's talk about", my_name, "."
print "He's", my_height, "inches tall."
print "He's", my_weight, "pounds heavy."
print "Actually that's not too heavy."
print "He's got", my_eyes, "eyes and", my_hair, "hair."
print "His teeth are usually", my_teeth, "depending on the coffee."
print "If I add", my_age, ",", my_height, ',', "and", my_weight, "I get", my_age + my_height + my_weight, '.'
```

但是其中 “,”（逗号）和 "."（句号）和相邻字符间有空格，不能完全模拟练习5的输出结果。

2. 练习5中提到的三个formatters，参照[doc](https://docs.python.org/2.4/lib/typesseq-strings.html)，释义如下
- %d. Signed integer decimal.
- %s. String (converts any python object using str()).
- %r. String (converts any python object using repr()).

**Comment by OMlalala** [comment]
### Exercise 6
#### py2
1. 当我看到打印的结果：Those **who** know binary and those **who** don't. 我在想如果对其中出现两次的“who”用format characters，是否只使用1个即可，结果发现不行。参数的个数与format在句中的出现次数一致。
代码：
```
who = "who"
y = "Those %s know binary and those %s don\'t." % (who, who)
print y
```

2. 更加深刻的认识了 `%r` 和 `%s` 的区别
- `%r`, debugging, displays the "raw" data of the variable
- `%s`, displaying variables to users

对代码：`print "I said: %r." % x` 变形加工
```
print "I said: %r." % x
print "I said: '%r'." % x
print "I said: %s." % x
print "I said: '%s'." % x
```
结果依次为
```
I said 'there are 10 types of people.'.
I said ''there are 10 types of people.''.
I said there are 10 types of people.
I said 'there are 10 types of people.'.
```
结论：
`%r` 和 `'%s'` 的效果是一样的。（第1行和第4行）
`'%r'` 应该在实际中不多见吧。（第2行）

3. 拼接两个字符串，考虑 连接符 为 “+” 和 “,”， 区别在于 空格。
代码：
```
w = "This is the left side of..."
e = "a string with a right side."

print w + e
print w, e
```

结果：
```
This is the left side of...a string with a right side.
This is the left side of... a string with a right side.
```
注意第二种情况，a前面的空格

#### py3
1. 这个练习没有发现和py2的区别，但是发现了一个细节！

2. `print` 后面的变量是区分大小写的！
之前按照教材输入 代码时，因为比较细心，所以没有出现过输错大小写的情况。
现在按照结果反推代码时，发现自己输错了一个字母的大小写。
代码：
```
words_1 = 'There are 10 types of people.'
print (words_1)
print (Words_1)
```
注意第二个`print`后跟的变量的`W`是大写。
结果：
![1](https://cloud.githubusercontent.com/assets/10447824/21725305/d4a2d07e-d472-11e6-9dc9-10b2a87ea080.png)

反思这个问题，其实根源是，自己平时工作用 SAS 比较多，而SAS中，变量命名是对大小写不敏感的。
所以，这点也是今后自己注意的地方，在使用python编程时，注意大小写。

**Comment by OMlalala** [comment]
### Exercise 7
1. 看到输出结果是 `..........` ，忘了可以用 `*`，除了标点符号，数字，字母都可以使用 `*` 。

代码：
```
a = "." * 10
b = "2" * 5
c = "c" * 7
print a + b + c
```
结果：
`..........22222ccccccc`

2. 看到输出结果：`Cheese Burger`，利用 `*` 和简化变量的方式可以优化代码：
```
end1 = "C"
end2 = "h"
end3 = "e"
end4 = "s"
end5 = "B"
end6 = "u"
end7 = "r"
end8 = "g"

print end1 + end2 + end3 * 2 + end4 + end3,
print end5 + end6 + end7 + end8 + end3 + end7
```

**Comment by OMlalala** [comment]
### Exercise 8
对于输入中文的问题，作者在Common Student Questions的第三个问题答复：使用 `%s`。
但是我输入代码后，蹦出问题 pep-0263。查询[stackoverflow](http://stackoverflow.com/questions/6289474/working-with-utf-8-encoding-in-python-source)后，尝试三种代码：
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

b = '%r %r %r'
print b % ('我', '爱', '你')

b = '%s %s %s'
print b % ('我', '爱', '你')

b = '%s %s %s'
print b % (u'我', u'爱', u'你')
```
结果依次如下：
![put chinese into string](https://cloud.githubusercontent.com/assets/10447824/21524265/dc57c042-cd4f-11e6-97d1-9f9eeebe375b.png)

结论：
正确显示中文，需采纳第三种方法。

**Comment by OMlalala** [comment]
### Exercise 9
1. 再一次深刻认识 %s 和 %r 的区别。
代码：
```
months = "Jan\nFeb"
print "Here are the months: %r" % months
print "Here are the months: %s" % months
```
结果：
```
Here are the month: 'Jan\nFeb'
Here are the month: Jan
Feb
```
结论，类比Excel的单元格格式：
%r 好像文本格式，即使输入公式，也是显示公式；
%s 好像常规格式，输入公式，会计算结果。
![1](https://cloud.githubusercontent.com/assets/10447824/21524704/2c767764-cd53-11e6-9f82-7b24613c9b35.png)

2. 小技巧：输入一段话，可以用 `“”“` 首尾照应。

**Comment by OMlalala** [comment]
### Exercise 10
1. `\\` 和 `\` 效果一样？
输入代码：
```
print "I'm \ a \ cat."
print "I'm \\ a \\ cat."
```
结果都是：
`I'm \ a \ cat.`

2. 常用 escape sequences
- `\n` 换行
- `\t` 缩进
- `'''` 和 `“”“ `效果一样

**Comment by OMlalala** [comment]
### Exercise 11
在[interacting-with-raw_input/](https://python4kids.brendanscott.com/2010/07/01/interacting-with-raw_input/)里练习关于`raw_input`的代码。两点注意：
1. `raw_input` 返回的是 `string` ，若要计算，还需要 `int()` 。 代码：
```
a = raw_input("Insert number 1: ")
b = raw_input("Insert number 2: ")
print "(a + b) will be ?"
print a + b
print int(a) + int(b)
```
结果：
```
Insert number 1: 20
Insert number 2: 30
(a + b) will be ?
2030
50
```

2. 两种代码实现同一种表达，后者相对简便。
```
print "How old are you?",
age = raw_input()

age = raw_input("How old are you? ")
```

**Comment by VyGiBe** [comment]
你还对代码的功能做了比较试验~
学到了~

**Comment by NBR-hugh** [comment]
## 笔记中学到的几点
1. 查阅英文官方文档：因为是买了中文书直接照着练，所以查询都是直接google，有很多过度解释又或者忽略的信息，发现文档的解释更系统更清晰，学习之～
2. 笔记说明附上代码本体，运行结果以及结论，十分清晰，学习之～
3. 对细节的把握，比如对s％，r％的理解，我从结果出发，大致理解为s％为显示效果便于用户阅读，r％显示原始文本便于程序员调试就停止，@OMlalala同学还做了多次代码测试进行实际比较，感觉后者时更好的方式，学习之～ 
4. 2个我没有注意到的问题被我引用到自己的笔记了，感谢之～

## 小建议
> Exercise 3
> 2. 若想数字的计算结果出现小数，有3种形式
> 22.0 / 7
> 22 / 7.0
> 22.0 / 7.0

ps：您看这样的表达会不会更简洁些：只要算式中的任意数字为浮点型，则输出也为浮点型。

谢谢@OMlalala 同学～

**Comment by OMlalala** [comment]
### Exercise 12
1. 突然发现，练习12和练习11的输出结果是一样的！！之前快速过练习1-17时，竟然没有发现。。

2. 最近一次敲代码是3天前，今天果然手生了。。想起了小时候学舞蹈，老师注重我们的基本功，督促我们每天要劈叉弯腰，经典话语：一天不练自己知道，三天不练家长知道，一周不练老师知道。。

3. 面对练习11同样的输出结果，即使之前曾经做过`raw_input`的练习，今天还是连敲了两次错误代码。
- 错误情形1：
代码：
```
age = print raw_input("How old are you?")
height = print raw_input("How tall are you?")
weight = print raw_input("How much do you weight?")

print "So, you're %r old, %r tall and %r heavy." % ( age, height, weight)
```
结果：
![1](https://cloud.githubusercontent.com/assets/10447824/21581831/7ff9ad26-d07c-11e6-85c0-c82fca69a28f.png)

- 错误情形2
代码：
```
print age = raw_input("How old are you?")
print height = raw_input("How tall are you?")
print weight = raw_input("How much do you weight?")

print "So, you're %r old, %r tall and %r heavy." % ( age, height, weight)
```
结果：
![2](https://cloud.githubusercontent.com/assets/10447824/21581833/9eedbb1e-d07c-11e6-927f-0ade295548d4.png)

直到第三次，才真正敲。。即使在练习11中，我已经总结过一次 `raw_input`。。
```
age = raw_input("How old are you? ")
height = raw_input("How tall are you? ")
weight = raw_input("How much do you weight? ")

print "So, you're %r old, %r tall and %r heavy." % (age, height, weight)
```
4. 作者在 Study Drills 中提到召唤 `pydoc `, 通过尝试，在Windows系统中，下面两种方式都可以召唤。
- `pydoc raw_input`
- `python -m pydoc raw_input`
考虑到简洁性，今后使用第一种。


`faketooth`：换一个角度看待这个问题，也许就不需要这么多练习了。Python 2.x 语法中有两类语句：`print语句`和`赋值语句`，你的报错是因为混用了这两类语句。如果放在 Python 3.x，会有什么不同呢？

**Comment by VyGiBe** [comment]
你做的好用心啊~
@OMlalala 可以在计划清单中加个复习提醒~
或者把知识点放进Anki这样的软件中设置间隔复习，再回顾~

**Comment by OMlalala** [comment]
### Exercise 13
1. 两个概念。代码`from sys import argv`中，`sys` 是 modules (feature / libraries) , `argv` 是 function.

2. [`import sys` 和` from sys import argv `的区别](http://softwareengineering.stackexchange.com/questions/187403/import-module-vs-from-module-import-function)
2.1 代码
```
from sys import argv
a, b = argv
print "The script is called: ", a
print "Your first variable is: ", b
```
```
import sys
a, b = sys.argv
print "The script is called: ", a
print "Your first variable is: ", b
```
注意，是 `sys.argv`

2.2 运行速度。反常识：二者一样，python 都会扫描一遍 `sys` 库

2.3 结论：建议使用 `import sys`

3. 为什么只能` a, b, c = argv` 而不能 `argv = a, b, c` ?
结论：` sys.argv` 是一个` list`, 除了教材中的命名方式，还可以：
```
import sys
a = sys.argv[0]
b = sys.argv[1]
c = sys.argv[2]
```

**Comment by OMlalala** [comment]
### Exercise 14
1. 复习了format characters的语法，不论是几个参数，都使用 `%` 而不是`，`逗号
代码：
```
print "Do you like me %s?" ， user_name
print "Do you like me %s?" % user_name
```
结果：
![1](https://cloud.githubusercontent.com/assets/10447824/21613745/7a407ee6-d211-11e6-84fb-75e45402522d.png)

2. 对 `raw_input(prompt)` 的理解。
在`raw_input`后面括号中的内容可以作为用户输入信息的提示，这里是显示` > `，也可以显示` -->`， 也可以针对不同的问题，设置不同的提示。
```
print "Do you like me %s?" % user_name
ans_1 = raw_input("(Say yes)\n")

print "Where do you live %s?" % user_name
ans_2 = raw_input("(West or East)\n")

print "What kind of computer do you have?"
ans_3 = raw_input("(Win or Mac?)\n")
```

3. 最后一段话，忘了可以使用` “””`

**Comment by OMlalala** [comment]
### Exercise 15
1. 从这个练习开始，开始在提交的代码中，保留自己最开始尝试的代码。之前是在自己写的代码中直接修改为教材答案，现在发现，保留代码后，更容易找到区别和盲点。

2. 目前接触的 command 有两种
- 像` print`、`open`, 属于built-in functions, 可直接通过 `open()` 使用
- 像 `read`, 属于库里带的函数，需 import, 且通过 `txt.read()` 使用

3. 从CLI和GUI角度理解代码。这一个练习主要是读取文件的内容，我理解相当于用鼠标双击桌面的txt文件，看到文件里面的内容。

**Comment by OMlalala** [comment]
### Exercise 16
1. 解答Study Drill 3. 练习要求：用一行包含 strings, formats, and escapes 的代码改写教材原本六行的代码。  
尝试如下：
代码V1：
`target.write("%s\n%s\n%s\n") % (line1, line2, line3)`
运行结果：
![1](https://cloud.githubusercontent.com/assets/10447824/21647310/b2ec682c-d2d4-11e6-9bc6-cb2ac3cf856d.png)
  
检查代码半天，实在没看出错误。查了文档对`write`的解释，也没看出自己的问题。
后来，发现了一个查询问题的新途径：[stackoverflow里有人已针对此练习提出问题](http://stackoverflow.com/questions/6394170/very-basic-python-question-strings-formats-and-escapes)。通过阅读回答，发现自己代码的问题。
  
代码V2：
`target.write(("%s\n%s\n%s\n") % (line1, line2, line3))`
运行结果：
OK！
为了更好的理解错误点，可以对比代码：
`print "%r\n%r\n%r\n" % (line1, line2, line3)`

2. 解答Study Drill 5.
如果使用 `txt = open(filename, 'w')` 方式打开文档，则无需` target.truncate()`。
因为[文档已经说明](https://docs.python.org/2/tutorial/inputoutput.html)：此模式下，现存文档将被清空。

> 'w' for only writing (an existing file with the same name will be erased)

**Comment by OMlalala** [comment]
### Exercise 17
1. 代码中出现了很多变量：`from_file, to_file, in_file, out_file, indata`, 前两遍敲代码，总是会在使用 `read() `和 `write()` 时出错，原因：未对**文件类型**的对象使用这两个函数。
今天忽然想到，可以用 type() 来查这几个变量的数据类型。
```
print type(from_file)
print type(to_file)
print type(in_file)
print type(out_file)
print type(indata)
```
![1](https://cloud.githubusercontent.com/assets/10447824/21742008/c63ee528-d520-11e6-8f8a-a90f5c06ec74.png)

2. 查询echo 和 cat 的用法。其中，[这篇文章](http://www.linfo.org/cat.html)提到cat的三个用法，练习中涉及的是其第一个用法：reading files， 文章中对这个用法的第二条举例，令人咋舌！
因为如果采取 cat 的第二个用法，整个第17课练习，就可以用一行代码搞定：
`cat test.txt > new_file.txt`
![2](https://cloud.githubusercontent.com/assets/10447824/21742011/e1633ec6-d520-11e6-9000-99ab2c541309.png)
