### ISSUE TITLE
许从用完成Py103入学任务啦

### ISSUE THREAD

**Issue by xucongyong** [AIHackers/PythonStartUp#52]
https://github.com/vanxv/pythonkz

**Comment by CrickeySong** [comment]
任务迁移完成，欢迎分享自己练习过程中的困难和收获哦~

**Comment by sunoonlee** [comment]
不用把 .pyc 文件传上来哦。可了解一下如何让 git 忽略某些文件：  [Ignoring files - User Documentation](https://help.github.com/articles/ignoring-files/)
