### ISSUE TITLE
YCR007完成py103开学任务啦

### ISSUE THREAD

**Issue by yuanchunrong** [AIHackers/PythonStartUp#57]
[作业地址](https://github.com/YCR007/YCR007-s-python-exercise)

**Comment by yuanchunrong** [comment]
## 一点点感想
作为一个完完全全的小白，之前一直很想要学习编程，但是没有用来参与实践，所以这个想法也就不了了之了，参加开智课程，才真正的上手编程的过程：

自己开始搭建环境，这个过程中，遇到了不少的问题，都有一点点自暴自弃了于是用issues发消息进行求职，感谢各位同侪们的热心建议，最终顺利完成了环境的搭建；

当一次看到电脑打印出“Hello wold”时真的是异常激动，哈哈~；

后面做17道练习题的过程相对而言是比较顺利的，只要过程中细心就行，只是对于每个语言符号的调用以及相关规则还需要多多的练习；

在这个过程中，逐渐的体会到了程序猿严谨细致的思维，阳老之前提到批量化处理问题的思维在这里得到了体现，自己对于信息的收集处理方式好像有了不同的体会，可惜没办法用文字表达出来，看来还需要多多练习

现在对于python编程之旅充满期待，非常期待未来的3个月和各位同侪们共同学习，最终写出一个小而美的程序运用于现实生活中~

-161227 by 小蓉

**Comment by liangpeili** [comment]
从成功打印出“hello world”开始，你就是一名程序媛啦
