### ISSUE TITLE
Corey 完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by chuanwj** [AIHackers/PythonStartUp#58]
前面17个小练习
[Learn python the hardway ](https://github.com/chuanwj/learn-python-the-hardway) 

之前是看 廖雪峰的教程，所以感觉 hardway里面的练习相对较容易些
分享下教程： [ 廖雪峰的官方网站 --Python3教程](http://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000)
感觉他写的教程都很通俗易懂

**Comment by liangpeili** [comment]
他的教程确实不错（虽然从元类开始难度陡升）
