### ISSUE TITLE
ex7运行故障，求指导。

### ISSUE THREAD

**Issue by fandongdong89** [AIHackers/PythonStartUp#59]
<img width="597" alt="ex7_py_ ___new" src="https://cloud.githubusercontent.com/assets/18494170/21491232/300c6942-cc36-11e6-94f8-8b0f0028564f.png">

Title：ex7运行不了，自己无法排除故障。

## 现象

- 输入：以下是我按照exercise 7 指示的输入的代码

1 print "Mary had a little lamb."
2 print "Its fleece was white as %s." % 'snow'
3 print "And everywhere that Mary went."
4 print "." * 10  # what'd that do？

7 end1 = "C"
8 end2 = "h"
9 end3 = "e"
10 end4 = "e"
11 end5 = "s"
12 end6 = "e"
13 end7 = "B"
14 end8 = "u"
15 end9 = "r"
16 end10 = "g"
17 end11 = "e"
18 end12 = "r"

21 # watch that comma at the end. try removing it to see what happens
22 print end1 + end2 + end3 + end4 + end5 + end6,
23 print end7 + end8 + end9 + end10 + end11 + end12

- 问题：在Terminal中运行，故障提示为  
File "new/ex7.py", line 4
SyntaxError: Non-ASCII character '\xef' in file new/ex7.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
fandongdongdeMacBook-Pro:~ fandongdong$ python new/ex8.py

**Comment by simpleowen** [comment]
第4行是八是有中文状态下输入的字符，那个问号?？
[碰到过](http://www.jianshu.com/p/a5fe69183dd0)
[google搜索，第1条也可以找到原因](http://stackoverflow.com/questions/10589620/syntaxerror-non-ascii-character-xa3-in-file-when-function-returns-%C2%A3)

**Comment by kunbao7** [comment]
第四行的问号，要么切换到英文状态下，要么在文件头加编码注释# -*- coding: utf-8 -*-

**Comment by liangpeili** [comment]
确实是中文字符集的问题

**Comment by fandongdong89** [comment]
谢谢大神，加编码注释之后，成功了。谢谢！

在 2016-12-27 13:37:41，"kunbao7" <notifications@github.com> 写道：


第四行的问号，要么切换到英文状态下，要么在文件头加编码注释# -- coding: utf-8 --

**Comment by sunoonlee** [comment]
@fandongdong89 小提醒：问题解决后，最好可以把解决方案简要更新在首层，然后关闭 issue~

**Comment by fandongdong89** [comment]
谢谢大神，加编码注释之后，成功了。谢谢！

在 2016-12-27 13:37:41，"kunbao7" <notifications@github.com> 写道：


第四行的问号，要么切换到英文状态下，要么在文件头加编码注释# -- coding: utf-8 --
