### ISSUE TITLE
SeanLu 完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by YoungSean** [AIHackers/PythonStartUp#60]
https://github.com/Sean-Lu/Learn-Python-the-Hard-Way

之前用的是python3的版本，PyCharm 来写代码。

**Comment by liangpeili** [comment]
用 Python3， 不错……
不过上面的地址最后面的括号是中文的，导致 Markdown 语法没生效

**Comment by YoungSean** [comment]
感谢提醒。 修改了下
