### ISSUE TITLE
Tracy_CUHK(李如)完成Py103 入学任务啦

### ISSUE THREAD

**Issue by Tracy-CUHK** [AIHackers/PythonStartUp#62]
Title：Tracy_CUHK(李如)完成Py103 入学任务啦

仓库地址：https://github.com/Tracy-CUHK/Python_ex1-17.git

**Comment by zhangshiyinrunwithcc** [comment]
@Tracy-CUHK 
- 哇喔！CUHK的人也来了！
- 哇喔，用本地库直接推送到远程库的
- 厉害厉害

**Comment by Tracy-CUHK** [comment]
@zhangshiyinrunwithcc 
怎么能看出来是本地库推送的呀？我查的教程，今天第一次用github，你更加厉害！！

**Comment by zhangshiyinrunwithcc** [comment]
@Tracy-CUHK 
- 哈哈 原来是我看错了；
- 我看到你的仓库里显示`Upload file` , 就以为你是用本地库推送到远程库的；
- 今天才发现，原来网页版可以直接`Upload file`.

![default](https://cloud.githubusercontent.com/assets/19412465/21516288/c02b20c8-cd11-11e6-9a65-2256841baca4.png)

**Comment by Tracy-CUHK** [comment]
@zhangshiyinrunwithcc 
我是用git命令行把练习add上去的，那个"upload exercises 1-17 to my Github" 是我再add文件的时候自己添加的message ：）
