### ISSUE TITLE
BravoCiao 完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by BravoCiao** [AIHackers/PythonStartUp#64]
参考资料：
 - Learn Python The Hard Way – Zed A. Shaw
 - LPTHW Youtube Series – Bart Paulson 
 -  参考网上中文版教材对应术语，教程部分以英文版为准

https://github.com/BravoCiao/PY103_Bravo

第一次学编程，前九个练习过得比较快，从第十个练习开始用#在代码里写评论，记下了自己不懂的或者注意要点
过完第十九个练习回过头去看前九个补评论，发现有些细节问题还是不够清楚的
课后练习能力范围内的都做了

**Comment by sunoonlee** [comment]
笔记挺详细，而且都是英文写的，Bravo!

遇到问题，优先查阅官方文档。比如你遇到的[这个问题](https://github.com/BravoCiao/PY103_Bravo/blob/master/ex16.py#L47)，查一下 Python 官方文档里 open 函数的说明就清楚了（比如 google 搜 python open，前两个便是），或许比你在 youtube 视频里找答案更快？

**Comment by BravoCiao** [comment]
恩，查了一下确实是这样，但是不知道为什么，在terminal里面用pydoc搜出来的解释要短得多，我以为那个就是官方文档了
实不相瞒，我是注意要先查阅官方文档的，也是过完教材才去看Youtube
但奇怪的是，官方文档里面每一个英文单词都认识，连起来就感觉没说人话
就像raw_input()，我一开始不太懂编程，看了三遍都不是很清楚它在说什么，可能是我英文造旨不够高吧~
新学习模式还要再多磨合磨合，感谢啦~

**Comment by sunoonlee** [comment]
> 官方文档里面每一个英文单词都认识，连起来就感觉没说人话

😆  大概是因为，同样的英文词在编程语境下含义不同，需要一些背景知识。
比如 [raw_input](https://docs.python.org/2/library/functions.html#raw_input) 短短的两句文档里头，argument、standard output、strip、raise 等等，都可算是术语了。等你有一些背景知识以后，读起来就没那么难了。

官方文档可能不会去照顾初学者的感受。相对来说，针对初学者的书籍（或者文档里的 Tutorial/Quick Start 部分）要友好得多。建议手边备一本这样的书（比如 Core Python Programming 或 Beginning Python: From Novice to Professional）。

xbaiyuan 同学在笔记 [review_why_hard_is_easy](https://github.com/xbaiyuan/lpthw_practice/blob/master/review_why_hard_is_easy.md) 里总结得好：

> 持续练习编程的初学者会在某一天获得Aha moment，这个Moment意味着，在「读」的阶段，大量的外显知识已经转化为内隐知识，工作记忆的负荷大大减少；在「写」的阶段，肌肉记忆已经形成，Linus级别的程序员，应该就像李小龙和宫本武藏那样无招胜有招——在看到对方产生打击动作的一瞬间，无需大脑的意识，肌肉记忆会做出一系列反应。

虽然跟前面说的并不是一回事，但 `Aha moment` 是相通的。

**Comment by BravoCiao** [comment]
恩恩，我特别爱抠细节，所以深有感触。
以前在做别的事情时感受过Aha moment，真是一种私房乐趣~
