### ISSUE TITLE
[谭笃志]完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by code661** [AIHackers/PythonStartUp#69]
[作业地址](https://github.com/code661/lpthw_openmind.git)

早早的就接触到了这本入门教材，因为英语较差的缘故便买了中译版本。但接触编程越深，就越发的认识到英语的重要性。fighting！

**Comment by code661** [comment]
@ishanshan 你好，有个小问题需要咨询。
付了学费也完成了入学任务，但是**忘记填写个人信息表格**了
联系微信里的一休同学没有回复，所以来Github里面来询问一下

**Comment by sunnyhuang42** [comment]
>但是忘记填写个人信息表格了


@code661  现在填写了吗？填写后一个工作日内，会收到欢迎邮件哦。

已把你的留言转达相关同事，不过现在元旦休假，处理速度会慢些。

等待的时间，可以先自行探索一下 Python3 和 Python2 的区别，并用 Python3 改写 LPTHW 里 3-7 个小练习（ch0 任务之一）。

**Comment by code661** [comment]
现在已经填写啦，了解情况啦。谢谢你了
