### ISSUE TITLE
Davidfupenghao完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by davidfph** [AIHackers/PythonStartUp#70]
[练习地址](https://github.com/Davidfupenghao/learnPythonTheHardWayPython3.git)
练习是用 python 3 写的，希望符合老师的要求。。。。
还有3个之前写过的小爬虫，望老师指导。
有咨询一休说正式开课是采用 python 3 的环境，而自己之前也一直是用 python 3 ，所以就直接拿 python 3 来进行作业了。
心得
---
在写练习的时候因为书上都是 python 2 程序，之前没有仔细研究过2和3的不同，这次也算是简单了解了一下，某些地方的改版还是非常好的，比如 print 的括号，感觉上比不加括号要清楚很多。

**Comment by liangpeili** [comment]
还写过爬虫啊，赞

**Comment by davidfph** [comment]
谢谢！
小程序，，只是方便工作而已→_→
