### ISSUE TITLE
yusi完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by goldandelion** [AIHackers/PythonStartUp#78]
https://github.com/goldandelion/learn-python

**Comment by liangpeili** [comment]
你点击下链接可以访问到吗？问题出在哪里？

**Comment by goldandelion** [comment]
@sunoonlee 解决了，好神奇，用add a link加链接就不能访问 直接复制黏贴就可以

**Comment by sunoonlee** [comment]
add a link 的 [姿势](https://guides.github.com/features/mastering-markdown/) 可能不对哦
