### ISSUE TITLE
Veronicabai 完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by VeronicaBai** [AIHackers/PythonStartUp#80]
https://github.com/VeronicaBai/Learn-Python-the-hard-way

**Comment by sunoonlee** [comment]
欢迎~ 敲了这么些代码，有何感想？

另外有空的话可以做个小任务：

把你的某一个练习代码（比如说 ex14 ）拿出来跟原书上仔细对比一下，看看在细节上（特别是空格的使用）跟范例有什么不同？

再进一步可以阅读一下 google python code style 里[对空格的建议](https://google.github.io/styleguide/pyguide.html?showone=Whitespace#Whitespace)
