### ISSUE TITLE
CeciliaCheng完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by ceciliacheng** [AIHackers/PythonStartUp#81]
我想我应该完成了   https://github.com/ceciliacheng/python

**Comment by sunoonlee** [comment]
```
占坑可耻
填坑光荣
: )
```

**Comment by ceciliacheng** [comment]
https://github.com/ceciliacheng/python

**Comment by liangpeili** [comment]
还差ex16和ex17  ：）

**Comment by ceciliacheng** [comment]
https://github.com/ceciliacheng/python 更新了@liangpeili

**Comment by ceciliacheng** [comment]
请问顺利开课之后,要经常用GitHub吗?
我觉得GitHub比Python还要难T_T...

**Comment by sunoonlee** [comment]
GitHub 会是课程主要的输出和讨论平台。不要心急，多花点时间就熟悉了，到后面你会发现常用到的操作并不多。
