### ISSUE TITLE
于耀程完成Py103入学任务啦

### ISSUE THREAD

**Issue by MagicCheng** [AIHackers/PythonStartUp#83]
- https://github.com/MagicCheng/efp
- 以前做过这些练习，从新做了下，感觉以前的都忘了，但做第二遍好像有点新发现。在外地，编程时间少。等回家再把后面的都补上。

**Comment by noylau** [comment]
我也是这个情况，重新练习之后貌似明白多了...

**Comment by sunoonlee** [comment]
可以用零碎时间在手机上做这个练习： [Python 3 Tutorial | SoloLearn: Learn to code for FREE!](https://www.sololearn.com/Play/Python#)。有手机APP。
