### ISSUE TITLE
SophieXS完成Py103入学任务啦

### ISSUE THREAD

**Issue by SophieXS** [AIHackers/PythonStartUp#84]

**Comment by SophieXS** [comment]
https://github.com/SophieXS/Python103-Start-uP

**Comment by sunoonlee** [comment]
加油，还剩 5 个。敲代码时尽量别漏掉范例里的空格，比如，一般来说，赋值符号两侧都该有的。

**Comment by SophieXS** [comment]
经常想偷懒，觉得不敲空格也没有影响到程序的运行，就没怎么注意这个格式了。

**Comment by sunoonlee** [comment]
这些其实都是小问题。先把代码写起来最重要。 😃
