### ISSUE TITLE
otomo完成py103入学任务啦

### ISSUE THREAD

**Issue by otomobao** [AIHackers/PythonStartUp#88]
[https://github.com/otomobao/Learn_python_the_hard_way_](https://github.com/otomobao/Learn_python_the_hard_way_)

**Comment by otomobao** [comment]
Mac上用Github Desktop同步的时候遇到了问题，看别的同学可以同步成功。先休息一下，睡醒后再看看怎么同步。。。
之前看了另外一本书《python 基础教程》只看了不到一章，再看这本书的时候通过对比发现这本超级适合我这种0基础的初学者，边学边写边想。感受到了课程老师在选资料上面就英明神武！
开智学堂结合认知科学让学习编程更有乐趣。lol

**Comment by otomobao** [comment]
[https://github.com/otomobao/Learn_python_the_hard_way_](https://github.com/otomobao/Learn_python_the_hard_way_
)

现在链接OK了，不知道为啥 最后一个下划线“_"被吞掉了，链接到之前一个链接了。手动添加了正确链接。。

**Comment by otomobao** [comment]
[[https://github.com/otomobao/Learn_python_the_hard_way_](https://github.com/otomobao/Learn_python_the_hard_way_)

**Comment by NBR-hugh** [comment]
[GitHub入门与实践 (豆瓣)](https://book.douban.com/subject/26462816/)
关于git同步的问题这本书有详细的操作示例，再结合网上的一些图示教程，希望对您有所帮助。

**Comment by otomobao** [comment]
感谢！ @NBR-hugh 
立刻去下了电子版
