### ISSUE TITLE
孙蕾（Sam/Mental-rotation）完成Python103 入学任务啦

### ISSUE THREAD

**Issue by Mental-rotation** [AIHackers/PythonStartUp#99]
练习成果：https://github.com/Mental-rotation/Sam
在练习过程中对一些编程语言似懂非懂，需要进一步识记应用。
准备看看《黑客与画家》。
希望在老师和同学的互动过程中，能迈入编程世界。

**Comment by ouyangzhiping** [comment]
不懂的地方，也许可以尝试写下笔记，时隔三个月后，再回头看看自己笔记:D

**Comment by Mental-rotation** [comment]
好的杨老师，已经记录下了一些问题。
